### ISSUE TITLE
dropwizard-jdbi with MySQL connection closed error

### ISSUE THREAD

**Issue by martintreurnicht** [dropwizard/dropwizard#1096]
I've configured my application exactly as instructed on http://www.dropwizard.io/manual/jdbi.html, with mysql. Everything works perfectly fine but after the application goes into idle for a long time i start getting these errors:

```
! at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_45-internal]
! at com.mysql.jdbc.Util.handleNewInstance(Util.java:377) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.Util.getInstance(Util.java:360) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.ConnectionImpl.throwConnectionClosedException(ConnectionImpl.java:1232) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:1225) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4100) ~[giftblock-pos.jar:na]
! at com.mysql.jdbc.ConnectionImpl.prepareStatement(ConnectionImpl.java:4069) ~[giftblock-pos.jar:na]
! at sun.reflect.GeneratedMethodAccessor19.invoke(Unknown Source) ~[na:na]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_45-internal]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_45-internal]
! at org.apache.tomcat.jdbc.pool.ProxyConnection.invoke(ProxyConnection.java:126) ~[giftblock-pos.jar:na]
! at org.apache.tomcat.jdbc.pool.JdbcInterceptor.invoke(JdbcInterceptor.java:108) ~[giftblock-pos.jar:na]
! at org.apache.tomcat.jdbc.pool.DisposableConnectionFacade.invoke(DisposableConnectionFacade.java:81) ~[giftblock-pos.jar:na]
! at com.sun.proxy.$Proxy65.prepareStatement(Unknown Source) ~[na:na]
! at org.skife.jdbi.v2.DefaultStatementBuilder.create(DefaultStatementBuilder.java:48) ~[giftblock-pos.jar:na]
! at org.skife.jdbi.v2.SQLStatement.internalExecute(SQLStatement.java:1304) ~[giftblock-pos.jar:na]
! ... 73 common frames omitted
! Causing: org.skife.jdbi.v2.exceptions.UnableToCreateStatementException: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
```

**Comment by martintreurnicht** [comment]
I'm trying out setting `checkConnectionOnBorrow` to `true` in the DataSourceFactory configuration. I'll keep you posted on the result

**Comment by arteam** [comment]
Yes, it should do the trick. Also, if you know a timeout, after which your MySQL backend drops idle connections, you could try to limit the lifetime of a connection by specifying `maxConnectionAge`.

**Comment by joschi** [comment]
@martintreurnicht Any updates on the issue?

**Comment by martintreurnicht** [comment]
Yes making that change did resolve the issue, thanks

**Comment by carlo-rtr** [comment]
great!
