### ISSUE TITLE
Read Timed out with jersey-media-moxy

### ISSUE THREAD

**Issue by Toilal** [dropwizard/dropwizard#1110]
I've created a maven project to showcase this issue : https://github.com/Toilal/dropwizard-moxy-issue.

The project contains a minimalist [Dropwizard application](https://github.com/Toilal/dropwizard-moxy-issue/blob/master/src/main/java/App.java) with a [single resource](https://github.com/Toilal/dropwizard-moxy-issue/blob/master/src/main/java/Ressource.java), a single @GET returning a basic [Entity](https://github.com/Toilal/dropwizard-moxy-issue/blob/master/src/main/java/Entity.java) object.

It also contains a dependency to `jersey-media-moxy` which seems to cause the issue.

```xml
<dependency>
    <groupId>org.glassfish.jersey.media</groupId>
    <artifactId>jersey-media-moxy</artifactId>
    <version>${jersey.version}</version>
</dependency>
```

When creating a simple [Integration test calling this method through JerseyClientBuilder](https://github.com/Toilal/dropwizard-moxy-issue/blob/master/src/test/java/AppTest.java#L31), first call to the method fails with ```java.net.SocketTimeoutException: Read timed out``` : 

```
> git clone https://github.com/Toilal/dropwizard-moxy-issue
...
> cd dropwizard-moxy-issue
> mvn test
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building read-timeout-issue 0.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ read-timeout-issue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.3:compile (default-compile) @ read-timeout-issue ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ read-timeout-issue ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.3:testCompile (default-testCompile) @ read-timeout-issue ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ read-timeout-issue ---
[INFO] Surefire report directory: C:\Users\QFXS1905\Documents\workspace442\read-timeout-issue\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running AppTest
INFO  [2015-06-09 14:32:35,408] org.eclipse.jetty.util.log: Logging initialized @3553ms
INFO  [2015-06-09 14:32:35,755] io.dropwizard.server.ServerFactory: Starting App
INFO  [2015-06-09 14:32:35,941] org.eclipse.jetty.setuid.SetUIDListener: Opened App@53687596{HTTP/1.1}{0.0.0.0:9914}
INFO  [2015-06-09 14:32:35,947] org.eclipse.jetty.server.Server: jetty-9.2.9.v20150224
INFO  [2015-06-09 14:32:37,704] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    GET     / (Ressource)

INFO  [2015-06-09 14:32:37,718] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@597b2bb1{/,null,AVAILABLE}
INFO  [2015-06-09 14:32:37,737] io.dropwizard.setup.AdminEnvironment: tasks =

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

WARN  [2015-06-09 14:32:37,738] io.dropwizard.setup.AdminEnvironment:
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INFO  [2015-06-09 14:32:37,753] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@aacc7fa{/admin,null,AVAILABLE}
INFO  [2015-06-09 14:32:37,821] org.eclipse.jetty.server.ServerConnector: Started App@53687596{HTTP/1.1}{0.0.0.0:9914}
INFO  [2015-06-09 14:32:37,822] org.eclipse.jetty.server.Server: Started @5969ms
127.0.0.1 - - [09/juin/2015:14:32:40 +0000] "GET / HTTP/1.1" 200 20 "-" "App (test client)" 1836
INFO  [2015-06-09 14:32:42,210] org.eclipse.jetty.server.ServerConnector: Stopped App@53687596{HTTP/1.1}{0.0.0.0:9914}
INFO  [2015-06-09 14:32:42,212] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@aacc7fa{/admin,null,UNAVAILABLE}
INFO  [2015-06-09 14:32:42,223] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@597b2bb1{/,null,UNAVAILABLE}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 9.949 sec <<< FAILURE!
testImpl(AppTest)  Time elapsed: 3.08 sec  <<< ERROR!
javax.ws.rs.ProcessingException: java.net.SocketTimeoutException: Read timed out
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:111)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:245)
        at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:687)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:683)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:307)
        at AppTest.testImpl(AppTest.java:31)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.read(SocketInputStream.java:152)
        at java.net.SocketInputStream.read(SocketInputStream.java:122)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:136)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:152)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:270)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:140)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:260)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:161)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:153)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:271)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:123)
        at com.codahale.metrics.httpclient.InstrumentedHttpRequestExecutor.execute(InstrumentedHttpRequestExecutor.java:44)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:254)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:106)
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:89)
        ... 42 more


Results :

Tests in error:
  testImpl(AppTest): java.net.SocketTimeoutException: Read timed out

Tests run: 1, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 17.122 s
[INFO] Finished at: 2015-06-09T16:32:42+02:00
[INFO] Final Memory: 14M/177M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project read-timeout-issue: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\QFXS1905\Documents\workspace442\read-timeout-issue\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

Removing the dependency to `jersey-media-moxy` make the test pass properly. Also, next calls will work (i've tested by catching the first call and adding others later, it just works as expected).

Maybe the configuration of moxy occurs while server is responding, reseting connections to current clients ?

**Comment by Toilal** [comment]
I found the solution for this issue.

Default timeout value of apache HttpClient is set by dropwizard-client to 500ms for default value. Problem is that many things in Jersey are lazy initialized on first call.

Moxy seems to be quite longer to initialize than Jackson, and the call is about 1000ms to respond, causing the "Read timed out" exception.

By configuring a timeout to 4000ms, it just works.

```java
HttpClientConfiguration httpClientConfiguration = new HttpClientConfiguration();
httpClientConfiguration.setTimeout(Duration.milliseconds(4000));

HttpClientBuilder clientBuilder = new HttpClientBuilder(app.getEnvironment());
clientBuilder.using(httpClientConfiguration);

JerseyClientBuilder builder = new JerseyClientBuilder(app.getEnvironment());
builder.setApacheHttpClientBuilder(clientBuilder);

client = builder.build("test client");
```

I think this default timeout value defined in dropwizard-client is really low ... Would you consider increasing it ?

**Comment by mattnelson** [comment]
Dropwizard already allows you customize those values through configuration.

http://www.dropwizard.io/manual/configuration.html#clients

**Comment by arteam** [comment]
@Toilal, glad your issue is resolved. 

About the default timeout: 500 ms seems like a reasonable default for a typical web request. Personally, I think that applications should rely to retrying logic, rather then to constant timeout values. It provides more fine-grained recovery in cases of network failures, GC spikes or temporary remote server availability(especially if it's a cluster). 

Anyway, users have a broad control on this and I think that the current timeout is fine.
