### ISSUE TITLE
NoClassDefFoundError on clean checkout

### ISSUE THREAD

**Issue by jtmelton** [dropwizard/dropwizard#1155]
I tried doing a fresh clone of dropwizard, and tried testing the sample application. The tests (4) all fail with this error: 
```
Running com.example.helloworld.resources.ProtectedResourceTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.01 sec <<< FAILURE!
com.example.helloworld.resources.ProtectedResourceTest  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.NoClassDefFoundError: javax/servlet/DispatcherType
	at org.glassfish.jersey.test.ServletDeploymentContext.builder(ServletDeploymentContext.java:103)
	at io.dropwizard.testing.junit.ResourceTestRule$1$1.configureDeployment(ResourceTestRule.java:188)
	at org.glassfish.jersey.test.JerseyTest.<init>(JerseyTest.java:206)
	at io.dropwizard.testing.junit.ResourceTestRule$1$1.<init>(ResourceTestRule.java:179)
	at io.dropwizard.testing.junit.ResourceTestRule$1.evaluate(ResourceTestRule.java:179)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
Caused by: java.lang.ClassNotFoundException: javax.servlet.DispatcherType
	at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 19 more
```
It appears that javax.servlet-api is being pulled in and DispatcherType should be in there, so not sure where the issue is, but wanted to file the issue.

**Comment by joschi** [comment]
Just tried to reproduce this in a fresh checkout but everything worked correctly. Please make sure that you're either using a released and tagged version (e. g. https://github.com/dropwizard/dropwizard/tree/v0.9.0-rc1) or that you build and locally deploy (`mvn install`) the complete project. Mixing SNAPSHOT versions will lead to such errors.

**Comment by jtmelton** [comment]
Just wanted to leave a note here describing what the issue was: maven had a corrupted download a the servlet-api jar which was causing this error. That error didn't show up until I did another fresh checkout, and then tried to build the full project. Deleting the jar from my local repo and re-downloadng it solved the problem. Hopefully this will help anybody who runs across the same issue.

**Comment by ryankennedy** [comment]
Would --strict-checksums have caught this? Seems like a good thing to set, assuming it's not already the default behavior.

**Comment by jtmelton** [comment]
Yes, this seems like a reasonable approach to me.
