### ISSUE TITLE
Configuration fails to parse when inner classes are involved in v0.7.1

### ISSUE THREAD

**Issue by jimbodude** [dropwizard/dropwizard#1167]
We saw this when upgrading from 0.6, where this worked, to 0.7.1, where it doesn't.  See this test, which fails with the exception noted below:
https://github.com/dropwizard/dropwizard/compare/release/0.7.x...jimbodude:inner-classes-in-configs-0.7.1

Inner classes in configs appear to be working just fine on latest.  This test passes:
https://github.com/dropwizard/dropwizard/compare/master...jimbodude:inner-classes-in-configs-0.9

The failure looks something like:
```
io.dropwizard.configuration.ConfigurationParsingException: /path/to/test/factory-test-innerclass.yml has an error:
  * Failed to parse configuration at: inner.bigNumber; Can not deserialize instance of long out of END_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.dropwizard.configuration.ExampleWithInnerClasses["inner"]->io.dropwizard.configuration.Inner["bigNumber"])

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:269)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:151)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:77)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:101)
	at io.dropwizard.configuration.ConfigurationFactoryTest.handleInnerClasses(ConfigurationFactoryTest.java:262)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of long out of END_OBJECT token
 at [Source: N/A; line: -1, column: -1] (through reference chain: io.dropwizard.configuration.ExampleWithInnerClasses["inner"]->io.dropwizard.configuration.Inner["bigNumber"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:164)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:691)
	at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseLong(StdDeserializer.java:395)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:350)
	at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$LongDeserializer.deserialize(NumberDeserializers.java:332)
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:525)
	at com.fasterxml.jackson.module.afterburner.deser.SettableObjectFieldProperty.deserializeAndSet(SettableObjectFieldProperty.java:53)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:149)
	at com.fasterxml.jackson.databind.deser.impl.InnerClassProperty.deserializeAndSet(InnerClassProperty.java:102)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserializeFromObject(SuperSonicBeanDeserializer.java:209)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:118)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:2965)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:1587)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:125)
	... 31 more
```

We've seen FIELD_NAME instead of the END_OBJECT token too, depending on what the config file looks like.  FIELD_NAME occurs if you have more than one field within the inner class.  It looks like the value part is simply not making it into the tree for some reason.

The workaround for this is simple enough - pull the inner classes out into their own classes, then things work just fine.

**Comment by arteam** [comment]
The issue is probably caused by a changed configuration format between 0.6/0.7 or some Jackson bug. Anyway, 0.7.* branch is not supported anymore. If the issue is stiill exist in 0.8/0.9, feel free to open a new issue.
