### ISSUE TITLE
Error while starting the application using java -jar

### ISSUE THREAD

**Issue by zarub2k** [dropwizard/dropwizard#1189]
I am getting the following error while I start the server using "java -jar abc.jar server configuration.yml"

Exception in thread "main" java.lang.VerifyError: class com.fasterxml.jackson.datatype.guava.deser.HostAndPortDeserializer overrides final method deserialize.(Lcom/fasterxml/jackson/core/JsonParser;Lcom/fasterxml/jackson/databind/DeserializationContext;)Ljava/lang/Object;
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at com.fasterxml.jackson.datatype.guava.GuavaModule.setupModule(GuavaModule.java:22)
        at com.fasterxml.jackson.databind.ObjectMapper.registerModule(ObjectMapper.java:537)
        at io.dropwizard.jackson.Jackson.configure(Jackson.java:41)
        at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:23)
        at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64)
        at io.dropwizard.Application.run(Application.java:68)

**Comment by zarub2k** [comment]
I resolved the problem by addressing the maven jar conflict. 
<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-databind</artifactId>
				<version>2.5.1</version>
			</dependency>

I added the above dependency in my <dependencyManagement> and the problem is resolved. This particular jar is conflicted with 2.4.4 version jar.

**Comment by zarub2k** [comment]
Resolved by me

**Comment by stantonk** [comment]
@zarub2k thx!

**Comment by VinnuKVK** [comment]
Thanks buddy! :)

**Comment by kaydoubleu** [comment]
Had the same issue; getting the error "com.fasterxml.jackson.datatype.guava.deser.HostAndPortDeserializer overrides final method deserialize".
This could be resolved by updating to a newer version. In my case from *2.2.2* to *2.8.8*.
Thank you :)
