### ISSUE TITLE
Query param validation not working properly on bean param subclasses

### ISSUE THREAD

**Issue by StanSvec** [dropwizard/dropwizard#1227]
Given following classes:
```java
public class BaseClass {

    @NotNull
    @QueryParam("startDate")
    protected LocalDate startDate;

    public LocalDate getStartDate() {
        return startDate;
    }
}

public class SubcClass extends BaseClass {
    ...
}

@Path("path")
public class QuantityResource {

    @GET
    public ResponseEntity working(@Valid @BeanParam BaseClass req) {
    	...    
    }

    @GET
    public ResponseEntity notWorking(@Valid @BeanParam SubClass req) {
    	...    
    }
}
```
If `working` method is executed and startDate query param is missing then correct HTTP Bad Request response with corresponding message is returned. However if `notWorking` method is executed and startDate query param is missing then 500 interval server error is returned and an exception is logged:
```
ERROR [2015-08-19 12:27:42,396] org.glassfish.jersey.server.ServerRuntime$Responder: An exception has been thrown from an exception mapper class io.dropwizard.jersey.validation.ConstraintViolationExceptionMapper.
! java.lang.NullPointerException: null
! at io.dropwizard.jersey.validation.ConstraintMessage.getMemberName(ConstraintMessage.java:74) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.validation.ConstraintMessage.calculateMessage(ConstraintMessage.java:54) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.validation.ConstraintMessage.getMessage(ConstraintMessage.java:39) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.validation.ConstraintViolationExceptionMapper$1.apply(ConstraintViolationExceptionMapper.java:24) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at io.dropwizard.jersey.validation.ConstraintViolationExceptionMapper$1.apply(ConstraintViolationExceptionMapper.java:21) ~[dropwizard-jersey-0.9.0-rc3.jar:0.9.0-rc3]
! at com.google.common.collect.Iterators$8.transform(Iterators.java:799) ~[guava-18.0.jar:na]
```
The cause is that `io.dropwizard.jersey.validation.ConstraintMessage.getMemberName` method is using `FieldUtils.getDeclaredField` method for getting required instance field. However this method returns only fields declared on the class and not on superclasses. Using `FieldUtils.getField` might help???

**Comment by nickbabcock** [comment]
Thanks for the bug report, since this is the feature that I implemented, I can take a look into this.

**Comment by StanSvec** [comment]
That was super quick! :+1:  I wish to see such pace on commercially supported products. :) Thanks a lot.
