### ISSUE TITLE
Metrics registry duplicate metric issue

### ISSUE THREAD

**Issue by gautampriya** [dropwizard/dropwizard#1258]
Referencing https://github.com/dropwizard/dropwizard/issues/832

This above issue still exists. I am struggling with it right now. While it is true that one can provide unique names, however, if I want to use a fresh client each time I need a new one in the same class/test class/(in general in the same context), then this issue is limiting my approaches. What are the reasons that the behaviour was changed in 0.8.0 in a way that introduces this bug/limitation. Can the metrics registry be cleared when a client is closed? Is there a plan to fix this issue? What is the work around for now short of supplying unique names.

I am using dropwizard-client 0.8.2

java.lang.IllegalArgumentException: A metric named org.apache.http.conn.HttpClientConnectionManager.cs.available-connections already exists
at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)
at com.codahale.metrics.httpclient.InstrumentedHttpClientConnectionManager.(InstrumentedHttpClientConnectionManager.java:63)
at io.dropwizard.client.HttpClientBuilder.createConnectionManager(HttpClientBuilder.java:287)
at io.dropwizard.client.HttpClientBuilder.buildWithDefaultRequestConfiguration(HttpClientBuilder.java:182)
at io.dropwizard.client.JerseyClientBuilder.buildConfig(JerseyClientBuilder.java:347)
at io.dropwizard.client.JerseyClientBuilder.build(JerseyClientBuilder.java:315)
at io.dropwizard.client.JerseyClientBuilder.build(JerseyClientBuilder.java:309)

**Comment by arteam** [comment]
This is probably fixed by #1232. Please, check if the issue exists in Dropwizard 0.8.5 or 0.9.1,

**Comment by jplock** [comment]
No feedback, closing
