### ISSUE TITLE
Cannot use metrics reporters in 0.9.0 or 0.9.0-rc5

### ISSUE THREAD

**Issue by achaphiv** [dropwizard/dropwizard#1315]
The following works in 0.9.0-rc4.

Class
```
import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.setup.Environment;

public class App extends Application<Configuration> {
  public static void main(String[] args) throws Exception {
    new App().run("server", "config.yml");
  }

  @Override
  public void run(Configuration configuration, Environment env) {}
}
```

config.yml (note that this also fails for other reporter types, but I'm going with the simplest example)
```
metrics:
  reporters:
    - type: console
      timeZone: UTC
      output: stdout
```

Starting in 0.9.0-rc5 and also in 0.9.0, you get this:
```
Exception in thread "main" javax.validation.UnexpectedTypeException: HV000186: The constraint of type 'javax.validation.constraints.NotNull' defined on 'metrics.reporters[0].frequency' has multiple matching constraint validators which is due to an additional value handler of type 'io.dropwizard.validation.valuehandling.OptionalValidatedValueUnwrapper'. It is unclear which value needs validating. Clarify configuration via @UnwrapValidatedValue.
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getConstraintValidatorInstanceForAutomaticUnwrapping(ConstraintTree.java:266)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getInitializedConstraintValidator(ConstraintTree.java:163)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:116)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:87)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:73)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:592)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:555)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:490)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:454)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:406)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:770)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:656)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:415)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:770)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:656)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:415)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:204)
	at io.dropwizard.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:257)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:149)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:95)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:64)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at testing.App.main(App.java:9)
```

**Comment by achaphiv** [comment]
Ah I see this was fixed in #1308.
