### ISSUE TITLE
MySQL Driver Issue

### ISSUE THREAD

**Issue by ahmed-isam** [dropwizard/dropwizard#1373]
Hi, I am truing to run the dropwizard app and it's failing because it's unable to load the class `com.mysql.jdbc.Driver`

**Error Log**
```
INFO  [2015-12-07 05:27:13,377] org.eclipse.jetty.util.log: Logging initialized @4557ms
INFO  [2015-12-07 05:27:13,924] org.hibernate.Version: HHH000412: Hibernate Core {5.0.2.Final}
INFO  [2015-12-07 05:27:13,928] org.hibernate.cfg.Environment: HHH000206: hibernate.properties not found
INFO  [2015-12-07 05:27:13,932] org.hibernate.cfg.Environment: HHH000021: Bytecode provider name : javassist
INFO  [2015-12-07 05:27:13,954] io.dropwizard.hibernate.SessionFactoryFactory: Entity classes: [org.solarcoin.claimingapi.entities.Claimant, org.solarcoin.claimingapi.entities.Project]
INFO  [2015-12-07 05:27:14,048] org.hibernate.annotations.common.Version: HCANN000001: Hibernate Commons Annotations {5.0.0.Final}
ERROR [2015-12-07 05:27:14,485] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! java.lang.ClassNotFoundException: com.mysql.jdbc.driver
! at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_66]
! at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_66]
! at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_66]
! at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_66]
! at java.lang.Class.forName0(Native Method) ~[na:1.8.0_66]
! at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_66]
! at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38) ~[tomcat-jdbc-8.0.28.jar:na]
! ... 43 common frames omitted
! Causing: java.lang.ClassNotFoundException: Unable to load class: com.mysql.jdbc.driver from ClassLoader:sun.misc.Launcher$AppClassLoader@7e6cbb7a;ClassLoader:sun.misc.Launcher$AppClassLoader@7e6cbb7a
! at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56) ~[tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:268) ~[tomcat-jdbc-8.0.28.jar:na]
! ... 42 common frames omitted
! Causing: java.sql.SQLException: Unable to load class: com.mysql.jdbc.driver from ClassLoader:sun.misc.Launcher$AppClassLoader@7e6cbb7a;ClassLoader:sun.misc.Launcher$AppClassLoader@7e6cbb7a
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:280) ~[tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200) ~[tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708) [tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:642) [tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:464) [tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:141) [tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:115) [tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:102) [tomcat-jdbc-8.0.28.jar:na]
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:126) [tomcat-jdbc-8.0.28.jar:na]
! at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:68) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.build(MetadataBuildingProcess.java:83) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:418) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.boot.internal.MetadataBuilderImpl.build(MetadataBuilderImpl.java:87) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:692) [hibernate-core-5.0.2.Final.jar:5.0.2.Final]
! at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:96) [dropwizard-hibernate-0.9.1.jar:0.9.1]
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:49) [dropwizard-hibernate-0.9.1.jar:0.9.1]
! at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:39) [dropwizard-hibernate-0.9.1.jar:0.9.1]
! at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:56) [dropwizard-hibernate-0.9.1.jar:0.9.1]
! at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:14) [dropwizard-hibernate-0.9.1.jar:0.9.1]
! at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:39) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.9.1.jar:0.9.1]
! at io.dropwizard.Application.run(Application.java:80) [dropwizard-core-0.9.1.jar:0.9.1]
! at org.solarcoin.claimingapi.ClaimingAPIApplication.main(ClaimingAPIApplication.java:59) [classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
! at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144) [idea_rt.jar:na]
WARN  [2015-12-07 05:27:14,496] org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator: HHH000342: Could not obtain connection to query metadata : Unable to load class: com.mysql.jdbc.driver from ClassLoader:sun.misc.Launcher$AppClassLoader@7e6cbb7a;ClassLoader:sun.misc.Launcher$AppClassLoader@7e6cbb7a
INFO  [2015-12-07 05:27:14,528] org.hibernate.dialect.Dialect: HHH000400: Using dialect: org.hibernate.dialect.MySQLDialect
INFO  [2015-12-07 05:27:14,579] org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: HHH000422: Disabling contextual LOB creation as connection was null
```
I am using IntelliJ -not sure if that matters :smile:-

**POM File**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>SolarCoin</groupId>
    <artifactId>ClaimingAPI</artifactId>
    <version>1.0-SNAPSHOT</version>

    <dependencies>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.0.2.Final</version>
        </dependency>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>0.9.1</version>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.14.2</version>
        </dependency>

        <dependency>
            <groupId>com.google.inject</groupId>
            <artifactId>guice</artifactId>
            <version>3.0</version>
        </dependency>

        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.4</version>
        </dependency>

        <dependency>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
            <version>19.0-rc2</version>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.12</version>
        </dependency>

        <dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-hibernate</artifactId>
            <version>0.9.1</version>
        </dependency>

        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>5.1.37</version>
        </dependency>

        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.3</version>
        </dependency>


    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-dependency-plugin</artifactId>
                <executions>
                    <execution>
                        <id>copy-dependencies</id>
                        <phase>package</phase>
                        <goals>
                            <goal>copy-dependencies</goal>
                        </goals>
                        <configuration>
                            <outputDirectory>${project.build.directory}</outputDirectory>
                            <overWriteReleases>false</overWriteReleases>
                            <overWriteSnapshots>true</overWriteSnapshots>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-resources-plugin</artifactId>
                <version>2.7</version>
                <configuration>
                    <outputDirectory/>
                    <encoding>UTF-8</encoding>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```

To be honest, I know this might not be a direct dropwizard problem, rather than my problem working with Maven, but I would still appreciate the help here from dropwizard pros :smile:

**Comment by arteam** [comment]
You would need to shade your dependencies into one jar. See the [Building Fat JARs](http://www.dropwizard.io/0.9.1/docs/getting-started.html#building-fat-jars) section in the manual.
