### ISSUE TITLE
Liquibase works with <include file="" /> but not <includeAll path=""/>

### ISSUE THREAD

**Issue by richmidwinter** [dropwizard/dropwizard#1391]
I'm finding (with 0.9.1) that this fails:

```
<includeAll path="migrations" />
```

Event though this works:

```
<include file="migrations/00001_initial.xml" />
```

This is the stacktrace:

```
Exception in thread "main" liquibase.exception.ChangeLogParseException: liquibase.exception.SetupException: /var/folders/m_/jvmrmqx90n54v276_xvtgxcw0000gn/T/liquibase-unzip5492890813073634394.dir/license/LICENSE.dom-documentation.txt (Not a directory)
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:27)
    at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:225)
    at liquibase.Liquibase.update(Liquibase.java:200)
    at liquibase.Liquibase.update(Liquibase.java:190)
    at liquibase.Liquibase.update(Liquibase.java:186)
    at liquibase.Liquibase.update(Liquibase.java:179)
    at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:68)
    at io.dropwizard.migrations.DbCommand.run(DbCommand.java:52)
    at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:61)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:77)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:80)
    at uk.co.wansdykehouse.pr.PRApplication.main(PRApplication.java:58)
Caused by: liquibase.exception.SetupException: /var/folders/m_/jvmrmqx90n54v276_xvtgxcw0000gn/T/liquibase-unzip5492890813073634394.dir/license/LICENSE.dom-documentation.txt (Not a directory)
    at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:367)
    at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:274)
    at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:221)
    at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:25)
    ... 12 more
Caused by: java.io.FileNotFoundException: /var/folders/m_/jvmrmqx90n54v276_xvtgxcw0000gn/T/liquibase-unzip5492890813073634394.dir/license/LICENSE.dom-documentation.txt (Not a directory)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
    at liquibase.util.FileUtil.unzip(FileUtil.java:76)
    at liquibase.resource.ClassLoaderResourceAccessor.list(ClassLoaderResourceAccessor.java:87)
    at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:344)
    ... 15 more```

**Comment by jplock** [comment]
This seems like an internal liquibase issue instead of with Dropwizard.

**Comment by jelmerterwal** [comment]
I got the same problem and used gradle shadowJar to create my fat jar. The solution for me was to exclude the license dir. Somehow the final jar could not be extracted which was what liquibase tried.

In my build.gradle file..
```
...

plugins {
  id "com.github.johnrengelman.shadow" version "1.2.3"
  ...
}

... 

shadowJar {
    exclude 'META-INF/license/*'
    mergeServiceFiles {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
    }
    relocate 'META-INF/resources/static', 'static'
    manifest {
        attributes 'Main-Class': mainClassName
    }
}
```
