### ISSUE TITLE
dropwizard-client 1.0.0rc1 can't handle multiple Set-Cookie headers

### ISSUE THREAD

**Issue by TheWizz** [dropwizard/dropwizard#1494]
I'm having trouble with the implementation of the DropwizardApacheConnector. Specifically, its use of Collections.singletonList on line 98 of this file 

  https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java

When receiveing a response with multiple cookies, they will all have a Set-Cookie header (with different data). Only the first such header will succeed. Subsequent headers can't be added since the headerValues, as far as I can tell, then always will be a Collections.singletonList, thus causing line 100 to fail since it can't add to such a "singleton" list. This results in headerValues.add causing an UnsupportedOperationException.

In order to move forward, I hacked around the problem for the time being as shown below. Please let me know if I'm totally missing the point here. If not, hopefully this helps helps someone else and shows a possible solution.

```
	for (Header header : apacheResponse.getAllHeaders()) {
		final List<String> headerValues = jerseyResponse.getHeaders().get(header.getName());
		if (headerValues == null) {
			List<String> list = new ArrayList<>(1);
			list.add(header.getValue());
			jerseyResponse.getHeaders().put(header.getName(), list);
		} else {
			headerValues.add(header.getValue());
		}
	}
```
-JM

**Comment by patrox** [comment]
hi @TheWizz - I had similiar issue in the past with headers - but not in Dropwizard.
I've prepared a test which should reflect the behaviour which you've described, can you have a look and confirm if my understanding is correct?

https://gist.github.com/patrox/db5aa7b3f00939dae393

**Comment by patrox** [comment]
the above test will currently fail with `java.lang.UnsupportedOperationException` - as there will be an attempt to add item to a `singletonList` (immutable).

https://github.com/dropwizard/dropwizard/blob/master/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java#L99

Full stacktrace:

```
javax.ws.rs.ProcessingException: java.lang.UnsupportedOperationException
	at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:109)
	at io.dropwizard.client.DropwizardApacheConnectorTest.applyShouldHandleMultipleHeadersWithTheSameKey(DropwizardApacheConnectorTest.java:195)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at com.intellij.junit4.JUnit4TestRunnerUtil$IgnoreIgnoredTestJUnit4ClassRunner.runChild(JUnit4TestRunnerUtil.java:341)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:99)
	... 32 more
```

**Comment by patrox** [comment]
@jplock, @joschi could you please have a look at the issue reported by @TheWizz as this might be a :bug: I can provide a PR with a fix - as after writing a test I'm already warmed up :)

**Comment by arteam** [comment]
Looks like a legitimate bug. I believe commit 0f77240 accidentally introduced it.

@patrox, a fix with a test would be really appreciated. Thanks for tackling this issue!

**Comment by patrox** [comment]
@arteam, @jplock, @joschi could you please have a look at my proposed solution for this ?

https://github.com/dropwizard/dropwizard/pull/1498

Please note, that in test I had to mock a lot of stuff - as I wanted to closely reproduce the issue.

FYI - I have checked all similiar cases from commit mentioned by @arteam (https://github.com/dropwizard/dropwizard/commit/0f7724003eb47051dfda838e7889d2649b25b006) - and seems like this was the only one which could be problematic.

**Comment by TheWizz** [comment]
Thanks, guys, for fixing this one so quickly!
-JM
