### ISSUE TITLE
Running unit test with sqlite3 in memory

### ISSUE THREAD

**Issue by foikila** [dropwizard/dropwizard#1500]
Hello, 

I'm trying to run my unit test with sqlite3 in memory and I encountered a problem with the parsing of the config.yml file... The tests works fine when I'm using a regular url i.e `url: jdbc:sqlite:database.db` but when I'm trying to use a in memory i get this error:
``` 
	at com.google.common.base.Throwables.propagate(Throwables.java:160)
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:214)
	at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:115)
	at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:87)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
Caused by: io.dropwizard.configuration.ConfigurationParsingException: src/main/java/gaas/cb/config/ConfigTest.yml has an error:
  * Malformed YAML at line: 14, column: 27; mapping values are not allowed here
 in 'reader', line 14, column 27:
      url: jdbc:sqlite::memory:
```
The yml file looks like this (minus unrelated stuff..)
```
database:
  driverClass: org.sqlite.JDBC
  url: jdbc:sqlite::memory:
  properties:
    charSet: UTF-8
``` 
According to [this](https://bitbucket.org/xerial/sqlite-jdbc/wiki/Usage) the url should be correct.

Do you guys have any idea what I can do to run the db in memory?

**Comment by joschi** [comment]
@foikila Try putting quotes around your JDBC URL. Unfortunately that string seems to be a valid but incomplete YAML statement.

**Comment by foikila** [comment]
@joschi thank you! Now it seems to work as intended.
This is the result:
```
database:
  driverClass: org.sqlite.JDBC
  url: "jdbc:sqlite::memory:"
  properties:
    charSet: UTF-8
```
