### ISSUE TITLE
NotNull validation of LoggerConfiguration.appenders fails

### ISSUE THREAD

**Issue by rturgut** [dropwizard/dropwizard#1516]
After upgrading to the latest versions (dropwizard ver '1.0.0-rc2'), I am having compilation issues with my app. It looks like a solution proposed/provided in #1308 and #1309 may work here as well.
 
_LoggerConfiguration.appenders_ may need to utilize @UnwrapValidatedValue(false) 

```
javax.validation.UnexpectedTypeException: HV000186: The constraint of type 'javax.validation.constraints.NotNull' defined on 'logging.appenders[0].facility' has multiple matching constraint validators which is due to an additional value handler of type 'io.dropwizard.validation.valuehandling.GuavaOptionalValidatedValueUnwrapper'. It is unclear which value needs validating. Clarify configuration via @UnwrapValidatedValue.
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getConstraintValidatorInstanceForAutomaticUnwrapping(ConstraintTree.java:266)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getInitializedConstraintValidator(ConstraintTree.java:163)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:116)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:87)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:73)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:617)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraint(ValidatorImpl.java:580)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:524)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:492)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:457)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:407)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:795)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:681)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:416)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:795)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:681)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:416)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:205)
	at io.dropwizard.configuration.ConfigurationFactory.validate(ConfigurationFactory.java:260)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:154)
	at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:99)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:115)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:63)
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:194)
	at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:112)
	at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:128)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
```

my config...
```
logging:
  level: INFO
  appenders:
    - type: gelf
      host: log-external.nexgen.myco.biz
      facility: myco.myapp.default
```

**Comment by nickbabcock** [comment]
Update to the latest dropwizard-gelf, as it looks like [it is solved](https://github.com/gini/dropwizard-gelf/commit/9f551be208273104ccfc8412ebd82bfcef64ebc6) for version 0.9.2-1.

Reply back if it is still a problem to continue the issue
