### ISSUE TITLE
Polymorphic Configuration doesn't handle system property overrides for collections if not specified in config file

### ISSUE THREAD

**Issue by bmlining** [dropwizard/dropwizard#1536]
I've run into an issue where system property overrides are not properly handled for Polymorphic Configuration when the configuration value is a collection and a default is not specified in the config file.

For example, with the below configuration both 'strings' and 'integer' can be overridden using '-Ddw.persistence.strings' and '-Ddw.persistence.integer':

```
persistence:
    type: testpersistence
    strings: ['string1', 'string2']
    integer: 2"
```

However, only integer can be overridden using '-Ddw.persistence.integer' with:

```
persistence:
    type: testpersistence
```

Attempting to override 'strings' using '-Ddw.persistence.strings' will result in:

```
io.dropwizard.configuration.ConfigurationParsingException: /var/folders/38/_80f5n7s4hv2llzmyt444d4m0000gn/T/junit3726267359703086845/junit8775153942057281016.tmp has an error:
  * Failed to parse configuration at: persistence.strings; Can not deserialize instance of java.util.HashSet out of VALUE_STRING token
 at [Source: N/A; line: -1, column: -1] (through reference chain: jackson.polymorphic.test.TestDropwizardConfiguration["persistence"]->jackson.polymorphic.test.TestPersistenceServiceConfigurationBuilder["strings"])

    at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:271)
    at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:179)
    at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:95)
    at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:119)
    at jackson.polymorphic.test.DropwizardPolymorphicConfigOverridesTest.dwConfiguration(DropwizardPolymorphicConfigOverridesTest.java:40)
    at jackson.polymorphic.test.DropwizardPolymorphicConfigOverridesTest.testConstructionWithSystemPropertyOverridesNoFileConfigForCollection(DropwizardPolymorphicConfigOverridesTest.java:67)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
    at org.junit.rules.RunRules.evaluate(RunRules.java:20)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.HashSet out of VALUE_STRING token
 at [Source: N/A; line: -1, column: -1] (through reference chain: jackson.polymorphic.test.TestDropwizardConfiguration["persistence"]->jackson.polymorphic.test.TestPersistenceServiceConfigurationBuilder["strings"])
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:857)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:853)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.handleNonArray(StringCollectionDeserializer.java:240)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:171)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:161)
    at com.fasterxml.jackson.databind.deser.std.StringCollectionDeserializer.deserialize(StringCollectionDeserializer.java:19)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:520)
    at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeSetAndReturn(SettableObjectMethodProperty.java:66)
    at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserializeFromObject(BuilderBasedDeserializer.java:300)
    at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:168)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:122)
    at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:93)
    at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:131)
    at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:518)
    at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:95)
    at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:156)
    at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3708)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2005)
    at io.dropwizard.configuration.ConfigurationFactory.build(ConfigurationFactory.java:148)
    ... 29 more
```

 I've included a test for this case, see the attachment 'DropwizardPolymorphicConfigOverridesTest.testConstructionWithSystemPropertyOverridesNoFileConfigForCollection()'.

[dropwizard-polymorphic-config.zip](https://github.com/dropwizard/dropwizard/files/251031/dropwizard-polymorphic-config.zip)

**Comment by bobtiernay-okta** [comment]
I'm also hitting this issue in a non-"polymorphic" context. It seems to be a general issue since the config file is used to derive the schema from the YAML `JsonNode` instance. When it is null, then overlaying the property override fails.

@joschi wonder if you have any thoughts on how we can improve this? On the positive side, I do see this mentioned in the documentation https://www.dropwizard.io/en/stable/manual/core.html#configuration:

> The array override facility only handles configuration elements that are arrays of simple strings. Also, the setting in question **must already exist in your configuration file as an array**; this mechanism will not work if the configuration key being overridden does not exist in your configuration file. If it does not exist or is not an array setting, it will get added as a simple string setting, including the ‘,’ characters as part of the string
