### ISSUE TITLE
Provide a MessageBodyWriter for ValidationErrorMessage

### ISSUE THREAD

**Issue by cowwoc** [dropwizard/dropwizard#1574]
I am getting the following error message:

```
org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyWriter not found for media type=text/html, type=class io.dropwizard.jersey.validation.ValidationErrorMessage, genericType=class io.dropwizard.jersey.validation.ValidationErrorMessage.
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:247) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106) ~[jersey-server-2.22.1.jar:na]
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86) ~[jersey-server-2.22.1.jar:na]
```

Shouldn't Dropwizard provide a `MessageBodyWriter` for this out of the box? Am I missing something?

**Comment by nickbabcock** [comment]
Since you're writing it out as html this is something that you define (if I'm not mistaken). `ValidationErrorMessage` serializes fine as json.

**Comment by cowwoc** [comment]
@nickbabcock I'm actually not trying to write it out as `text/html`. I have no idea why Jersey thinks I am.  That said, you mention that `ValidationErrorMessage` serializes fine as json. Who (which class) provides this serialization?

**Comment by nickbabcock** [comment]
[JacksonMessageBodyProvider](https://github.com/dropwizard/dropwizard/blob/a3379d7de294f82409b1443af87b70e62238bdef/dropwizard-jersey/src/main/java/io/dropwizard/jersey/jackson/JacksonMessageBodyProvider.java)

You shouldn't have to do anything with this to get json serialization :confused: 

Are your endpoints/resources annotated with `@Produces(MediaType.APPLICATION_JSON)`?

**Comment by fredzica** [comment]
I am having the same problem. My endpoint is annotated with @Produces(MediaType.TEXT_HTML) and it validates its parameters (for instance: @Length(min = 8)). When the validation does not pass, I suppose it tries to write Json along with a 400 status code, but as the method is meant to produce HTML output another error occurs and HTTP 500 is returned.

**Comment by jplock** [comment]
@fredzica does `@Produces({MediaType.TEXT_HTML, MediaType.APPLICATION_JSON})` fix the issue?

**Comment by fredzica** [comment]
@jplock Yeah, it does. Thanks.
Using dropwizard 0.9.2 here

**Comment by kanhaiyaagarwal** [comment]
Thanks a lot guys for this thread , i have tried what not to solve this issue,
adding     @Produces(MediaType.APPLICATION_JSON) solves my issue

**Comment by phani50** [comment]
try {
            response = ClientBuilder
                    .newClient(clientConfig)
                    .target(endPoint)
                    .path(ICPS_REST_API_PATH)
                    .request(MediaType.APPLICATION_OCTET_STREAM)
                    .header("x-correlation-id", CoapRequestContext.getCorrelationId())
                    .post(Entity.entity(httpEntity.getContent(), MediaType.APPLICATION_OCTET_STREAM));
            if (response.getStatus() == Status.OK.getStatusCode()) {
                return response.readEntity(StringEntity.class);
            }
            String errorMsg = response.readEntity(String.class);
            throw new IGWException(errorMsg);

        } finally {
            if (response != null) {
                response.close();
            }
        }


I am getting below exception, can any one help me /,

org.glassfish.jersey.message.internal.MessageBodyProviderNotFoundException: MessageBodyReader not found for media type=application/octet-stream, type=class org.apache.http.entity.StringEntity, genericType=class org.apache.http.entity.StringEntity.
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:231)
	at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
	at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:808)
	at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:326)
	at org.glassfish.jersey.client.InboundJaxrsResponse$1.call(InboundJaxrsResponse.java:115)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
	at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
	at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:112)
	at com.nagra.iot.igw.util.IcpsRestClient.post(IcpsRestClient.java:44)

**Comment by jplock** [comment]
instead of `MediaType.APPLICATION_OCTET_STREAM`, are you able to use `MediaType.TEXT_PLAIN` or whatever the equivalent content type is for the `StringEntity.class` you are POST'ing?

**Comment by jplock** [comment]
or try removing those headers and see if it works
