### ISSUE TITLE
Getting Error on entity persistence using hibernate

### ISSUE THREAD

**Issue by bruce-genhot** [dropwizard/dropwizard#1624]
I tried to upgrade my dropwizard from 0.8.2 to 1.0.0-r3, but got below error when persisting an entity by using hibernate 

```
! java.lang.NoSuchMethodError: org.hibernate.event.spi.EventSource.accessTransaction()Lorg/hibernate/Transaction;
! at org.hibernate.envers.internal.synchronization.AuditProcessManager.get(AuditProcessManager.java:34)
! at org.hibernate.envers.event.spi.EnversPostInsertEventListenerImpl.onPostInsert(EnversPostInsertEventListenerImpl.java:36)
! at org.hibernate.action.internal.EntityIdentityInsertAction.postInsert(EntityIdentityInsertAction.java:156)
! at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:102)
! at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:597)
! at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:232)
! at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:213)
! at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:256)
! at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
! at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
! at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
! at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
! at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
! at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
! at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.performSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:97)
! at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.onSaveOrUpdate(DefaultSaveOrUpdateEventListener.java:73)
! at org.hibernate.internal.SessionImpl.fireSaveOrUpdate(SessionImpl.java:651)
! at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:643)
! at org.hibernate.internal.SessionImpl.saveOrUpdate(SessionImpl.java:638)
! at io.dropwizard.hibernate.AbstractDAO.persist(AbstractDAO.java:154)
! at no.trinnvis.dabih.db.AccountDAO.create(AccountDAO.java:26)
! at no.trinnvis.dabih.resources.AccountsResource.createAccount(AccountsResource.java:327)
! at no.trinnvis.dabih.resources.AccountsResource.post(AccountsResource.java:310)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:497)
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$VoidOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:143)
```

**Comment by wind57** [comment]
Why was this closed? I can reproduce it

**Comment by arteam** [comment]
@wind57, Please upgrade your application to Hibernate 5, which is now used in Dropwizard 1.0.0.
