### ISSUE TITLE
Integration Tests with DropwizardTestSupport. HTTP Server not available for tests

### ISSUE THREAD

**Issue by pushkarajc** [dropwizard/dropwizard#1681]
Following instructions on Testing Dropwizard 1.0.0 for Non-JUnit integration tests, I developed tests for a resource using DropwizardTestSupport. The DropwizardTestSupport seems to be booting up the server. I see the whole sequence being printed on the console.  But it doesn't seem to be available for connections. It appears to have stopped right after the startup too. But no exceptions around it. Any ideas? Here is my code and the log.

```java
public class UserResourceTest {

    public static final DropwizardTestSupport<AppConfiguration> SUPPORT =
            new DropwizardTestSupport<AppConfiguration>(AppApplication.class,
                    ResourceHelpers.resourceFilePath("app-integration-testing.yaml"),
                    ConfigOverride.config("server.applicationConnectors[0].port", "0") // Optional, if not using a separate testing-specific configuration file, use a randomly selected port
            );

    @BeforeClass
    public void beforeClass() {
        SUPPORT.before();
    }

    @AfterClass
    public void afterClass() {
        SUPPORT.after();
    }

    @Test
    public void getAllUsers() throws Exception{
        Client client = new JerseyClientBuilder(SUPPORT.getEnvironment()).build("test client");
        Response response = client.target(
                String.format("http://localhost:%d/service/v1/users", SUPPORT.getLocalPort()))
                .request().get();

        log.debug("Response : {}",response);
    }
}

Logs:


**INFO  [2016-08-09 09:41:26,688] o.e.j.s.ServerConnector: Started application@5626d18c{HTTP/1.1}{0.0.0.0:56919}
INFO  [2016-08-09 09:41:26,689] o.e.j.s.ServerConnector: Started admin@45e9b12d{HTTP/1.1}{0.0.0.0:23460}
INFO  [2016-08-09 09:41:26,689] o.e.jetty.server.Server: Started @4307ms
INFO  [2016-08-09 09:41:36,877] o.e.j.s.ServerConnector: Stopped application@5626d18c{HTTP/1.1}{0.0.0.0:0}
INFO  [2016-08-09 09:41:36,878] o.e.j.s.ServerConnector: Stopped admin@45e9b12d{HTTP/1.1}{0.0.0.0:23460}**
INFO  [2016-08-09 09:41:36,880] o.e.j.s.h.ContextHandler: Stopped i.d.j.MutableServletContextHandler@7f0d8eff{/,null,UNAVAILABLE}
INFO  [2016-08-09 09:41:36,883] o.e.j.s.h.ContextHandler: Stopped i.d.j.MutableServletContextHandler@1fe8f5e8{/,null,UNAVAILABLE}
DEBUG [2016-08-09 09:41:36,893] j.management.mbeanserver:  name = org.mongodb.driver:type=ConnectionPool,clusterId=57aa07b414ffad14780ce1b2,host=169.55.89.254,port=27017
DEBUG [2016-08-09 09:41:36,893] j.management.mbeanserver: name = org.mongodb.driver:type=ConnectionPool,clusterId=57aa07b414ffad14780ce1b2,host=169.55.89.254,port=27017
DEBUG [2016-08-09 09:41:36,893] j.management.mbeanserver: name = org.mongodb.driver:type=ConnectionPool,clusterId=57aa07b414ffad14780ce1b2,host=169.55.89.254,port=27017
DEBUG [2016-08-09 09:41:36,893] j.management.mbeanserver: Send delete notification of object org.mongodb.driver:clusterId=57aa07b414ffad14780ce1b2,host=169.55.89.254,port=27017,type=ConnectionPool
DEBUG [2016-08-09 09:41:36,893] j.management.mbeanserver: JMX.mbean.unregistered org.mongodb.driver:type=ConnectionPool,clusterId=57aa07b414ffad14780ce1b2,host=169.55.89.254,port=27017
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.389 sec <<< FAILURE!
getAllUsers(com.v1.api.resources.UserResourceTest)  Time elapsed: 10.179 sec  <<< FAILURE!
**javax.ws.rs.ProcessingException: org.apache.http.NoHttpResponseException: localhost:56919 failed to respond**
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:109)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at com.v1.api.resources.UserResourceTest.getAllUsers(UserResourceTest.java:47)
Caused by: org.apache.http.NoHttpResponseException: localhost:56919 failed to respond
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:143)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:57)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:261)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:165)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:167)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:272)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
        at com.codahale.metrics.httpclient.InstrumentedHttpRequestExecutor.execute(InstrumentedHttpRequestExecutor.java:44)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:271)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
        at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:87)
        ... 45 more


```

**Comment by evnm** [comment]
Judging by the `ServerConnector` logging, the Jetty server is started up and then immediately shut down before the tests actually run.

What is the contents of `app-integration-testing.yaml`?

**Comment by nickbabcock** [comment]
@pushkarajc, I'm optimistically assuming the non-response means the issue has been figured out. If your issue persists, please provide more information for diagnosis.
