### ISSUE TITLE
MethodNotFound in Jetty-Server

### ISSUE THREAD

**Issue by fzakaria** [dropwizard/dropwizard#1720]
I am using Dropwizard 1.0 and it looks like the versions listed in the bom are not correct.

Here is the code from 

```
        if (!isAsyncSupported()) {
            baseRequest.setAsyncSupported(false, null);
        }
        try {
            servlet.service(request, response);
        } finally {
            baseRequest.setAsyncSupported(asyncSupported, null);
        }
```

The problem is that the BOM for dropwizard **1.0** is using jetty-server [9.3.9.v20160517](https://mvnrepository.com/artifact/io.dropwizard/dropwizard-bom/1.0.0)

That version of jetty-server does not have the methods they are trying to use does not have it.

Here is a sample exception

```
WARN  2016-09-04 04:06:40,677 /0F77FF7D77F74C01A6CFECF56436EDAF/169AD10DA09C44B29805D51A49F1A705 [dw-41] org.eclipse.jetty.servlet.ServletHandler: Error for /lookup/test
java.lang.NoSuchMethodError: org.eclipse.jetty.server.Request.setAsyncSupported(ZLjava/lang/String;)V
	at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:51)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1685)
	at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
```

**Comment by nickbabcock** [comment]
[Should be there](https://github.com/eclipse/jetty.project/blob/0bbebec1e0981eaca2d2110f8322e4a953b1b066/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java#L1870-L1873), check for incompatible versions of Jetty using `mvn dependency:tree`

**Comment by fzakaria** [comment]
hmm..
This is what I"m seeing.

Doesn't that mean the dependency is pulled in from `dropwizard-jetty` ?

```
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:1.0.0:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.23.1:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.23.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:3.1.2:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.7.6:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.7.6:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.7.6:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.23.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.3.6.v20151106:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.3.6.v20151106:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.3.6.v20151106:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.3.6.v20151106:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.3.6.v20151106:compile
```
https://github.com/eclipse/jetty.project/blob/d737e1c638653988ce7d8e5bfb89859347e1c306/jetty-server/src/main/java/org/eclipse/jetty/server/Request.java

**Comment by fzakaria** [comment]
Ugh it was a dependencyManagement in my root pom causing the confusion.
Closing.
