### ISSUE TITLE
IncompatibleClassChangeError: LoggerContext does not implement org.slf4j.ILoggerFactory

### ISSUE THREAD

**Issue by sidwagle** [dropwizard/dropwizard#1724]
Porting my application to use dropwizard for jetty / jersey and the likes. Cannot get the server to start. I have made sure only slfj jars and logback on the classpath are the dropwizard dependencies.

Dropwizard Version : 1.0.0

Exception trace:
`java.lang.IncompatibleClassChangeError: Class ch.qos.logback.classic.LoggerContext does not implement the requested interface org.slf4j.ILoggerFactory
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
    at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
    at io.dropwizard.jackson.DiscoverableSubtypeResolver.<clinit>(DiscoverableSubtypeResolver.java:24)
    at io.dropwizard.jackson.Jackson.configure(Jackson.java:61)
    at io.dropwizard.jackson.Jackson.newObjectMapper(Jackson.java:23)
    at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64)
    at io.dropwizard.Application.run(Application.java:72)
    at org.apache.ambari.metrics.server.MetricsServerApplication.main(MetricsServerApplication.java:29)`

Attaching my dependency tree for reference.
[dep-tree.txt](https://github.com/dropwizard/dropwizard/files/462867/dep-tree.txt)

**Comment by arteam** [comment]
Thanks for reporting! 

The only cause for this issue I can think of is existence of several versions of slf4j in the classpath.
But in your dependency tree I see only version `1.7.21`. Could you try to create a shaded JAR and see if there are any warnings during building the JAR?

**Comment by nickbabcock** [comment]
@sidwagle, is this still an issue?

**Comment by sidwagle** [comment]
Hi Nick,

Yes I never got past this issue, have it on the shelf at the moment will
revisit this in a couple of days to see if I get anywhere.

I used the Dep tree visualization of Intellij and made sure all the
slf4j-api version are excluded except the one needed by dropwizard but I
still get the same error message. I am building a shaded jar.

Thanks,
Sid

**Comment by nickbabcock** [comment]
Can you post a minimally reproducible project (gist/repo/pom/etc)?

**Comment by nickbabcock** [comment]
Closing for lack of response.
