### ISSUE TITLE
Defining Hibernate @TypeDefs at the package level (package-info.java)

### ISSUE THREAD

**Issue by dotCipher** [dropwizard/dropwizard#1785]
I ended up extending the [SessionFactoryFactory](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/SessionFactoryFactory.java) from `dropwizard-hibernate` in my project in order to attach a custom `NamingStrategyDelegator` with custom naming strategies.  When I set the `@TypeDefs`block within the same package as my entities I get errors on startup when referring to the types by name in my entities.

Example in my `package-info.java`:

```
@TypeDefs({
        @TypeDef(name = "UUID",
                defaultForType = UUID.class,
                typeClass = org.hibernate.type.PostgresUUIDType.class
})
```

Within an `@Entity` class:

```
    @Id
    @Column(nullable = false, unique = true, updatable = false)
    private UUID hash;
```

Error:

```
org.hibernate.MappingException: Could not determine type for: UUID
    at org.hibernate.cfg.annotations.SimpleValueBinder.fillSimpleValue(SimpleValueBinder.java:519)
    at org.hibernate.cfg.SetSimpleValueTypeSecondPass.doSecondPass(SetSimpleValueTypeSecondPass.java:42)
    at org.hibernate.cfg.Configuration.processSecondPassesOfType(Configuration.java:1472)
    at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1420)
    at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1846)
        at my.custom.project.bundles.hibernate.MyProjectSessionFactoryFactory.buildSessionFactory(MyProjectSessionFactoryFactory.java:106)
```

I could attach all annotations to the classes for the `@TypeDefs` but I would prefer to have them at the package level.  How should I be going about this?

**Comment by rohitcelestial** [comment]
@dotCipher How did you resolve this?

**Comment by dotCipher** [comment]
Apologies but this issue is a bit old. I honestly don't recall what I did here for resolving it

**Comment by joschi** [comment]
@rohitcelestial Maybe you could open a new issue and provide a minimal example to reproduce the issue?
