### ISSUE TITLE
Java 8 LocalDate QueryParam

### ISSUE THREAD

**Issue by OverlyExcessive** [dropwizard/dropwizard#1786]
It seems that parsing of Java 8 `LocalDate` as QueryParam is not liked. I get the following error on startup when trying with a simple controller.

```java
    @GET
    public Integer testRatas(@QueryParam("foo") final LocalDate foo) {
        return 1;
    }
```

```
Caused by: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialisation.
[[FATAL] No injection source found for a parameter of type public java.lang.Integer resources.ForexRatesResource.testRatas(java.time.LocalDate) at index 0.; source='ResourceMethod{httpMethod=GET, consumedTypes=[], producedTypes=
[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class 
resources.ForexRatesResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@517a2b0]}, definitionMethod=public 
java.lang.Integer resources.ForexRatesResource.testRatas(java.time.LocalDate), parameters=
[Parameter [type=class java.time.LocalDate, source=foo, defaultValue=null]], responseType=cla
ss java.lang.Integer}, nameBindings=[]}']
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:555)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184)
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350)
	at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:640)
	... 46 more
```

**Comment by joschi** [comment]
@OverlyExcessive Which version of Dropwizard are you using?

**Comment by OverlyExcessive** [comment]
@joschi 1.0.2

**Comment by OverlyExcessive** [comment]
**Minimal steps to reproduce:**

Using `dropwizard/example` project add the following lines in `src/main/java/com.example.helloworld/resources/HelloWordResource.java`:

```java
    @GET
    @Path("/localdate")
    @Produces(MediaType.TEXT_PLAIN)
    public String receiveLocalDate(@QueryParam("localDate")Optional<LocalDate> localDateParam) {
        if (localDateParam.isPresent()) {
            final LocalDate actualDateTimeParam = localDateParam.get();
            LOGGER.info("Received a date: {}", actualDateTimeParam);
            return actualDateTimeParam.toString();
        } else {
            LOGGER.warn("No received date");
            return null;
        }
    }
```

Run `mvn package`, build fails during integration tests.

**Comment by joschi** [comment]
@OverlyExcessive Try using `LocalDateParam`:
```java
    @GET
    @Path("/date")
    @Produces(MediaType.TEXT_PLAIN)
    public String receiveDate(@QueryParam("date") Optional<LocalDateParam> dateTimeParam) {
        if (dateTimeParam.isPresent()) {
            final LocalDateParam actualDateTimeParam = dateTimeParam.get();
            LOGGER.info("Received a date: {}", actualDateTimeParam);
            return actualDateTimeParam.get().toString();
        } else {
            LOGGER.warn("No received date");
            return null;
        }
    }
```

**Comment by OverlyExcessive** [comment]
@joschi 
Seems that worked, thanks!

**Comment by karolmie1** [comment]
@OverlyExcessive That was a great question. In fact It would fit nicely on stackoverflow. I would upvote that.

**Comment by chrisco484** [comment]
It seems like you can provide a Parameter Converter implementation to allow direct support of LocalDate as described here:

[](https://blog.sebastian-daschner.com/entries/jaxrs-convert-params)
