### ISSUE TITLE
@Context variables don't get injected when testing resources

### ISSUE THREAD

**Issue by yateam** [dropwizard/dropwizard#1933]
Hello,

I am writing a test for one of my resources. It uses a @Context variable (UriInfo uriInfo). Following the documentation I used `GrizzlyWebTestContainerFactory` in order to make @Context injections work. However, I still get an error: Not inside a request scope.

My resource:
```
import io.swagger.annotations.Api;

import javax.annotation.security.PermitAll;
import javax.inject.Inject;
import javax.validation.constraints.NotNull;
import javax.ws.rs.*;
import javax.ws.rs.core.*;
import java.util.Optional;

@Produces(MediaType.APPLICATION_JSON)
@Api(value = "Sessions")
public class SessionResource {
  private final IUserService userService;

  @Context
  private UriInfo uriInfo;

  @Inject
  public SessionResource(IUserService userService) {
    this.userService = userService;
  }

  @POST
  @Consumes(MediaType.APPLICATION_FORM_URLENCODED)
  public Response logIn(@NotNull @FormParam("email") String email, @NotNull @FormParam("password") String password) {
    return Response.status(Response.Status.UNAUTHORIZED).build();
  }

}
```

Code snippet from the test:
```
@Rule
  public final ResourceTestRule RESOURCES = ResourceTestRule.builder()
          .setTestContainerFactory(new GrizzlyWebTestContainerFactory())
          .addResource(new SessionResource(userService))
          .build();
```

The exception I get:
```
ERROR [2017-02-20 17:22:19,992] org.glassfish.grizzly.servlet.ServletHandler: service exception:
! java.lang.IllegalStateException: Not inside a request scope.
! at jersey.repackaged.com.google.common.base.Preconditions.checkState(Preconditions.java:173)
! at org.glassfish.jersey.process.internal.RequestScope.current(RequestScope.java:233)
! at org.glassfish.jersey.process.internal.RequestScope.findOrCreate(RequestScope.java:158)
! at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2020)
! ... 28 common frames omitted
! Causing: org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
! 1. java.lang.IllegalStateException: Not inside a request scope.
! 
! at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2026)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:766)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.getUnqualifiedService(ServiceLocatorImpl.java:773)
! at org.jvnet.hk2.internal.IterableProviderImpl.get(IterableProviderImpl.java:111)
! at org.glassfish.jersey.server.internal.inject.AbstractContainerRequestValueFactory.getContainerRequest(AbstractContainerRequestValueFactory.java:71)
! at org.glassfish.jersey.server.internal.inject.PathParamValueFactoryProvider$PathParamValueFactory.provide(PathParamValueFactoryProvider.java:93)
! at org.glassfish.jersey.server.internal.inject.ParamInjectionResolver.resolve(ParamInjectionResolver.java:134)
! at org.jvnet.hk2.internal.Utilities.justInject(Utilities.java:941)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:980)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.inject(ServiceLocatorImpl.java:970)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:617)
! at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:184)
! at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:350)
! at org.glassfish.jersey.server.ApplicationHandler$3.call(ApplicationHandler.java:347)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:255)
! at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:347)
! at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
! at javax.servlet.GenericServlet.init(GenericServlet.java:244)
! at org.glassfish.grizzly.servlet.ServletHandler.loadServlet(ServletHandler.java:342)
! at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:204)
! at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:173)
! at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
! at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591)
! at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571)
! at java.lang.Thread.run(Thread.java:745)
```

Am I missing something?

**Comment by yateam** [comment]
Turned out that the problem is with @PathParam in a parent resource - test framework seems not be able to inject it. I guess, you may close the issue.
