### ISSUE TITLE
UnitOfWorkAwareProxyFactory not creating transaction

### ISSUE THREAD

**Issue by ramsrib** [dropwizard/dropwizard#1945]
I'm trying to use `UnitOfWorkAwareProxyFactory` along with PasswordAuthenticator for AuthFilter.  But it's not working as expected, it seems like UnitOfWorkAwareProxyFactory is not creating hibernate session.

I'm using `1.1.0-rc1` version of dropwizard.

This is my code:
```
final UserDAO userDAO = new UserDAO(hibernate.getSessionFactory());

PasswordAuthenticator passwordAuthenticator = new UnitOfWorkAwareProxyFactory(hibernate)
                .create(PasswordAuthenticator.class, UserDAO.class, userDAO);

environment.jersey().register(new AuthDynamicFeature(new BasicCredentialAuthFilter.Builder<UserPrincipal>()
                .setAuthenticator(passwordAuthenticator)
                .setAuthorizer(new PasswordAuthorizer())
                .setPrefix("Basic")
                .buildAuthFilter()));
```
I'm getting this exception, 

```
ERROR [2017-03-01 05:01:11,844] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: cb8b3bead28c905a
! org.hibernate.HibernateException: No session currently bound to execution context
! at org.hibernate.context.internal.ManagedSessionContext.currentSession(ManagedSessionContext.java:58)
! at org.hibernate.internal.SessionFactoryImpl.getCurrentSession(SessionFactoryImpl.java:456)
! at io.dropwizard.hibernate.AbstractDAO.currentSession(AbstractDAO.java:44)
! at io.dropwizard.hibernate.AbstractDAO.namedQuery(AbstractDAO.java:65)
! at com.inventorbit.startomatic.db.UserDAO.findByUsernameAndPassword(UserDAO.java:19)
! at com.inventorbit.startomatic.auth.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:25)
! at com.inventorbit.startomatic.auth.PasswordAuthenticator_$$_jvst2cb_6._d0authenticate(PasswordAuthenticator_$$_jvst2cb_6.java)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at io.dropwizard.hibernate.UnitOfWorkAwareProxyFactory.lambda$create$0(UnitOfWorkAwareProxyFactory.java:81)
! at com.inventorbit.startomatic.auth.PasswordAuthenticator_$$_jvst2cb_6.authenticate(PasswordAuthenticator_$$_jvst2cb_6.java)
! at com.inventorbit.startomatic.auth.PasswordAuthenticator.authenticate(PasswordAuthenticator.java:15)
! at io.dropwizard.auth.AuthFilter.authenticate(AuthFilter.java:136)
! at io.dropwizard.auth.basic.BasicCredentialAuthFilter.filter(BasicCredentialAuthFilter.java:28)
! at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
! at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
! at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
```

**Comment by arteam** [comment]
Did you add the `@UnitOfWork` annotation on the `PasswordAuthenticator#authenticate` method? Judging by the stack trace you provided, `UnitOfWorkAwareProxyFactory` intercepted the call to `PasswordAuthenticator.authenticate`, but for a Hibernate session was not opened.

**Comment by ramsrib** [comment]
You are right!, I missed to annotate with @UnitWork. 

Thanks a lot for quick response.
