### ISSUE TITLE
DropwizardConfiguredValidator wrongly calls an annotated Resource method

### ISSUE THREAD

**Issue by victornoel** [dropwizard/dropwizard#1953]
Hi,

I have a resource with the following defined in it:
```
    @GET
    @Produces(MediaType.APPLICATION_JSON + ";qs=1")
    @Valid
    public WorkspaceFullContent get() {
        ...
    }
```

And I don't know why, when a request arrives for another annotated method of this resource, DropwizardConfiguredValidator decides to call `get()`!

Important points:
 - If I rename it with anything that does not start with `get` everything is fine.
 - If I remove the `@Valid` annotation, then it works.

I suppose there is something in JAX-RS about validating a resource before executing one of its method, but I'm not sure it is expected that JAX-RS annotated should be considered as getters on the resource…

An exception (caused by my code in the `get()` resource method) is following, so that you can see where this happens exactly:
```
WARN  [2017-03-09 12:05:48,749] org.glassfish.jersey.server.validation.internal.ValidationExceptionMapper: Unexpected Bean Validation problem.
! javax.ws.rs.WebApplicationException: HTTP 403 Forbidden
! at org.ow2.petals.cockpit.server.resources.WorkspaceResource.checkAccess(WorkspaceResource.java:100)
! at org.ow2.petals.cockpit.server.resources.WorkspaceResource.lambda$0(WorkspaceResource.java:110)
! at org.jooq.impl.DefaultDSLContext.lambda$transactionResult0$0(DefaultDSLContext.java:468)
! at org.jooq.impl.Tools$10$1.block(Tools.java:3291)
! at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
! at org.jooq.impl.Tools$10.get(Tools.java:3288)
! at org.jooq.impl.DefaultDSLContext.transactionResult0(DefaultDSLContext.java:505)
! at org.jooq.impl.DefaultDSLContext.transactionResult(DefaultDSLContext.java:438)
! at org.ow2.petals.cockpit.server.resources.WorkspaceResource.get(WorkspaceResource.java:108)
! ... 40 common frames omitted
! Causing: java.lang.reflect.InvocationTargetException: null
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.hibernate.validator.internal.util.ReflectionHelper.getValue(ReflectionHelper.java:245)
! ... 35 common frames omitted
! Causing: javax.validation.ValidationException: HV000090: Unable to access get.
! at org.hibernate.validator.internal.util.ReflectionHelper.getValue(ReflectionHelper.java:251)
! at org.hibernate.validator.internal.engine.ValidatorImpl.getValue(ValidatorImpl.java:1714)
! at org.hibernate.validator.internal.engine.ValidatorImpl.getValue(ValidatorImpl.java:1685)
! at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:647)
! at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:416)
! at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:205)
! at io.dropwizard.jersey.validation.DropwizardConfiguredValidator.validate(DropwizardConfiguredValidator.java:112)
! at io.dropwizard.jersey.validation.DropwizardConfiguredValidator.validateResourceAndInputParams(DropwizardConfiguredValidator.java:42)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:134)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at org.glassfish.grizzly.servlet.FilterChainImpl.doFilter(FilterChainImpl.java:147)
! at org.glassfish.grizzly.servlet.FilterChainImpl.invokeFilterChain(FilterChainImpl.java:106)
! at org.glassfish.grizzly.servlet.ServletHandler.doServletService(ServletHandler.java:224)
! at org.glassfish.grizzly.servlet.ServletHandler.service(ServletHandler.java:173)
! at org.glassfish.grizzly.http.server.HttpHandler$1.run(HttpHandler.java:224)
! at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:593)
! at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:573)
! at java.lang.Thread.run(Thread.java:745)
```

**Comment by joschi** [comment]
@victornoel Please upgrade to Dropwizard 1.1.0-rc.2 and check if it solves your problem.

**Comment by victornoel** [comment]
@joschi good call, it works with this version :)
I close the issue then!

**Comment by victornoel** [comment]
Whoups no, I made a mistake when I tested and it does NOT work with 1.1.0-rc2 :)

**Comment by joschi** [comment]
@victornoel I think the problem is that Hibernate Validator (or rather javax.validation) expects the classes to follow the JavaBean conventions and a method of `get()` would lead to the expectation of a field named `<null>` (i. e. Hibernate Validator fails to find the correctly named field).

As a workaround, use another name than `get()` for your `@GET` methods. 😉
