### ISSUE TITLE
LoggingExceptionMapper OutOfMemoryError

### ISSUE THREAD

**Issue by charbonnier666** [dropwizard/dropwizard#1955]
Hi guys, I make a big upload with dropwizard REST and I have this error everytime (or in this class: AsyncAppender-Worker-async-console-append)
Uploading and writing to DB works fine
Have you some idea ? maybe some logback configuration ?

```TRACE [2017-03-10 13:27:24,070] org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl: ResourceLocalTransactionCoordinatorImpl#afterCompletionCallback(false)
TRACE [2017-03-10 13:27:24,070] org.hibernate.resource.transaction.internal.SynchronizationRegistryStandardImpl: SynchronizationRegistryStandardImpl.notifySynchronizationsAfterTransactionCompletion(5)
TRACE [2017-03-10 13:27:24,070] org.hibernate.internal.SessionImpl: SessionImpl#afterTransactionCompletion(successful=false, delayed=false)
TRACE [2017-03-10 13:27:24,070] org.hibernate.internal.SessionImpl: Closing session
INFO  [2017-03-10 13:27:24,071] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    91355 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    27546730 nanoseconds spent preparing 1 JDBC statements;
    23695309332 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}
TRACE [2017-03-10 13:27:24,071] org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl: Closing JDBC container [org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl@6bb96c0e]
TRACE [2017-03-10 13:27:24,071] org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl: Releasing JDBC resources
TRACE [2017-03-10 13:27:24,071] org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl: Closing logical connection
TRACE [2017-03-10 13:27:24,071] org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl: Releasing JDBC resources
TRACE [2017-03-10 13:27:24,071] org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl: Logical connection closed
ERROR [2017-03-10 13:27:24,353] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: b578481362f72137
! java.lang.OutOfMemoryError: Java heap space
! at java.util.Arrays.copyOf(Arrays.java:3332)
! at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
! at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
! at java.lang.StringBuilder.append(StringBuilder.java:136)
! at com.mysql.jdbc.PreparedStatement.asSql(PreparedStatement.java:936)
! at com.mysql.jdbc.PreparedStatement.asSql(PreparedStatement.java:919)
! at com.mysql.jdbc.PreparedStatement.toString(PreparedStatement.java:4602)
! at java.util.Formatter$FormatSpecifier.printString(Formatter.java:2886)
! at java.util.Formatter$FormatSpecifier.print(Formatter.java:2763)
! at java.util.Formatter.format(Formatter.java:2520)
! at java.util.Formatter.format(Formatter.java:2455)
! at java.lang.String.format(String.java:2940)
! at org.jboss.logging.Slf4jLocationAwareLogger.doLogf(Slf4jLocationAwareLogger.java:81)
! at org.jboss.logging.Logger.logf(Logger.java:2398)
! at org.jboss.logging.DelegatingBasicLogger.tracef(DelegatingBasicLogger.java:124)
! at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.close(ResourceRegistryStandardImpl.java:148)
! at org.hibernate.resource.jdbc.internal.ResourceRegistryStandardImpl.release(ResourceRegistryStandardImpl.java:82)
! at org.hibernate.id.insert.AbstractReturningDelegate.releaseStatement(AbstractReturningDelegate.java:67)
! at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:45)
! at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:2827)
! at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3398)
! at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:81)
! at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:597)
! at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:232)
! at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:213)
! at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:256)
! at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:318)
! at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:275)
! at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:182)
! at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:113)
! at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.saveWithGeneratedOrRequestedId(DefaultSaveOrUpdateEventListener.java:192)
! at org.hibernate.event.internal.DefaultSaveOrUpdateEventListener.entityIsTransient(DefaultSaveOrUpdateEventListener.java:177)
0:0:0:0:0:0:0:1 - - [10/mar/2017:13:27:24 +0000] "POST /client/upload/app/111 HTTP/1.1" 500 110 "http://localhost:3000/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36" 159065
```

**Comment by arteam** [comment]
What the size of the uploaded file? Judging by the stack trace, you don't have enough heap space in your application to allocate the whole file as an SQL statement. You can try to increase the allocated memory with the -Xms and -Xmx parameters during start-up. If the file is really big, you may consider to store it off heap.

**Comment by charbonnier666** [comment]
@arteam about 40MB (byte array in blob), it's writing correct on db but after closing connection it seems to write some log about file... don't you think so?

**Comment by arteam** [comment]
Ah, I see, my mistake. I guess you can try to disable Hibernate SQL logging in your config:
```
logging:
  loggers:
    org.hibernate.SQL:
      level: OFF
```

**Comment by arteam** [comment]
Or the whole Hibernate logging with `org.hibernate`, because I see that TRACE logging statements are logged as well.

**Comment by charbonnier666** [comment]
@arteam Yes 👍  If I disable hibernate trace it doesn't appears anymore
