### ISSUE TITLE
Commands and customizable exception handling

### ISSUE THREAD

**Issue by nickbabcock** [dropwizard/dropwizard#2122]
With 1.2.0-rc1 out I tried rolling out to all my apps in testing, but I hit a snag:

#2003 introduced printing the stack trace on an exception which is good for the `server` command but the wrong call for `check` and other commands.

Let's look at the differences between v1.1.3 and v1.2.0-rc1 with dropwizard-example by `check banner.txt`

v1.1.3

```
classes\banner.txt has an error:
  * Failed to parse configuration; Can not construct instance of com.example.helloworld.HelloWorldConfiguration: no String-argument constructor/factory method to deserialize from String value ('web-scale hello world dP for the web 88 .d8888b. dP.  .dP .d8888b. 88d8b.d8b. 88d888b. 88 .d8888b. 88ooood8  `8bd8'  88'  `88 88'`88'`88 88'  `88 88 88ooood8 88.  ...  .d88b.  88.  .88 88  88  88 88.  .88 88 88.  ... `88888P' dP'  `dP `88888P8 dP  dP  dP 88Y888P' dP `88888P' 88 dP')
 at [Source: N/A; line: -1, column: -1]
```

v1.2.0

```
io.dropwizard.configuration.ConfigurationParsingException: classes\banner.txt has an error:
  * Failed to parse configuration; Cannot construct instance of `com.example.helloworld.HelloWorldConfiguration` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('web-scale hello world dP for the web 88 .d8888b. dP.  .dP .d8888b. 88d8b.d8b. 88d888b. 88 .d8888b. 88ooood8  `8bd8'  88'  `88 88'`88'`88 88'  `88 88 88ooood8 88.  ...  .d88b.  88.  .88 88  88  88 88.  .88 88 88.  ... `88888P' dP'  `dP `88888P8 dP  dP  dP 88Y888P' dP `88888P' 88 dP')
 at [Source: UNKNOWN; line: -1, column: -1]

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:276)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:157)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:92)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:124)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
        at io.dropwizard.cli.Cli.run(Cli.java:74)
        at io.dropwizard.Application.run(Application.java:93)
        at com.example.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:38)
Caused by: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `com.example.helloworld.HelloWorldConfiguration` (although at least one Creator exists): no String-argument constructor/factory method to deserialize from String value ('web-scale hello world dP for the web 88 .d8888b. dP.  .dP .d8888b. 88d8b.d8b. 88d888b. 88 .d8888b. 88ooood8  `8bd8'  88'  `88 88'`88'`88 88'  `88 88 88ooood8 88.  ...  .d88b.  88.  .88 88  88  88 88.  .88 88 88.  ... `88888P' dP'  `dP `88888P8 dP  dP  dP 88Y888P' dP `88888P' 88 dP')
 at [Source: UNKNOWN; line: -1, column: -1]
        at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:63)
        at com.fasterxml.jackson.databind.DeserializationContext.reportInputMismatch(DeserializationContext.java:1329)
        at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1031)
        at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:370)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:314)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:170)
        at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:120)
        at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3972)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:128)
        ... 6 more
```
The stack trace is unneeded for `check` and only adds confusion. Similarly, I have custom commands where the stack trace greatly distracts from the output and I won't be able to upgrade from v1.1 until the same behavior is kept.

Off the top of my head:

- a `Command` needs to signal that it failed (I'm ok with exception ✔️)
- `Cli#run` can provide a sane default for what to do with an exception (like printing stack trace) but this must be overridable
- `onFatalError` is too weak in it's current state to be used for this (it lacks the exception, for instance, if an exception even caused `onFatalError` to be triggered)

**Comment by arteam** [comment]
Closed  by #2133
