### ISSUE TITLE
Faile to handled verbose Accept-Language header

### ISSUE THREAD

**Issue by Ezcred** [dropwizard/dropwizard#2131]
Hello Drop-wizards,

As per accept language header guidelines:
1. https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
2. https://tools.ietf.org/html/rfc7231#section-5.3.5

Drop wizard is failed to handle below header
`Accept-Language: en_in,en-IN;q=0.8,en-US;q=0.6
`
Tested on below versions of drop wizard:
a) 1.1.3
b) v1.2.0-rc1

Please close/ mark duplicate is this is already know or taken care of.

Exception thrown:

```
! javax.ws.rs.WebApplicationException: Unable to parse "Accept-Language" header value: "en-US;q=0.6;en_in,en-IN;q=0.5"
! at io.dropwizard.views.ViewMessageBodyWriter.detectLocale(ViewMessageBodyWriter.java:91)
! at io.dropwizard.views.ViewMessageBodyWriter.writeTo(ViewMessageBodyWriter.java:73)
! at io.dropwizard.views.ViewMessageBodyWriter.writeTo(ViewMessageBodyWriter.java:27)
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265)
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250)
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
! at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106)
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
! at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86)
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162)
! at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1130)
! at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:711)
! at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:434)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:329)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
```

**Comment by lutzhorn** [comment]
Looks like this is related to https://github.com/dropwizard/dropwizard/issues/2097 and https://github.com/dropwizard/dropwizard/pull/2103.

**Comment by lutzhorn** [comment]
I think your header value is not valid. The underscore `_` in `en_in` seems not to comply with [the RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.4).

    language-range  = ( ( 1*8ALPHA *( "-" 1*8ALPHA ) ) | "*" )

There is a dash `-`, not an underscore `_`.

**Comment by Ezcred** [comment]
Got it. Let me check who is sending that.
