### ISSUE TITLE
Issue with allowed methods in 1.2.0

### ISSUE THREAD

**Issue by yash9patel** [dropwizard/dropwizard#2174]
While setting yaml file with 
allowedMethods: [GET, POST, PUT, DELETE, HEAD, OPTIONS, PATCH]
I still get issue java.lang.NoSuchFieldError: DEFAULT_ALLOWED_METHODS
I tried with empty [], ["GET"] and "GET" but still get the same error. I am using java 1.9 with dropwizard 1.2.0. When I switch it to 1.0.0, issue goes away.
```

java.lang.NoSuchFieldError: DEFAULT_ALLOWED_METHODS
	at io.dropwizard.server.AbstractServerFactory.<init>(AbstractServerFactory.java:261)
	at io.dropwizard.server.DefaultServerFactory.<init>(DefaultServerFactory.java:70)
	at io.dropwizard.Configuration.<init>(Configuration.java:63)
	at com.java.SampleServiceConfiguration.<init>(SampleServiceConfiguration.java:6)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at java.base/java.lang.Class.newInstance(Class.java:558)
	at io.dropwizard.configuration.YamlConfigurationFactory.build(YamlConfigurationFactory.java:105)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:93)
	at com.java.SampleApplication.main(SampleServiceApplication.java:11)
```

**Comment by joschi** [comment]
Have you tried using Java 8?
Are you 100% sure that all dependencies are from Dropwizard 1.2.0?
What's the complete code of your Dropwizard application?

**Comment by arteam** [comment]
Please check that your project pulls `dropwizard-jersey` with the 1.2.0 version. The type of the `AllowedMethodsFilter.DEFAULT_ALLOWED_METHODS` field was changed from `Set` to `ImmutableSet` between 1.1 to 1.2. Judging by the stack trace, you probably have an old version of `AllowedMethodsFilter` in the classpath.

**Comment by yash9patel** [comment]
You guys were right I did have conflicts in my pom file and it is resolved. Sometimes you need someone to check for basics again.
