### ISSUE TITLE
drop-wizard 3.2.3 jars support for IBM JDK 1.6 

### ISSUE THREAD

**Issue by Bhavanish1** [dropwizard/dropwizard#2183]
Team,

**We need drop-wizard 3.2.3 jars support for IBM JDK 1.6** 

Metrics-servlets-3.2.3 is having one transitive dependency profiler-1.0.2 
We also do not see any mention of support for JDK 1.6. Can we get the built in version for IBM JDK 1.6

 Caused by: com.ibm.ws.webcontainer.exception.WebAppNotLoadedException: Failed to load webapp: JVMCFRE003 bad major version&#59; class=com/papertrail/profiler/jaxrs/CpuProfileResource, offset=6
        at com.ibm.ws.webcontainer.VirtualHostImpl.addWebApplication(VirtualHostImpl.java:176)
        at com.ibm.ws.webcontainer.WSWebContainer.addWebApp(WSWebContainer.java:749)
        ... 20 more
Caused by: java.lang.UnsupportedClassVersionError: JVMCFRE003 bad major version; class=com/papertrail/profiler/jaxrs/CpuProfileResource, offset=6
        at java.lang.ClassLoader.defineClassImpl(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:273)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:74)

**Comment by joschi** [comment]
@Bhavanish1 You should probably open an issue in the Dropwizard Metrics project at https://github.com/dropwizard/metrics

But it looks like there is no version of the [Papertrail JVM profiler](https://github.com/papertrail/profiler/) which runs with Java 6, so I think you're out of luck.
