### ISSUE TITLE
Cannot figure out type parameterization

### ISSUE THREAD

**Issue by bearrito** [dropwizard/dropwizard#2187]
```
Exception in thread "main" java.lang.IllegalStateException: Cannot figure out type parameterization for com.bossanova.core.bag.commands.IndexSetupCommand
	at io.dropwizard.util.Generics.getTypeParameter(Generics.java:65)
	at io.dropwizard.cli.ConfiguredCommand.getConfigurationClass(ConfiguredCommand.java:45)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:68)
	at io.dropwizard.cli.Cli.run(Cli.java:70)
	at io.dropwizard.Application.run(Application.java:80)
	at com.bossanova.core.bag.application.Main.main(Main.java:13)
```

My command signature looks like 
```
public class IndexSetupCommand extends ConfiguredCommand<BagConfig<Bag>> {
```

I'm assuming the next generics is confusing this.

**Comment by arteam** [comment]
Closed via #2190
