### ISSUE TITLE
Early end of file results in 500 instead of 400

### ISSUE THREAD

**Issue by scho** [dropwizard/dropwizard#2195]
From time to time, we see some 500s in our dropwizard applications when looking at the metric `io.dropwizard.jetty.MutableServletContextHandler.5xx`. Looking at the logs, doesn't show any errors, also the `io.dropwizard.jersey.errors.LoggingExceptionMapper` is not hit.

Then we found out, that at the same time, these mysterious 500s happen, also this warning shows up in the logs:
```
WARN  [2017-11-06 16:21:57,507] [] org.eclipse.jetty.servlet.ServletHandler:
! org.eclipse.jetty.io.EofException: Early EOF
! at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:877)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:189)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:141)
! at org.glassfish.jersey.message.internal.EntityInputStream.isEmpty(EntityInputStream.java:200)
! ... 46 common frames omitted
! Causing: javax.ws.rs.ProcessingException: org.eclipse.jetty.io.EofException: Early EOF
! at org.glassfish.jersey.message.internal.EntityInputStream.isEmpty(EntityInputStream.java:217)
! at org.glassfish.jersey.message.internal.InboundMessageContext.hasEntity(InboundMessageContext.java:772)
! at org.glassfish.jersey.servlet.WebComponent.filterFormParameters(WebComponent.java:670)
! at org.glassfish.jersey.servlet.WebComponent.initContainerRequest(WebComponent.java:520)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:471)
! ... 42 common frames omitted
! Causing: javax.servlet.ServletException: javax.ws.rs.ProcessingException: org.eclipse.jetty.io.EofException: Early EOF
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:489)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1772)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1759)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:582)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1180)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:512)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1112)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:426)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
! at org.eclipse.jetty.server.Server.handle(Server.java:534)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
! at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:229)
! at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1412)
! at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:351)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:283)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:108)
! at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
! at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
! at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
! at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
! at java.lang.Thread.run(Thread.java:745)
```

Is it possible, that the way Jetty handles early end of file in requests changed and `io.dropwizard.jersey.errors.EarlyEofExceptionMapper` does no longer work?

FYI: We are currently on dropwizard `1.0.9`.

**Comment by scho** [comment]
With the upgrade to dropwizard `1.1.6` the warning is gone and I see an error which goes all the up to the `LoggingExceptionMapper`:

```
ERROR [2017-12-11 09:42:13,352] [1f320cd2c64c2810] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 1f320cd2c64c2810
! org.eclipse.jetty.io.EofException: Early EOF
! at org.eclipse.jetty.server.HttpInput$3.getError(HttpInput.java:1104)
! at org.eclipse.jetty.server.HttpInput$3.noContent(HttpInput.java:1093)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:307)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:250)
! at org.glassfish.jersey.message.internal.EntityInputStream.isEmpty(EntityInputStream.java:200)
! ... 62 common frames omitted
! Causing: javax.ws.rs.ProcessingException: org.eclipse.jetty.io.EofException: Early EOF
! at org.glassfish.jersey.message.internal.EntityInputStream.isEmpty(EntityInputStream.java:217)
! at org.glassfish.jersey.message.internal.InboundMessageContext.hasEntity(InboundMessageContext.java:772)
! at org.glassfish.jersey.logging.ServerLoggingFilter.filter(ServerLoggingFilter.java:106)
! at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
! at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
! at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1650)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89)
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:120)
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:135)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1637)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:533)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:473)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:454)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:564)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:317)
! at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:239)
! at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1444)
! at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:351)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:234)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
! at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:128)
! at org.eclipse.jetty.util.thread.Invocable$InvocableExecutor.invoke(Invocable.java:222)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:294)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:199)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:673)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:591)
! at java.lang.Thread.run(Thread.java:745)
```

To me, it looks like `io.dropwizard.jersey.errors.EarlyEofExceptionMapper` does not catch this, since the exception is wrapped with a `javax.ws.rs.ProcessingException`.

**Comment by isaki-x** [comment]
Looking at the stack trace alone (not the code), I suspect this might be an issue with Jersey. I'll try to poke around if I have some time today and see what I can find.

**Comment by nickbabcock** [comment]
I'm not able to reproduce this. I have PR that I'll push that adds a test (tested on 1.1.6 and master) that triggers Jetty's `EofException` and the test confirms that that exception mapper is called 🤔

**Comment by scho** [comment]
With the upgrade to dropwizard `1.1.6`, we also introduced the Jersey HTTP logging feature (`org.glassfish.jersey.logging.LoggingFeature`), which calls `javax.ws.rs.container.ContainerRequestContext#hasEntity` which then throws the exception in my previous comment. Without the logging feature, there is still only a warning being logged. 

For now, our plan is to move to the newest dropwizard version and see if the problem is still there.

**Comment by nickbabcock** [comment]
Hey @scho, are you still seeing this issue else I'll close the issue.

**Comment by scho** [comment]
@shail We are on dw `1.3.5` and still have this issue.

**Comment by suvodeep-pyne** [comment]
This is still a problem. The thing is the exception is thrown before the request is processed. One of the ways of reproducing this is 
```
nc -v localhost 8080
POST /api/endpoint HTTP/1.0
Content-Type: application/x-www-form-urlencoded
Content-Length: 20


```
The empty lines at the end are required to complete the HTTP request. Here content length is 20, however, nothing is provided triggering the EOF exception.

However, I was unable to find a straightforward way of consuming the exception. It seems to get triggered before the `appHandler` actually handles the request.

**Comment by suvodeep-pyne** [comment]
Well. There seems to be a workaround. You can create a filter class which filters the exception and checks for Early Eof. This is a hack very specific for my case. However, you get the idea. I have tested this and it works. Here's the filter snippet.

```

  @Override
  public void doFilter(
      final ServletRequest request,
      final ServletResponse response,
      final FilterChain chain)
      throws IOException, ServletException {
    try {
      chain.doFilter(request, response);
    } catch (ServletException e) {
      if (isEarlyEofException(e)) {
        log.debug("EOF Exception encountered - client disconnected during stream processing.", e);

        if (response instanceof HttpServletResponse) {
          ((HttpServletResponse) response).setStatus(HttpServletResponse.SC_BAD_REQUEST);
        }
      } else {
        throw e;
      }
    }
  }

  private boolean isEarlyEofException(final ServletException e) {
    return e.getCause() instanceof ProcessingException
        && e.getCause().getCause() instanceof EofException
        && e.getCause().getCause().getMessage().equals(EARLY_EOF_MSG);
  }

```
