### ISSUE TITLE
how to enable stagemonitor (application monitoring)

### ISSUE THREAD

**Issue by qmnonic** [dropwizard/dropwizard#2209]
Not sure how to enable the stagemonitor servletplugin given the instructions.  I have an open issue at stagemonitor - https://github.com/stagemonitor/stagemonitor/issues/346 , but figure the dropwizard devs might know better?

Basic configuration step outlined here - https://github.com/stagemonitor/stagemonitor/wiki/Step-1%3A-In-Browser-Widget

For testing purposes, i have a clean version of the dropwizard example app installed, with a minimal commit that adds the ServletPlugin.Initializer.onStartup call - 
 https://github.com/qmnonic/dropwizard/tree/master/dropwizard-example

Logs show an error trying to add the stagemonitor servlet, running as `mvn -Denforcer.skip=true package`:

```
INFO  [2017-11-09 04:37:17,418] org.eclipse.jetty.setuid.SetUIDListener: Opened application@507f7cd1{HTTP/1.1,[http/1.1]}{0.0.0.0:50040}
INFO  [2017-11-09 04:37:17,419] org.eclipse.jetty.setuid.SetUIDListener: Opened admin@349996a6{HTTP/1.1,[http/1.1]}{0.0.0.0:50041}
INFO  [2017-11-09 04:37:17,422] org.stagemonitor.web.servlet.configuration.ConfigurationServlet: Registering configuration Endpoint /stagemonitor/configuration. You can dynamically change the configuration by issuing a POST request to /stagemonitor/configuration?key=stagemonitor.config.key&value=configValue&stagemonitor.password=password. If the password is not set, dynamically changing the configuration is not available. The password can be omitted if set to an empty string.
ERROR [2017-11-09 04:37:17,422] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.IllegalStateException: null
! at org.eclipse.jetty.servlet.ServletContextHandler$Context.addServlet(ServletContextHandler.java:1262)
! at org.stagemonitor.web.servlet.ServletPlugin$Initializer.onStartup(ServletPlugin.java:468)
! at com.example.helloworld.HelloWorldApplication$4.lifeCycleStarting(HelloWorldApplication.java:90)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:188)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:67)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:227)
! at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:141)
! at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:154)
! at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
! at org.junit.rules.RunRules.evaluate(RunRules.java:20)
! at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
! at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:369)
! at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:275)
! at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:239)
! at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:160)
! at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
! at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
! at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
! at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 4.368 s <<< FAILURE! - in com.example.helloworld.IntegrationTest
```

**Comment by arteam** [comment]
Please try to attach the listener to `environment.getApplicationContext().getServletHandler()` instead of `environment.lifecycle()`. They are two different lifecycles.

```java
environment.getApplicationContext().getServletHandler().addLifeCycleListener(new AbstractLifeCycle.AbstractLifeCycleListener() {
            @Override
            public void lifeCycleStarting(LifeCycle event) {
                new ServletPlugin.Initializer().onStartup(environment.getApplicationContext().getServletContext());
            }
        });
```

environment.lifecycle() usually tied to the Jetty server's lifecycle and the starts before the servlet environment.

But generally the use of `environment.getApplicationContext()` is discouraged, because by accessing you poke around in Jetty's internals. `environment.servlets()` is a preferred way to register servlets.

**Comment by qmnonic** [comment]
That seemed to work - thanks!
