### ISSUE TITLE
ClassNotFoundException when running command from Integration Test

### ISSUE THREAD

**Issue by edovale** [dropwizard/dropwizard#2274]
When running a command from an integration test using juni5 I am getting the following exception:

```
ERROR [2018-02-14 21:35:14,445] org.apache.tomcat.jdbc.pool.ConnectionPool: Unable to create initial connections of pool.
! java.lang.ClassNotFoundException: 
! at java.lang.Class.forName0(Native Method)
! at java.lang.Class.forName(Class.java:348)
! at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:38)
! ... 72 common frames omitted
! Causing: java.lang.ClassNotFoundException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2;ClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2
! at org.apache.tomcat.jdbc.pool.ClassLoaderUtil.loadClass(ClassLoaderUtil.java:56)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:272)
! ... 71 common frames omitted
! Causing: java.sql.SQLException: Unable to load class:  from ClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2;ClassLoader:sun.misc.Launcher$AppClassLoader@18b4aac2
! at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:283)
! at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:203)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:738)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:670)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.init(ConnectionPool.java:482)
! at org.apache.tomcat.jdbc.pool.ConnectionPool.<init>(ConnectionPool.java:154)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.pCreatePool(DataSourceProxy.java:118)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.createPool(DataSourceProxy.java:107)
! at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:131)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.createDatabase(AbstractLiquibaseCommand.java:94)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.openLiquibase(AbstractLiquibaseCommand.java:79)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:67)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:93)
! at io.huru.client.BaseITTest.resetDB(BaseITTest.java:36)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:389)
! at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
! at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.invokeMethodInExtensionContext(ClassTestDescriptor.java:289)
! at org.junit.jupiter.engine.descriptor.ClassTestDescriptor.lambda$synthesizeBeforeEachMethodAdapter$11(ClassTestDescriptor.java:277)
! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$null$2(TestMethodTestDescriptor.java:132)
! at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeMethodsOrCallbacksUntilExceptionOccurs(TestMethodTestDescriptor.java:152)
! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeBeforeEachMethods(TestMethodTestDescriptor.java:131)
! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:106)
! at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:57)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:83)
! at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
! at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
! at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
! at java.util.Iterator.forEachRemaining(Iterator.java:116)
! at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
! at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
! at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
! at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$null$2(HierarchicalTestExecutor.java:92)
! at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
! at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
! at java.util.Iterator.forEachRemaining(Iterator.java:116)
! at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
! at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
! at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
! at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
! at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
! at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$3(HierarchicalTestExecutor.java:92)
! at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:77)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
! at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
! at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:170)
! at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:154)
! at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:90)
! at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:86)
! at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
! at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
! at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
! at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
! at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

I am simply trying to reset the DB schema by running the migrations command to drop and recreate the DB. Here is the code for the tests:

```
@ExtendWith(DropwizardExtensionsSupport.class)
public class BaseITTest {

	public static final DropwizardAppExtension<ExampleConfiguration> EXTENSION = new DropwizardAppExtension<>(
			ExampleApplication.class, ResourceHelpers.resourceFilePath("config.yaml"));

	@BeforeClass
	public static void resetDB() throws Exception {
		EXTENSION.getApplication().run("db", "drop-all", "--confirm-delete-everything");
		EXTENSION.getApplication().run("db", "migrate");
	}

}
```

What I am noticing is that the dropwizard APP starts fine but when running the command I get the error. There seems to be an issue with classloaders. Has anyone seen this?

**Comment by joschi** [comment]
@edovale Please provide a minimal project we can use to reproduce the issue.

Also, please post the complete output of the following Maven command:
```
$ mvn dependency:tree
```

**Comment by edovale** [comment]
Here is the output of mvn dependency:tree
```
[INFO] Scanning for projects...
[WARNING] The project io.huru:example:jar:1.0-SNAPSHOT uses prerequisites which is only intended for maven-plugin projects but not for non maven-plugin projects. For such purposes you should use the maven-enforcer-plugin. See https://maven.apache.org/enforcer/enforcer-rules/requireMavenVersion.html
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building truebook 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ truebook ---
[INFO] io.huru:example:jar:1.0-SNAPSHOT
[INFO] +- io.dropwizard:dropwizard-core:jar:1.3.0-rc6:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:1.3.0-rc6:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.0:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.9.9:compile
[INFO] |  +- io.dropwizard:dropwizard-jackson:jar:1.3.0-rc6:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-core:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-afterburner:jar:2.9.4:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-joda:jar:2.9.4:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:1.3.0-rc6:compile
[INFO] |  |  +- org.hibernate:hibernate-validator:jar:5.4.2.Final:compile
[INFO] |  |  |  +- org.jboss.logging:jboss-logging:jar:3.3.0.Final:compile
[INFO] |  |  |  \- com.fasterxml:classmate:jar:1.3.4:compile
[INFO] |  |  +- org.glassfish:javax.el:jar:3.0.0:compile
[INFO] |  |  \- org.javassist:javassist:jar:3.22.0-GA:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:1.3.0-rc6:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.9.4:compile
[INFO] |  |  +- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] |  |  \- org.apache.commons:commons-text:jar:1.2:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:1.3.0-rc6:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:4.0.2:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:1.7.25:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.2.3:compile
[INFO] |  |  +- ch.qos.logback:logback-classic:jar:1.2.3:compile
[INFO] |  |  +- org.slf4j:log4j-over-slf4j:jar:1.7.25:compile
[INFO] |  |  +- org.slf4j:jcl-over-slf4j:jar:1.7.25:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-util:jar:9.4.8.v20171121:compile
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:1.3.0-rc6:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:1.3.0-rc6:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:2.25.1:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:2.25.1:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey2:jar:4.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider:jar:2.9.4:compile
[INFO] |  |  |  +- com.fasterxml.jackson.jaxrs:jackson-jaxrs-base:jar:2.9.4:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:jar:2.9.4:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet:jar:2.25.1:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-server:jar:9.4.8.v20171121:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-io:jar:9.4.8.v20171121:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-webapp:jar:9.4.8.v20171121:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-xml:jar:9.4.8.v20171121:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-continuation:jar:9.4.8.v20171121:compile
[INFO] |  +- io.dropwizard:dropwizard-servlets:jar:1.3.0-rc6:compile
[INFO] |  |  \- io.dropwizard.metrics:metrics-annotation:jar:4.0.2:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:1.3.0-rc6:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jetty9:jar:4.0.2:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlet:jar:9.4.8.v20171121:compile
[INFO] |  |  |  \- org.eclipse.jetty:jetty-security:jar:9.4.8.v20171121:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:9.4.8.v20171121:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:9.4.8.v20171121:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:1.3.0-rc6:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:4.0.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:4.0.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jmx:jar:4.0.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-servlets:jar:4.0.2:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:4.0.2:compile
[INFO] |  |  \- com.papertrail:profiler:jar:1.0.2:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:4.0.2:compile
[INFO] |  +- io.dropwizard:dropwizard-request-logging:jar:1.3.0-rc6:compile
[INFO] |  |  \- ch.qos.logback:logback-access:jar:1.2.3:compile
[INFO] |  +- net.sourceforge.argparse4j:argparse4j:jar:0.7.0:compile
[INFO] |  \- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.3:compile
[INFO] +- io.dropwizard:dropwizard-jdbi3:jar:1.3.0-rc6:compile
[INFO] |  +- io.dropwizard:dropwizard-db:jar:1.3.0-rc6:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-jdbc:jar:9.0.4:compile
[INFO] |  |     \- org.apache.tomcat:tomcat-juli:jar:9.0.4:compile
[INFO] |  +- org.jdbi:jdbi3-core:jar:3.0.1:compile
[INFO] |  |  +- org.antlr:antlr-runtime:jar:3.4:compile
[INFO] |  |  |  +- org.antlr:stringtemplate:jar:3.2.1:compile
[INFO] |  |  |  \- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  \- net.jodah:expiringmap:jar:0.5.6:compile
[INFO] |  +- org.jdbi:jdbi3-sqlobject:jar:3.0.1:compile
[INFO] |  +- org.jdbi:jdbi3-jodatime2:jar:3.0.1:compile
[INFO] |  +- org.jdbi:jdbi3-guava:jar:3.0.1:compile
[INFO] |  \- io.dropwizard.metrics:metrics-jdbi3:jar:4.0.2:compile
[INFO] +- io.dropwizard:dropwizard-migrations:jar:1.3.0-rc6:compile
[INFO] |  +- org.liquibase:liquibase-core:jar:3.5.4:compile
[INFO] |  \- com.mattbertolini:liquibase-slf4j:jar:2.0.0:compile
[INFO] +- io.dropwizard:dropwizard-client:jar:1.3.0-rc6:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:2.25.1:compile
[INFO] |  |  +- org.glassfish.jersey.core:jersey-common:jar:2.25.1:compile
[INFO] |  |  |  +- org.glassfish.jersey.bundles.repackaged:jersey-guava:jar:2.25.1:compile
[INFO] |  |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.1:compile
[INFO] |  |  +- org.glassfish.hk2.external:javax.inject:jar:2.5.0-b32:compile
[INFO] |  |  \- org.glassfish.hk2:hk2-locator:jar:2.5.0-b32:compile
[INFO] |  |     \- org.glassfish.hk2.external:aopalliance-repackaged:jar:2.5.0-b32:compile
[INFO] |  +- org.glassfish.jersey.ext.rx:jersey-rx-client:jar:2.25.1:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.5:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] |  |  \- commons-codec:commons-codec:jar:1.10:compile
[INFO] |  +- io.dropwizard.metrics:metrics-httpclient:jar:4.0.2:compile
[INFO] |  \- org.glassfish.jersey.connectors:jersey-apache-connector:jar:2.25.1:compile
[INFO] +- org.elasticsearch.client:elasticsearch-rest-high-level-client:jar:6.1.3:compile
[INFO] |  +- org.elasticsearch:elasticsearch:jar:6.1.3:compile
[INFO] |  |  +- org.apache.lucene:lucene-core:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-analyzers-common:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-backward-codecs:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-grouping:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-highlighter:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-join:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-memory:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-misc:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-queries:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-queryparser:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-sandbox:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-spatial:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-spatial-extras:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-spatial3d:jar:7.1.0:compile
[INFO] |  |  +- org.apache.lucene:lucene-suggest:jar:7.1.0:compile
[INFO] |  |  +- org.elasticsearch:securesm:jar:1.2:compile
[INFO] |  |  +- org.elasticsearch:elasticsearch-cli:jar:6.1.3:compile
[INFO] |  |  |  \- net.sf.jopt-simple:jopt-simple:jar:5.0.2:compile
[INFO] |  |  +- com.carrotsearch:hppc:jar:0.7.1:compile
[INFO] |  |  +- org.yaml:snakeyaml:jar:1.17:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-smile:jar:2.9.4:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.9.4:compile
[INFO] |  |  +- com.tdunning:t-digest:jar:3.0:compile
[INFO] |  |  +- org.hdrhistogram:HdrHistogram:jar:2.1.9:compile
[INFO] |  |  +- org.apache.logging.log4j:log4j-api:jar:2.9.1:compile
[INFO] |  |  \- org.elasticsearch:jna:jar:4.4.0-1:compile
[INFO] |  +- org.elasticsearch.client:elasticsearch-rest-client:jar:6.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpasyncclient:jar:4.1.2:compile
[INFO] |  |  +- org.apache.httpcomponents:httpcore-nio:jar:4.4.5:compile
[INFO] |  |  \- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  +- org.elasticsearch.plugin:parent-join-client:jar:6.1.3:compile
[INFO] |  |  +- org.locationtech.spatial4j:spatial4j:jar:0.6:compile
[INFO] |  |  +- com.vividsolutions:jts:jar:1.13:compile
[INFO] |  |  \- org.apache.logging.log4j:log4j-core:jar:2.9.1:compile
[INFO] |  \- org.elasticsearch.plugin:aggs-matrix-stats-client:jar:6.1.3:compile
[INFO] +- com.hubspot.dropwizard:dropwizard-guice:jar:1.0.6.0:compile
[INFO] |  +- com.squarespace.jersey2-guice:jersey2-guice-impl:jar:1.0.6:compile
[INFO] |  |  +- com.google.inject.extensions:guice-multibindings:jar:4.0:compile
[INFO] |  |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:2.25.1:compile
[INFO] |  |  \- com.squarespace.jersey2-guice:0-jersey2-guice-spi:jar:1.0.6:compile
[INFO] |  +- com.google.code.findbugs:annotations:jar:3.0.1:compile
[INFO] |  +- com.google.inject:guice:jar:4.0:compile
[INFO] |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  +- com.google.inject.extensions:guice-servlet:jar:4.0:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-server:jar:2.25.1:compile
[INFO] |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:2.25.1:compile
[INFO] |  |  +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO] |  +- org.reflections:reflections:jar:0.9.10:compile
[INFO] |  +- javax.servlet:javax.servlet-api:jar:3.1.0:compile
[INFO] |  +- javax.inject:javax.inject:jar:1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO] |  +- org.glassfish.hk2:hk2-api:jar:2.5.0-b32:compile
[INFO] |  |  \- org.glassfish.hk2:hk2-utils:jar:2.5.0-b32:compile
[INFO] |  +- javax.ws.rs:javax.ws.rs-api:jar:2.0.1:compile
[INFO] |  \- com.google.guava:guava:jar:24.0-jre:compile
[INFO] |     +- org.checkerframework:checker-compat-qual:jar:2.0.0:compile
[INFO] |     +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO] |     +- com.google.j2objc:j2objc-annotations:jar:1.1:compile
[INFO] |     \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO] +- org.jdbi:jdbi3-postgres:jar:3.0.1:compile
[INFO] |  \- org.postgresql:postgresql:jar:9.4.1212:compile
[INFO] +- org.junit.jupiter:junit-jupiter-engine:jar:5.0.3:test
[INFO] |  +- org.apiguardian:apiguardian-api:jar:1.0.0:test
[INFO] |  +- org.junit.platform:junit-platform-engine:jar:1.0.3:test
[INFO] |  |  +- org.junit.platform:junit-platform-commons:jar:1.0.3:test
[INFO] |  |  \- org.opentest4j:opentest4j:jar:1.0.0:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-api:jar:5.0.3:test
[INFO] \- io.dropwizard:dropwizard-testing:jar:1.3.0-rc6:compile
[INFO]    +- junit:junit:jar:4.12:compile
[INFO]    |  \- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO]    +- org.objenesis:objenesis:jar:2.6:compile
[INFO]    +- org.assertj:assertj-core:jar:3.9.0:test
[INFO]    \- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:jar:2.25.1:compile
[INFO]       \- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:2.25.1:compile
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.466 s
[INFO] Finished at: 2018-02-15T09:58:26-05:00
[INFO] Final Memory: 26M/324M
[INFO] ------------------------------------------------------------------------
```

**Comment by SriniMurthy** [comment]
Anybody found a resolution for this issue? I have tried various databases, drivers, even put the driver jar in the classpath manually to no effect

**Comment by arteam** [comment]
There's some discussion in #2275 about reproducing the issue.

**Comment by joschi** [comment]
@edovale Please verify whether this problem still exists on Dropwizard 1.3.5 and leave a comment.
We'll reopen the issue if the problem still exists.

**Comment by schmee** [comment]
Just for the record I encountered this issue today when upgrading a project from Dropwizard 1.2.0 to 1.3.5. The problem pops up in an integration test using the `DropwizardAppRule`. If I get around to it I'll try to extract a minimal example, but for now I just wanted to leave a note that the issue still exists in 1.3.5.

**Comment by schmee** [comment]
Turns out this was a PEBKAC error, the DB driver was not configured properly. Sorry for the noise!

**Comment by tvaughan77** [comment]
@schmee Could you elaborate when you say the DB driver wasn't configured properly?  I'm trying a Dropwizard 1.2.0 -> 1.3.5 upgrade and all my IntTests that were using a `@Classrule` to spin up a MySQL instance are failing because of an apparent ClassNotFoundException...

It's weird, because the Flyway migration works fine, but then the first time I try us use a DBI handle.open() it barfs...

**Comment by tvaughan77** [comment]
> @schmee Could you elaborate when you say the DB driver wasn't configured properly? I'm trying a Dropwizard 1.2.0 -> 1.3.5 upgrade and all my IntTests that were using a `@Classrule` to spin up a MySQL instance are failing because of an apparent ClassNotFoundException...
> 
> It's weird, because the Flyway migration works fine, but then the first time I try us use a DBI handle.open() it barfs...

Answering my own question . . . . 

Somewhere between 1.2.0 and 1.3.5 the DataSourceFactory changed such that it needs to be provided with a driverClass String property.  In my Dropwizard 1.2.0 codebase there must have been some classpath scanning magic going on because my IntTests had historically been able to get away with just this configuration:

```
         DataSourceFactory dataSourceFactory = new DataSourceFactory();
        dataSourceFactory.setUrl(this.mySQLRule.getDbUrl());
        dataSourceFactory.setUser(this.mySQLRule.getDbUser());
        dataSourceFactory.setPassword(this.mySQLRule.getDbPassword());
```

Once I added `dataSourceFactory.setDriverClass("com.mysql.jdbc.Driver");`  everything started working again

The bitch about this was that because the default driver set in the DataSourceFactory was the empty string (`""`), the stack traces were pretty tough to figure out what Class couldn't be loaded.  Perhaps the Tomcat ConnectionPool guys would benefit from adding a check if the String isn't null/empty
