### ISSUE TITLE
1.3.0-rc3 and newer has breaking dependency changes

### ISSUE THREAD

**Issue by phambryan** [dropwizard/dropwizard#2285]
Upgrading to metrics 4.0.2 in rc3 has breaking collision.
We're using cassandra-driver-core 3.4.0 and it's based on metric 3.2.2.
Is it's possible to move 1.3.x release to metrics5 ?

Stack trace:
INFO  [2018-02-27 16:46:59,196] com.datastax.driver.core.NettyUtil: Did not find Netty's native epoll transport in the classpath, defaulting to NIO.
java.lang.NoClassDefFoundError: com/codahale/metrics/JmxReporter
    at com.datastax.driver.core.Metrics.<init>(Metrics.java:113)
    at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1467)
    at com.datastax.driver.core.Cluster.init(Cluster.java:159)
    at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:330)
    at com.datastax.driver.core.Cluster.connect(Cluster.java:280)

Referencing: https://github.com/dropwizard/metrics/issues/1248

**Comment by joschi** [comment]
@phambryan We won't downgrade Dropwizard Metrics in Dropwizard 1.3.0.

I'm afraid you'll either have to stay on Dropwizard 1.2.x for that particular project or wait until the Cassandra driver upgrades to Dropwizard Metrics 4.x (which seems to have happened for Cassandra Java Driver 4.0: https://github.com/datastax/java-driver/pull/937).
