### ISSUE TITLE
Starting two services on the same port results in unexpected behaviour

### ISSUE THREAD

**Issue by aedwards-act** [dropwizard/dropwizard#2303]
In our integration tests we were starting two separate drop wizard services, a mistake was made where they were both configured to start on the same port.

We get an `java.lang.IllegalArgumentException: A metric named org.eclipse.jetty.util.thread.QueuedThreadPool.dw.utilization already exists
	at com.codahale.metrics.MetricRegistry.register(MetricRegistry.java:91)`, the root cause of which was difficult to debug, overriding the metric registry with one which suppressed the exception allowed the service to resume until a `java.net.BindException: Address already in use: bind`.
Changing the port and reverting the implementation meant the registry issue went away.

We've also seen a similar issue on our build server, we would guess when a test service has not been shutdown gracefully during a previous build.

I'm not sure what behavior would cause two services to share a metric registry if they attempt to start on the same port, but it is an issue that it hides the BindException.

**Comment by aedwards-act** [comment]
This was seen in dropwizard 1.2.2.

When we, previously, used version 8.2 we would get the expected `java.net.BindException`.

**Comment by arteam** [comment]
Thanks for reporting this issue! I tried reproduce it, but wasn't able to. Here's a test I used:

```java
public class DoubleAppRuleTest {

    @Rule
    public DropwizardAppRule<Configuration> RULE = new DropwizardAppRule<>(TestApplication.class, resourceFilePath("test-config.yaml"));

    @Rule
    public DropwizardAppRule<Configuration> RULE_2 = new DropwizardAppRule<>(TestApplication.class, resourceFilePath("test-config.yaml"));

    @Test
    public void canGetExpectedResourceOverHttp() {
        Assertions.assertThat(RULE.client().target("http://localhost:" + RULE.getLocalPort() + "/application/")
            .request()
            .get(String.class)).isEqualTo("test");
    }

    public static class TestApplication extends Application<Configuration> {

        @Override
        public void run(Configuration configuration, Environment environment) throws Exception {
            environment.jersey().register(new TestResource());
        }
    }

    @Path("/")
    public static class TestResource {

        @GET
        public String test() {
            return "test";
        }
    }
}
```

```yaml
server:
  type: simple
  connector:
    type: http
    port: 12000
```


When I run it I get:
```
INFO  [2018-03-13 16:12:49,909] io.dropwizard.server.ServerFactory: Starting TestApplication
ERROR [2018-03-13 16:12:49,979] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.net.BindException: Address already in use
```

A couple of questions:
* Do you customize the `MetricsRegistry` used in your ap? 
* Do you use `SharedMetricRegistries`? Dropwizard by default sets up the current `MetricsRegistry` as shared. Maybe there's some point when your app picks up the old `MetricsRegistry` from the previous process.

**Comment by P-A-R-U-S** [comment]
Getting same error:

`14:59 $ java -jar target/oci-certs-canary-0.1-SNAPSHOT.jar server oci-certs-canary-configuration.yml 
INFO  [2021-03-03 23:03:08,698] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-03-03 23:03:08,700] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
INFO  [2021-03-03 23:03:08,744] io.dropwizard.server.ServerFactory: Starting CanaryService
ERROR [2021-03-03 23:03:08,831] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.net.BindException: Address already in use
! at java.base/sun.nio.ch.Net.bind0(Native Method)
! at java.base/sun.nio.ch.Net.bind(Net.java:550)
! at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:249)
! at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
! at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
! ... 10 common frames omitted
! Causing: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
! at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
! at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:216)
! ... 8 common frames omitted
! Causing: java.lang.RuntimeException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
! at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:229)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:204)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:71)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.oracle.pic.ocicerts.controlplane.CanaryService.main(CanaryService.java:15)
java.lang.RuntimeException: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
	at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:229)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarting(AbstractLifeCycle.java:204)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:71)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.oracle.pic.ocicerts.controlplane.CanaryService.main(CanaryService.java:15)
Caused by: java.io.IOException: Failed to bind to 0.0.0.0/0.0.0.0:8080
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:349)
	at org.eclipse.jetty.server.ServerConnector.open(ServerConnector.java:310)
	at org.eclipse.jetty.setuid.SetUIDListener.lifeCycleStarting(SetUIDListener.java:216)
	... 8 more
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:550)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:249)
	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:88)
	at org.eclipse.jetty.server.ServerConnector.openAcceptChannel(ServerConnector.java:345)
	... 10 more`

**Comment by joschi** [comment]
> ```
> java.net.BindException: Address already in use
> ```

That's expected when you try to bind a socket which is already used by another application.
