### ISSUE TITLE
Custom ExceptionMappers not working properly. (dropwizard version - 1.3.1)

### ISSUE THREAD

**Issue by vishal-kedia** [dropwizard/dropwizard#2351]
```
@Data
@AllArgsConstructor
public class ExceptionResponse {
  private ApplicationException.ApplicationExceptionCode errorCode;
  private String errorMessage;
}
```
```
@Provider
public class ApplicationExceptionMapper implements ExceptionMapper<ApplicationException> {

  @Override
  public Response toResponse(ApplicationException ex) {
    return Response.status(ex.getCode().getCode())
        .entity(new ExceptionResponse(ex.getCode(), ex.getMessage()))
        .type(MediaType.APPLICATION_JSON_TYPE)
        .build();
  }

}
```
```
@Getter
public class ApplicationException extends Exception {

  /**
   * 
   */
  private static final long serialVersionUID = 9060461350080152830L;

  @Getter
  public static enum ApplicationExceptionCode {
    UNAUTHORIZED_401(401, "Unauthorized Access"), INVALID_USER_404(404,
        "User not found"), BAD_REQUEST_400(400,
            "Some of the input fields may be incorrect"), INTERNAL_SERVER_ERROR_500(500,
                "Something went wrong");

    private int code;
    private String defaultMessage;

    private ApplicationExceptionCode(int code, String defaultMessage) {
      this.defaultMessage = defaultMessage;
    }
  }

  private ApplicationExceptionCode code;

  public ApplicationException(ApplicationExceptionCode code) {
    this(code, code.getDefaultMessage());
  }

  public ApplicationException(ApplicationExceptionCode code, String message) {
    super(message);
    this.code = code;
  }
}
```
```
@Path("/v2/test")
public class TestResource {

  @GET
  public Response throwError() throws ApplicationException {
    throw new ApplicationException(ApplicationExceptionCode.INTERNAL_SERVER_ERROR_500);
  }

}
```
And then registered the exception mapper with jersey.
`env.jersey().register(ApplicationExceptionMapper.class);`
`env.jersey().register(TestResource.class);`
When doing `curl http://localhost:8090/v2/test` I got 
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 500 insufficient content written</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /v2/test. Reason:
<pre>    insufficient content written</pre></p>
</body>
</html>
```
And console logs for the same:
```
2018-05-09 12:02:42,495 [dw-17 - GET /v2/test] ERROR o.g.j.s.ServerRuntime$Responder - [Request-Id: ] - Error while closing the output stream in order to commit response.
! java.lang.IllegalArgumentException: null
! at org.eclipse.jetty.server.Response.setStatusWithReason(Response.java:788)
! at org.eclipse.jetty.server.Response.setStatus(Response.java:782)
! at org.glassfish.jersey.servlet.internal.ResponseWriter.writeResponseStatusAndHeaders(ResponseWriter.java:171)
! at org.glassfish.jersey.server.ServerRuntime$Responder$1.getOutputStream(ServerRuntime.java:701)
! at org.glassfish.jersey.message.internal.CommittingOutputStream.commitStream(CommittingOutputStream.java:200)
! at org.glassfish.jersey.message.internal.CommittingOutputStream.flushBuffer(CommittingOutputStream.java:305)
! at org.glassfish.jersey.message.internal.CommittingOutputStream.commit(CommittingOutputStream.java:261)
! at org.glassfish.jersey.message.internal.CommittingOutputStream.close(CommittingOutputStream.java:276)
! at org.glassfish.jersey.message.internal.OutboundMessageContext.close(OutboundMessageContext.java:877)
! at org.glassfish.jersey.server.ContainerResponse.close(ContainerResponse.java:412)
! at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:784)
! at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:444)
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:490)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:334)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at com.serviceenabled.dropwizardrequesttracker.RequestTrackerServletFilter.doFilter(RequestTrackerServletFilter.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:561)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:564)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
! at org.eclipse.jetty.util.thread.Invocable.invokePreferred(Invocable.java:122)
! at org.eclipse.jetty.util.thread.strategy.ExecutingExecutionStrategy.invoke(ExecutingExecutionStrategy.java:58)
! at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:201)
! at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:133)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
! at java.lang.Thread.run(Thread.java:748)
0:0:0:0:0:0:0:1 - - [09/May/2018:06:32:42 +0000] "GET /v2/test HTTP/1.1" 500 277 "-" "curl/7.54.0" 7

```

**Comment by vishal-kedia** [comment]
have tried all of that it doesn't work, if we remove the entity from the response in exception mapper then it works fine.

**Comment by vishal-kedia** [comment]
New exception mapper with which i tried.
```
import javax.ws.rs.core.Response;
import javax.ws.rs.ext.ExceptionMapper;
import com.test.TestException;
import io.dropwizard.jersey.errors.ErrorMessage;

public class TestExceptionMapper implements ExceptionMapper<TestException>{

  @Override
  public Response toResponse(TestException exception) {
    return Response.ok(new ErrorMessage("test")).build();
  }

}
```
and simplified exception as below:
```
public class TestException extends RuntimeException{

  /**
   * 
   */
  private static final long serialVersionUID = -7005260865437222239L;

}
```
and error throwing resource:
```
@Path("/v2/test")
public class TestResource {
  
  @GET
  public Response test() {
    throw new TestException();
  }

}
```

**Comment by vishal-kedia** [comment]
and it gives the same error - `Error while closing the output stream in order to commit response.`

**Comment by nickbabcock** [comment]
Ensure that response can be serialized to media type produced in the function if not specified in the exception mapper. If this fails, I will ask that you upload the complete example (with a test that demonstrates this issue) so that we may take a look.

**Comment by vishal-kedia** [comment]
@nickbabcock sorry for trouble, i have done the stupidest mistake possible. Forgot to initialize the `code` in `ApplicationExceptionCode ` constructor. and in exception mapper `ex.getCode().getCode()` is returning 0 and status is getting set as 0 in response 
 `Response.status(ex.getCode().getCode())`. Thanks for all the help.
