### ISSUE TITLE
Custom config entry always throws ConfigurationParsingException

### ISSUE THREAD

**Issue by black-snow** [dropwizard/dropwizard#2357]
I must be stupid. I can't get the configuration to accept custom entries.

According to the docs it should be sufficient to just add the field to my Configuration. Let's say I want a simple text field *x*:

```yml
logging:
  level: Info
  ...

x: y
```

```java
public class MyConfig extends Configuration {
    @NotEmpty
    private String x;

    @JsonProperty
    public String getX() { return x; }

    @JsonProperty
    public void setX(String x) { this.x = x; }
}
```

But as soon as I add anything non-standard to my config.yml I end up with:

```
io.dropwizard.configuration.ConfigurationParsingException: config.yml has an error:
  * Unrecognized field at: smtpConfiguration
    Did you mean?:
      - logging
      - metrics
      - server

        at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:140)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at xyz.main(xyz.java:45)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "x" (class io.dropwizard.Configuration), not marked as ignorable (3 known properties: "server", "logging", "metrics"])
...
```

I also tried some nested things with a custom class with getters and setters for the fields.
I also tried a ConfigurationFactory but that didn't help either.
Also tried `@JsonProperty("x")`.

What am I missing?

**Comment by black-snow** [comment]
@joschi There you go:

```java
public class FrontendTestingApplication extends Application<FrontendTestingConfiguration> implements Observer {
	
    private static FrontendTestingApplication instance;

    public static void main(final String[] args) throws Exception {
    	instance = new FrontendTestingApplication();
        instance.run(args);
    }
    
    public static FrontendTestingApplication getInstance() {
    	if (instance == null)
    		instance = new FrontendTestingApplication();
    	return instance;
    }

    @Override
    public String getName() {
        return "FrontendTesting";
    }

    @Override
    public void initialize(final Bootstrap<FrontendTestingConfiguration> bootstrap) {
    	bootstrap.addCommand(new TestCommand<FrontendTestingConfiguration>(this));
    }
    
    ...
```

```java
public class TestCommand<B extends Configuration> extends ConfiguredCommand<B> {
	
	private FrontendTestingApplication app;

	protected TestCommand(Application<B> app) {
		super("test", "xy\r\n");
		this.app = (FrontendTestingApplication) app;
	}

    ...
```

**Comment by joschi** [comment]
@black-snow Please provide a complete example. For example, we don't know the implementation of `FrontendTestingConfiguration`.

**Comment by black-snow** [comment]
See the example `MyConfig` in the first post - I just changed the name.

**Comment by joschi** [comment]
@black-snow Humor me and provide the complete code.

**Comment by black-snow** [comment]
Updated https://github.com/dropwizard/dropwizard/issues/2357#issuecomment-388802017

**Comment by black-snow** [comment]
That worked! Thanks Jochen!

**Comment by NehaThawani44** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project
        xmlns="http://maven.apache.org/POM/4.0.0"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>com.leanix.task</groupId>
    <artifactId>todo-service</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>TodoService</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <dropwizard.version>4.0.7</dropwizard.version>
        <mainClass>com.leanix.task.todoservice.ToDoApplication</mainClass>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.dropwizard</groupId>
                <artifactId>dropwizard-dependencies</artifactId>
                <version>${dropwizard.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>

<dependency>
    <groupId>io.dropwizard</groupId>
    <artifactId>dropwizard-core</artifactId>
    <version>4.0.7</version>
</dependency>
        <dependency>
    <groupId>org.hibernate.orm</groupId>
    <artifactId>hibernate-core</artifactId>

</dependency>
  <dependency>
    <groupId>io.dropwizard</groupId>
    <artifactId>dropwizard-jdbi3</artifactId>
    <version>4.0.7</version>
</dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
        </dependency>
   <dependency>
    <groupId>jakarta.ws.rs</groupId>
    <artifactId>jakarta.ws.rs-api</artifactId>  
   </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>
        <dependency>
            <groupId>org.hibernate.validator</groupId>
            <artifactId>hibernate-validator</artifactId>
        </dependency>
   <dependency>
    <groupId>org.jdbi</groupId>
    <artifactId>jdbi3-core</artifactId>
</dependency>
<dependency>
    <groupId>org.jdbi</groupId>
    <artifactId>jdbi3-sqlobject</artifactId>
</dependency>

<dependency>
    <groupId>com.h2database</groupId>
    <artifactId>h2</artifactId>   
</dependency>


    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>3.5.2</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-jar-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>3.12.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>3.2.5</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-source-plugin</artifactId>
                    <version>3.3.0</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.6.3</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-site-plugin</artifactId>
                    <version>3.12.1</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>3.5.0</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <configuration>
                    <createDependencyReducedPom>true</createDependencyReducedPom>
                    <transformers>
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                        <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                            <mainClass>${mainClass}</mainClass>
                        </transformer>
                    </transformers>
                    
                    <filters>
                        <filter>
                            <artifact>*:*</artifact>
                            <excludes>
                                <exclude>META-INF/*.SF</exclude>
                                <exclude>META-INF/*.DSA</exclude>
                                <exclude>META-INF/*.RSA</exclude>
                            </excludes>
                        </filter>
                    </filters>
                </configuration>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>                     
                <addClasspath>true</addClasspath>
                <classpathPrefix>lib/</classpathPrefix>
                <mainClass>com.leanix.task.todoservice.ToDoApplication</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>11</source>
                    <target>11</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <executions>
                    <execution>
                        <id>attach-javadocs</id>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <reporting>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-project-info-reports-plugin</artifactId>
                <configuration>

                    <dependencyDetailsEnabled>false</dependencyDetailsEnabled>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
            </plugin>
        </plugins>
    </reporting>
    <profiles>
        <profile>
            <id>java11+</id>
            <activation>
                <jdk>[11,)</jdk>
            </activation>
            <properties>
                
                <maven.javadoc.skip>true</maven.javadoc.skip>
            </properties>
        </profile>
    </profiles>
</project>
 Here is my Pom.xml and here is my config file , I dont know what is wrong with my config @joschi .    


h2:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  user: sa
  password: ""
  properties:
    charSet: UTF-8
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 5
  maxSize: 15
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1m  # Adjusted format for 1 minute
  healthCheckProperties:
    timeout: 5s

server:
  softNofileLimit: 1000
  applicationConnectors:
    - type: http
      port: 8080

todo:
  id: '1'
  title: "MorningTask"
  description: "MorningTask1"

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: INFO

  # Logger-specific levels.
  loggers:

    # Sets the level for 'com.example.app' to DEBUG.
    com.example.app: DEBUG

    # Redirects SQL logs to a separate file
    org.hibernate.SQL:
      level: DEBUG

  # Logback's Time Based Rolling Policy - archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}.log.gz
  # Logback's Size and Time Based Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
  # Logback's Fixed Window Rolling Policy -  archivedLogFilenamePattern: /tmp/application-%i.log.gz

  appenders:
    - type: console
    - type: file
      threshold: INFO
      logFormat: "%-6level [%d{HH:mm:ss.SSS}] [%t] %logger{5} - %X{code} %msg %n"
      currentLogFilename: /tmp/application.log
      archivedLogFilenamePattern: /tmp/application-%d{yyyy-MM-dd}-%i.log.gz
      archivedFileCount: 7
      timeZone: UTC
      maxFileSize: 10MiB
-----------------


    @JsonProperty("h2")
    private DataSourceFactory database = new DataSourceFactory();

    @JsonProperty("todo")
    private ToDoConfiguration todo = new ToDoConfiguration();

    public DataSourceFactory getDataSourceFactory() {
        return database;
    }

    public ToDoConfiguration getTodo() {
        return todo;
    }
-------------------

Also in my run config of intelliJ i have added: arguments server config.yml
Tried every way yet it doesnt work
