### ISSUE TITLE
dropwizard-example database setup - migrations.xml does not exist

### ISSUE THREAD

**Issue by mikey-t** [dropwizard/dropwizard#2406]
I'm attempting to follow the readme directions to get the dropwizard-example application running. It appears to generate the jar successfully, but the db migrate fails saying that the migrations.xml file does not exist. I cracked open the generated jar file and it's definitely not there. Is it supposed to be? I'm new to java - I'm probably missing something really obvious.

Here's the output for the migrate command:

java -jar target/dropwizard-example-1.4.0-SNAPSHOT.jar db migrate example.yml
INFO  [2018-06-22 22:31:07,811] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
INFO  [2018-06-22 22:31:07,816] liquibase.executor.jvm.JdbcExecutor: SELECT COUNT(*) FROM PUBLIC.DATABASECHANGELOGLOCK
INFO  [2018-06-22 22:31:07,820] liquibase.executor.jvm.JdbcExecutor: SELECT LOCKED FROM PUBLIC.DATABASECHANGELOGLOCK WHERE ID=1
INFO  [2018-06-22 22:31:07,859] liquibase.lockservice.StandardLockService: Successfully acquired change log lock
INFO  [2018-06-22 22:31:07,897] liquibase.lockservice.StandardLockService: Successfully released change log lock
liquibase.exception.ChangeLogParseException: **migrations.xml does not exist**
        at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:106)
        at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
        at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:217)
        at liquibase.Liquibase.update(Liquibase.java:190)
        at liquibase.Liquibase.update(Liquibase.java:179)
        at liquibase.Liquibase.update(Liquibase.java:175)
        at liquibase.Liquibase.update(Liquibase.java:168)
        at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:68)
        at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
        at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
        at com.example.helloworld.HelloWorldApplication.main(HelloWorldApplication.java:38)

**Comment by nickbabcock** [comment]
I can't seem to replicate this. Have you tried the following?

```bash
cd dropwizard
./mvnw package
cd dropwizard-example
java -jar target/dropwizard-example-1.4.0-SNAPSHOT.jar db migrate example.yml
```

**Comment by mikey-t** [comment]
That's what I needed, thanks! Is it true to assume that most people would know to do that or is that something that should be added to the readme for beginners like me?

**Comment by nickbabcock** [comment]
What step did you miss? I'm happy to see the dropwizard-example readme amended 😊

**Comment by mikey-t** [comment]
I ran mvn not mvnw and I ran it in the dropwizard-example directory and not the root dropwizard directory. That might have been implied for someone not so new to Java - I'm not sure.

**Comment by nickbabcock** [comment]
Yeah don't worry about it! We want the readme to be approachable to beginners 😄 

fd73b20 should close this. Respond back if you have any more questions.
