### ISSUE TITLE
Getting an Logging exception with getLong not implemented error

### ISSUE THREAD

**Issue by MurahariVadapalli** [dropwizard/dropwizard#2415]
```
    @SqlUpdate("INSERT INTO test7 (namespaceID, vendorIdJson, vendorIdJsonMd5) VALUES (:ns, :vendorJson, :vendorMd5)")
    @GetGeneratedKeys   
    long insertIdentifier(@Bind("ns") int ns, @Bind("vendorJson") String vendorJson, @Bind("vendorMd5") String vendorMd5);
```
```
        for (VendorID vendorId: newVendors) {
            Long catId = this.mappedIdentsDAO.insertIdentifier(namespace.get(), vendorId.toJson(), vendorId.toMd5());
            ImmutableMap.Builder<String, Object> builder = ImmutableMap.builder();

            builder.put("RADS Category", catId);
            builder.put("Vendor ID", vendorId.getMap());
            identifierMaps.add(builder.build());
        }
```
```
    <dependency>
      <groupId>com.oracle</groupId>
      <artifactId>ojdbc6</artifactId>
      <version>11.2.0.3</version>
    </dependency>
```
```
ERROR [2018-06-27 08:38:53,878] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: d0eb6b93a56f975d
! java.sql.SQLException: Invalid column type: getLong not implemented for class oracle.jdbc.driver.T4CRowidAccessor
! at oracle.jdbc.driver.Accessor.unimpl(Accessor.java:412)
! at oracle.jdbc.driver.Accessor.getLong(Accessor.java:551)
! at oracle.jdbc.driver.OracleReturnResultSet.getLong(OracleReturnResultSet.java:425)
! at org.skife.jdbi.v2.util.LongColumnMapper.mapColumn(LongColumnMapper.java:34)
! at org.skife.jdbi.v2.util.LongColumnMapper.mapColumn(LongColumnMapper.java:22)
! at org.skife.jdbi.v2.sqlobject.FigureItOutResultSetMapper.map(FigureItOutResultSetMapper.java:35)
! at org.skife.jdbi.v2.GeneratedKeys.first(GeneratedKeys.java:73)
! ... 65 common frames omitted
```

**Comment by joschi** [comment]
@MurahariVadapalli This seems to be a problem of Oracle and JDBI.

Take a look at https://github.com/jdbi/jdbi/blob/v3.3.0/oracle12/src/test/java/org/jdbi/v3/oracle12/TestGetGeneratedKeysOracle.java for how they solve that problem (with a custom [`RowMapper`](http://jdbi.org/apidocs/org/jdbi/v3/core/mapper/RowMapper.html)).
