### ISSUE TITLE
Support MDC on access logs

### ISSUE THREAD

**Issue by mattnelson** [dropwizard/dropwizard#2419]
Logback does not currently support[1] MDC on access logs. There is a comment[2] on that JIRA that shows a workaround via a custom encoder. The example is for json. I'm wondering if the json logs introduced in #2232 would be able to be extended to also support this workflow.

[1] https://jira.qos.ch/browse/LOGBACK-1016
[2] https://jira.qos.ch/browse/LOGBACK-1016?focusedCommentId=19139&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-19139

**Comment by BenRomberg** [comment]
For anyone interested to use this with Dropwizard 1.3:

```
@JsonTypeName("logback-access-with-context")
public class AccessWithContextRequestLogFactory extends LogbackAccessRequestLogFactory {
    private String requestLogName = "logback-access-with-context";

    @JsonCreator
    @RelaxInstantiator
    public AccessWithContextRequestLogFactory(Optional<String> name) {
        name.ifPresent(requestLogName -> this.requestLogName = requestLogName);
    }

    @JsonProperty
    public String getName() {
        return this.requestLogName;
    }

    /**
     * Adjusted from {@link LogbackAccessRequestLogFactory#build(String)}
     */
    @Override
    public RequestLog build(String name) {
        Logger logger = (Logger) LoggerFactory.getLogger("http.request");
        logger.setAdditive(false);

        LoggerContext context = logger.getLoggerContext();

        AccessWithContextRequestLog requestLog = new AccessWithContextRequestLog();

        LevelFilterFactory<IAccessEvent> levelFilterFactory = new NullLevelFilterFactory<>();
        AsyncAppenderFactory<IAccessEvent> asyncAppenderFactory = new AsyncAccessEventAppenderFactory();
        LayoutFactory<IAccessEvent> layoutFactory = AccessWithContextLayout::new;

        for (AppenderFactory<IAccessEvent> output : getAppenders()) {
            requestLog.addAppender(output.build(context, name, layoutFactory, levelFilterFactory, asyncAppenderFactory));
        }
        return requestLog;
    }
}

public class AccessWithContextRequestLog extends LogbackAccessRequestLog {
    /**
     * Adjusted from {@link ch.qos.logback.access.jetty.RequestLogImpl#log(Request, Response)}
     */
    @Override
    public void log(Request jettyRequest, Response jettyResponse) {
        JettyServerAdapter adapter = new JettyServerAdapter(jettyRequest, jettyResponse);
        IAccessEvent accessEvent = new AccessWithContextEvent(jettyRequest, jettyResponse, adapter);
        if (getFilterChainDecision(accessEvent) == FilterReply.DENY) {
            return;
        }
        iteratorForAppenders().forEachRemaining(appender -> appender.doAppend(accessEvent));
    }
}

public class AccessWithContextLayout extends LogbackAccessRequestLayout {
    static {
        defaultConverterMap.put("X", AccessMdcConverter.class.getName());
    }

    public AccessWithContextLayout(Context context, TimeZone timeZone) {
        super(context, timeZone);
        setPattern(
                "%h %l %u [%t{dd/MMM/yyyy:HH:mm:ss Z," + timeZone.getID() + "}] [%X] \"%r\" %s %b \"%i{Referer}\" \"%i{User-Agent}\" %D");
    }
}

public class AccessWithContextEvent extends AccessEvent {
    private final Map<String, String> mdc;

    public AccessWithContextEvent(HttpServletRequest httpRequest, HttpServletResponse httpResponse, ServerAdapter adapter) {
        super(httpRequest, httpResponse, adapter);
        this.mdc = MDC.getCopyOfContextMap();
    }

    public Map<String, String> getMdc() {
        return mdc;
    }
}

public class AccessMdcConverter extends AccessConverter {
    private final MDCConverter delegate = new MDCConverter();

    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public String convert(IAccessEvent event) {
        if (!(event instanceof AccessWithContextEvent)) {
            return "";
        }
        LoggingEvent loggingEvent = new LoggingEvent();
        loggingEvent.setMDCPropertyMap(((AccessWithContextEvent) event).getMdc());
        return delegate.convert(loggingEvent);
    }
}
```

Usage:
* Create a file `META-INF/services/io.dropwizard.request.logging.RequestLogFactory` with content `package.of.the.AccessWithContextRequestLogFactory`
* In the Dropwizard configuration, set `server.requestLog.type` to `"logback-access-with-context"`.

**Comment by subash89** [comment]
I'am using dropwizar 2.0.14 can want to use MDC in request log. The above suggestion does not work in 2.x. The logback-access-with-context defined in server.requestLog.type not get picked up.


io.dropwizard.configuration.ConfigurationParsingException: src/main/resources/config.yml has an error:
  * Failed to parse configuration at: server.requestLog; Cannot deserialize instance of `java.lang.String` out of FIELD_NAME token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: com.fmr.lwc2.TestConfig["server"]->io.dropwizard.server.SimpleServerFactory["requestLog"])

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:278)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:155)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:88)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
