### ISSUE TITLE
CLOB Error in io dropwizard migrations liquibase 1.3.5

### ISSUE THREAD

**Issue by shashank-devisetty** [dropwizard/dropwizard#2434]
After upgrading io dropwizard migrations version from 1.3.2 to 1.3.5, I get the below error when I try to insert seed data for a CLOB column

ERROR [2018-07-17 10:47:20,619] liquibase.changelog.ChangeSet: Change Set migrations.xml::1::<project> failed.  Error: CLOB resource not found: []
liquibase.exception.MigrationFailedException: Migration failed for change set migrations.xml::1::<project>:
     Reason: liquibase.exception.DatabaseException: CLOB resource not found: []
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:168)
	at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:68)
	at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)

**Comment by joschi** [comment]
@shashank-devisetty Please post the complete `migrations.xml` file you're using.

**Comment by shashank-devisetty** [comment]
`<?xml version="1.0" encoding="UTF-8"?>

<databaseChangeLog
        xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
         http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">

    <changeSet id="1" author="shashank">
        <loadData file="data.csv" tableName="MY_TABLE" separator="|"/>
    </changeSet>
</databaseChangeLog>`

The below is my data.csv file
`config_id|config_name|config_value
1|fieldSet|[]
2|overdueDayLimit|6
3|notificationThreshold|300
4|assignmentClass|app.core.users.BalancedUserFormatter`

**Comment by shashank-devisetty** [comment]
@joschi Any updates reg the issue??

**Comment by nickbabcock** [comment]
Looks like you aren't the only one [with this issue](https://liquibase.jira.com/browse/CORE-3287), so since this looks to be an internal liquidbase bug, I'm going to mark this as blocked.
