### ISSUE TITLE
Failed to parse configuration at: server.requestLog; Type ch.qos.logback.access.spi.IAccessEvent not present (through reference chain: com.sri.tmctrivia.experimental.HelloWorldConfiguration["server"]->io.dropwizard.server.SimpleServerFactory["requestLog"])

### ISSUE THREAD

**Issue by rvsasseen** [dropwizard/dropwizard#2476]
I'm getting an error with dropwizard 1.3.5 that appears related to https://github.com/dropwizard/dropwizard/pull/2112. I am trying to use dropwizard with log4j2 in a larger project. I can get that to work with the example hello-world code, but it fails with the larger project. 

In the working hello-world code, I get output starting with 
$ java -cp target/dhw-1.1-SNAPSHOT.jar com.whatever.HelloWorldApplication  server hello-world.yml 
2018-08-29 15:52:13,283	Croft.local	main	 INFO	HelloWorldApplication.bootstrapLogging	Overriding bootstrapLogging() to do nothing
Overriding bootstrapLogging() to do nothing
2018-08-29 15:52:13,569	Croft.local	main	 INFO	Version.<clinit>	HV000001: Hibernate Validator null
2018-08-29 15:52:13,840	Croft.local	main	 INFO	Log.initialized	Logging initialized @1005ms to org.eclipse.jetty.util.log.Slf4jLog
2018-08-29 15:52:14,129	Croft.local	main	 INFO	SimpleServerFactory.configure	Registering jersey handler with root path prefix: /application
2018-08-29 15:52:14,130	Croft.local	main	 INFO	SimpleServerFactory.configure	Registering admin handler with root path prefix: /admin

In my larger project, which is trying to run the same code but from a much larger jar file, I get error output I'll paste below, in which the logback class not being found is ch.qos.logback.access.spi.IAccessEvent. The hello-world.yml file is the same one as from above. How can I figure out what is causing this to happen? 

I've tried looking at the mvn dependency:tree output in the two cases, but nothing unreasonable jumped out at me. The META-INF/services/io.dropwizard.logging.AppenderFactory in both jars contains:
io.dropwizard.logging.ConsoleAppenderFactory
io.dropwizard.logging.FileAppenderFactory
io.dropwizard.logging.SyslogAppenderFactory
io.dropwizard.logging.TcpSocketAppenderFactory
io.dropwizard.logging.UdpSocketAppenderFactory

$ java -cp target/whatever-1.1-SNAPSHOT-withdependencies.jar com.whatever.HelloWorldApplication server hello-world.yml
2018-08-29 16:52:18,282	Croft.local	main	 INFO	HelloWorldApplication.bootstrapLogging	Overriding bootstrapLogging() to do nothing
Overriding bootstrapLogging() to do nothing
2018-08-29 16:52:18,630	Croft.local	main	 INFO	Version.<clinit>	HV000001: Hibernate Validator null
2018-08-29 16:52:19,018	Croft.local	main	 INFO	Log.initialized	Logging initialized @1338ms to org.eclipse.jetty.util.log.Slf4jLog
io.dropwizard.configuration.ConfigurationParsingException: hello-world.yml has an error:
  * Failed to parse configuration at: server.requestLog; Type ch.qos.logback.access.spi.IAccessEvent not present (through reference chain: com.sri.tmctrivia.experimental.HelloWorldConfiguration["server"]->io.dropwizard.server.SimpleServerFactory["requestLog"])

	at io.dropwizard.configuration.ConfigurationParsingException$Builder.build(ConfigurationParsingException.java:279)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:156)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.whatever.HelloWorldApplication.main(HelloWorldApplication.java:18)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: Type ch.qos.logback.access.spi.IAccessEvent not present (through reference chain: com.sri.tmctrivia.experimental.HelloWorldConfiguration["server"]->io.dropwizard.server.SimpleServerFactory["requestLog"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1711)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:290)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:189)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:120)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:130)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:252)
	at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:155)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3984)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2276)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:127)
	... 6 more
Caused by: java.lang.TypeNotPresentException: Type ch.qos.logback.access.spi.IAccessEvent not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.ConstructorRepository.getParameterTypes(ConstructorRepository.java:94)
	at java.lang.reflect.Executable.getGenericParameterTypes(Executable.java:283)
	at java.lang.reflect.Method.getGenericParameterTypes(Method.java:283)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getParameterType(AnnotatedMethod.java:145)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getPrimaryType(POJOPropertyBuilder.java:342)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getRawPrimaryType(POJOPropertyBuilder.java:358)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.filterBeanProps(BeanDeserializerFactory.java:625)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.addBeanProps(BeanDeserializerFactory.java:495)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.buildBeanDeserializer(BeanDeserializerFactory.java:227)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerFactory.createBeanDeserializer(BeanDeserializerFactory.java:137)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer2(DeserializerCache.java:411)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createDeserializer(DeserializerCache.java:349)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCache2(DeserializerCache.java:264)
	at com.fasterxml.jackson.databind.deser.DeserializerCache._createAndCacheValueDeserializer(DeserializerCache.java:244)
	at com.fasterxml.jackson.databind.deser.DeserializerCache.findValueDeserializer(DeserializerCache.java:142)
	at com.fasterxml.jackson.databind.DeserializationContext.findContextualValueDeserializer(DeserializationContext.java:444)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDefaultImplDeserializer(TypeDeserializerBase.java:220)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:159)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:113)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:254)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:136)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:288)
	... 17 more
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.access.spi.IAccessEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 48 more

**Comment by nickbabcock** [comment]
Nothing jumps to mind other than ensuring both the requestLog and logging are marked as external. To help demonstrate the problem please post a minimal reproducible project.

**Comment by rvsasseen** [comment]
Thanks for taking a look. I am currently trying to work around this by making a separate project for this and having it use logback, instead of including it in my main project which uses log4j2. I hope to get back to this specific problem later.

**Comment by nickbabcock** [comment]
Ok no problem. Since you're moving on, I'm going to close this. Once you've tracked down the issue further, create a new issue with all the relevant info and reference this issue.

**Comment by adriansuarez** [comment]
I suspect the original poster is doing something similar to the instructions in [this page](https://www.dropwizard.io/en/latest/manual/core.html#logging) in the _Note_ section that begins with _If you don’t want to use Logback ..._

I am seeing a more benign version of the same issue on 2.0.16, which I can reproduce by simply following the instructions in that _Note_ section. The only symptom is that the following message is printed to standard error, but the server still starts up:

```
io.dropwizard.configuration.ConfigurationMetadata.$1: Type ch.qos.logback.access.spi.IAccessEvent not present
```

This occurs while Hibernate is validating the deserialized configuration at the field `server.requestLog`, which is configured with `type: external` as instructed in that _Note_ section.

It looks like the root of the problem is that `LogbackAccessRequestLogFactory` pulls in the Logback dependency, and it is also the default implementation of `RequestLogFactory`, as defined with the [`JsonTypeInfo` annotation](https://github.com/dropwizard/dropwizard/blob/05bdecbe59366d4c747aa2f0256dcd768bd6b6e6/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/RequestLogFactory.java#L12). So it is still being loaded when doing Hibernate validation on the config, even if it is not specified in the config.

This is the exception stacktrace that is getting swallowed when the message above is printed:

```
java.lang.TypeNotPresentException: Type ch.qos.logback.access.spi.IAccessEvent not present
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:117)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:125)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.visitor.Reifier.reifyTypeArguments(Reifier.java:68)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:138)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:49)
	at sun.reflect.generics.repository.MethodRepository.getReturnType(MethodRepository.java:68)
	at java.lang.reflect.Method.getGenericReturnType(Method.java:255)
	at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.getType(AnnotatedMethod.java:77)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getPrimaryType(POJOPropertyBuilder.java:341)
	at com.fasterxml.jackson.databind.introspect.POJOPropertyBuilder.getRawPrimaryType(POJOPropertyBuilder.java:365)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.removeIgnorableTypes(BeanSerializerFactory.java:707)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanProperties(BeanSerializerFactory.java:573)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:384)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:286)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:231)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:165)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1474)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1442)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:562)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4358)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4337)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:164)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:840)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:897)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4358)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4337)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:164)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:840)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:897)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4358)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4337)
	at io.dropwizard.configuration.ConfigurationMetadata.<init>(ConfigurationMetadata.java:76)
	at io.dropwizard.configuration.BaseConfigurationFactory.<init>(BaseConfigurationFactory.java:76)
	at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:29)
	at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:18)
...
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.access.spi.IAccessEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:114)
	... 51 more
```

It looks like this is doing reflection on the `LogbackAccessRequestLogFactory` methods and failing when it encounters the `IAccessEvent` type parameter, which appears in the method signatures for [`getAppenders()` and `setAppenders()`](https://github.com/dropwizard/dropwizard/blob/05bdecbe59366d4c747aa2f0256dcd768bd6b6e6/dropwizard-request-logging/src/main/java/io/dropwizard/request/logging/LogbackAccessRequestLogFactory.java#L51).

Like I said, this is relatively benign, but it is still annoying enough that I added back the "logback-access" dependency, and that silenced the error message. That's a reasonable workaround for now, but Logback's most recent stable release is from 2017 and certain scanning tools are already flagging it for known vulnerabilities, so it isn't ideal to pull it in as a dependency if it is not used.

**Comment by rvsasseen** [comment]
I can confirm that I was trying to follow the "If you don’t want to use Logback" instructions.
