### ISSUE TITLE
Jersey client leaking connections

### ISSUE THREAD

**Issue by rrusu656e74** [dropwizard/dropwizard#2658]
Hi Here,

I have an endpoint running in prod powered by dropwizard 1.3.5, Windows Server, 2016, Java 8 64 bit.
Recently started to exhaust the connection pool upstream. Here is an example of exception.

	javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
		at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:111)
		at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
		at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
		at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
		at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
		at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
		at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
		at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:437)
		at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:343)
		at com.xxxxxxxxxx.submitRequest(AccessControllerAuthorizationService.java:56)
		at com.xxxxxxxxxx.authorizeAs(AccessControllerAuthorizationService.java:34)
		at com.xxxxxxxxxx.capturedNewSetOfCredentials(BAService.java:42)
		at com.xxxxxxxxxx.lambda$OnGetImage$3(I7000sWin64.java:205)
		at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
		at java.util.concurrent.FutureTask.run(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
		at java.lang.Thread.run(Unknown Source)
	Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
		at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:313)
		at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:279)
		at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
		at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
		at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
		at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
		at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
		at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
		at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:89)

When the application boostraps it creates the `Client` and it gets reused for multiple requests. This is the code which submits the request. 

    private boolean submitRequest(Diagnostics scope, String resource, Object request) {
        try{
            Response response = client.target(serverUri)
                    .path(resource)
                    .request(MediaType.APPLICATION_JSON)
                    .accept(MediaType.APPLICATION_JSON)
                    .post(Entity.json(request));

            return response.getStatus() == 200;

        }catch (Exception exception){
            return false;
        }
    }

Checking the online DW docs did not find anything that might suggest what could be the issue. Is there anything which might cause the connections not to be released ?

Appreciate your feedback!

**Comment by rrusu656e74** [comment]
If there are any other details i need to include here, i'm happy to provide

**Comment by nickbabcock** [comment]
Are you ensuring that the response is closed?

**Comment by rrusu656e74** [comment]
Good question. And following that i think you answered my question. 

Based on https://jersey.github.io/documentation/latest/client.html#d0e5255  if you don't read the entity, then you need to close the response manually by invoking Response#close().

That's what I'm missing probably. Thank you!
