### ISSUE TITLE
Error running integration tests with 2.0.0-rc1

### ISSUE THREAD

**Issue by keirlawson** [dropwizard/dropwizard#2746]
I've tried upgrading our project to 2.0.0-rc1, however upon integration testing I'm seeing the following error:

```
java.lang.NoClassDefFoundError: Could not initialize class io.dropwizard.validation.valuehandling.GuavaOptionalValueExtractor
	at io.dropwizard.validation.BaseValidator.newConfiguration(BaseValidator.java:26)
	at io.dropwizard.jersey.validation.Validators.newConfiguration(Validators.java:33)
	at io.dropwizard.jersey.validation.Validators.newValidatorFactory(Validators.java:26)
	at io.dropwizard.setup.Bootstrap.<init>(Bootstrap.java:64)
	at io.dropwizard.testing.DropwizardTestSupport$2.<init>(DropwizardTestSupport.java:273)
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:273)
```

There is nothing obvious in my own configuration that should be causing this, and the validation dependency is present in the project and thus should be on the classpath.

**Comment by joschi** [comment]
@keirlawson Thanks for reporting this! Could you please post a minimal project to reproduce the issue?

**Comment by keirlawson** [comment]
In trying to produce a minimal example I seem to have stumbled upon what the issue was, namely I had a dependency on Hibernate validator 5.x, moving to 6.x resolved the issue.

**Comment by joschi** [comment]
@keirlawson Great, thanks for the update! 😃
