### ISSUE TITLE
NullPointerException at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations

### ISSUE THREAD

**Issue by animesh-sharama** [dropwizard/dropwizard#2830]
dropwizard-jdbi3 throws NPE when using mariaDB client.

steps to reproduce

- create a dropwizard maven project with below as dependency

```
<properties>
        <dropwizard.version>1.3.12</dropwizard.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
    </properties>

<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-core</artifactId>
            <version>${dropwizard.version}</version>
 </dependency>

<dependency>
            <groupId>org.mariadb.jdbc</groupId>
            <artifactId>mariadb-java-client</artifactId>
            <version>2.4.2</version>
        </dependency>

<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-jdbi3</artifactId>
            <version>2.0.0-rc4</version>
</dependency>
```

- try building and running the project (mvn package; java -jar.....)

The exact same config with hibernate works fine with below hibernate.
replace the dropwizard-jdbi3 dependency with hibernate, rebuild and rerun the error is gone.

```
<dependency>
            <groupId>io.dropwizard</groupId>
            <artifactId>dropwizard-hibernate</artifactId>
            <version>${dropwizard.version}</version>
</dependency>
```

stackTrace

```
java.lang.NullPointerException
        at sun.reflect.annotation.TypeAnnotationParser.mapTypeAnnotations(TypeAnnotationParser.java:356)
        at sun.reflect.annotation.AnnotatedTypeFactory$AnnotatedTypeBaseImpl.<init>(AnnotatedTypeFactory.java:139)
        at sun.reflect.annotation.AnnotatedTypeFactory.buildAnnotatedType(AnnotatedTypeFactory.java:65)
        at sun.reflect.annotation.TypeAnnotationParser.buildAnnotatedType(TypeAnnotationParser.java:79)
        at java.lang.reflect.Field.getAnnotatedType(Field.java:1170)
        at org.hibernate.validator.internal.metadata.provider.TypeAnnotationAwareMetaDataProvider.findTypeAnnotationConstraintsForMember(TypeAnnotationAwareMetaDataProvider.java:65)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.findPropertyMetaData(AnnotationMetaDataProvider.java:246)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getFieldMetaData(AnnotationMetaDataProvider.java:229)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.retrieveBeanConfiguration(AnnotationMetaDataProvider.java:137)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfiguration(AnnotationMetaDataProvider.java:125)
        at org.hibernate.validator.internal.metadata.provider.AnnotationMetaDataProvider.getBeanConfigurationForHierarchy(AnnotationMetaDataProvider.java:108)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.createBeanMetaData(BeanMetaDataManager.java:203)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getOrCreateBeanMetaData(BeanMetaDataManager.java:231)
        at org.hibernate.validator.internal.metadata.BeanMetaDataManager.getBeanMetaData(BeanMetaDataManager.java:178)
        at org.hibernate.validator.internal.engine.ValidatorImpl.buildNewLocalExecutionContext(ValidatorImpl.java:771)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraint(ValidatorImpl.java:754)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateCascadedConstraints(ValidatorImpl.java:681)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:420)
        at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:208)
        at io.dropwizard.configuration.BaseConfigurationFactory.validate(BaseConfigurationFactory.java:236)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:128)
        at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:89)
        at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:126)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:74)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:93)
```

**Comment by sleberknight** [comment]
You specified the `dropwizard.version` as `1.3.12` which is then used for all the dependencies _except_ for `dropwizard-jdbi3`, which you are using `2.0.0-rc4`. I would suggest trying it using the same version for all the dependencies, e.g. use  `1.3.12` or `2.0.0-rc4`. (Use the `dropwizard.version` property for the `dropwizard-jdbi3` dependency declaration.)
