### ISSUE TITLE
DropwizardSSLConnectionSocketFactoryTest.shouldFailDueDefaultProviderInsufficiency fails on Java 12

### ISSUE THREAD

**Issue by alexey-wg2** [dropwizard/dropwizard#2921]
`io.dropwizard.client.ssl.DropwizardSSLConnectionSocketFactoryTest#shouldFailDueDefaultProviderInsufficiency` fails on Java 12 with the  following error:
```
java.lang.AssertionError: 
Expecting code to raise a throwable.

	at io.dropwizard.client.ssl.DropwizardSSLConnectionSocketFactoryTest.shouldFailDueDefaultProviderInsufficiency(DropwizardSSLConnectionSocketFactoryTest.java:272)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:675)
	...
```

The test tries to start a server which loads `acme-weak.keystore.p12` as a part of its TLS configuration and expect it won't be started. However, in Java 12 such weak keystore doesn't  not longer cause the default Java security provider to crash.

The issue can be reproduced by using the keytool which crashes while reading the file with the following error with Java 8:
```
$keytool -v -list -storetype pkcs12 -keystore  /Users/alexey/Work/git/dropwizard/dropwizard-client/src/test/resources/stores/client/acme-weak.keystore.p12 -storepass acme2
keytool error: java.io.IOException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)
java.io.IOException: parseAlgParameters failed: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:816)
	at sun.security.pkcs12.PKCS12KeyStore.engineLoad(PKCS12KeyStore.java:2018)
	at java.security.KeyStore.load(KeyStore.java:1445)
	at sun.security.tools.keytool.Main.doCommands(Main.java:823)
	at sun.security.tools.keytool.Main.run(Main.java:366)
	at sun.security.tools.keytool.Main.main(Main.java:359)
Caused by: java.io.IOException: ObjectIdentifier() -- data isn't an object ID (tag = 48)
	at sun.security.util.ObjectIdentifier.<init>(ObjectIdentifier.java:257)
	at sun.security.util.DerInputStream.getOID(DerInputStream.java:314)
	at com.sun.crypto.provider.PBES2Parameters.engineInit(PBES2Parameters.java:267)
	at java.security.AlgorithmParameters.init(AlgorithmParameters.java:293)
	at sun.security.pkcs12.PKCS12KeyStore.parseAlgParameters(PKCS12KeyStore.java:812)
	... 5 more
```
While on Java 12 the command above works fine.

We can possibly consider negating the test for Java 12+ (my preference), or try to come up with a `.keystore` file which would always crash on the standard Java security provider but work with the Bounty castle provider used in a deferent test.

**Comment by joschi** [comment]
@alexey-wg2 Thanks for reporting this!

The test doesn't seem to fail on Java 13 (for example https://github.com/dropwizard/dropwizard/runs/338915521).
Could this be a problem with the specific JDK you're using on your machine?
