### ISSUE TITLE
Jersey failed to start in JRE11

### ISSUE THREAD

**Issue by chenziliang** [dropwizard/dropwizard#3058]
Hi,

When i changed my JVM runtime to Oracle JRE 11, my application failed to start with the following exception. Dropwizard lib version is 1.3.17. May you shed some light here ? Would like to understand if 1.3.37 supports JRE11 as well ?

Thanks !

```
javax.servlet.ServletException: io.dropwizard.jersey.setup.JerseyServletContainer-6cc52eb1@5dcca37f==io.dropwizard.jersey.setup.JerseyServletContainer,jsp=null,order=1,inst=false,async=true
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:692)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:428)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:750)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:744)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:852)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:278)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:101)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:119)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:406)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:256)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:167)
	at org.eclipse.jetty.server.Server.start(Server.java:418)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:113)
	at org.eclipse.jetty.server.Server.doStart(Server.java:382)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	...
Caused by: java.lang.IllegalArgumentException
	at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:171)
	at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:153)
	at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:425)
	at org.glassfish.jersey.server.internal.scanning.AnnotationAcceptingListener.process(AnnotationAcceptingListener.java:170)
	at org.glassfish.jersey.server.ResourceConfig.scanClasses(ResourceConfig.java:915)
	at org.glassfish.jersey.server.ResourceConfig._getClasses(ResourceConfig.java:869)
	at org.glassfish.jersey.server.ResourceConfig.getClasses(ResourceConfig.java:775)
	at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1206)
	at org.glassfish.jersey.server.ResourceConfig$RuntimeConfig.<init>(ResourceConfig.java:1178)
	at org.glassfish.jersey.server.ResourceConfig.createRuntimeConfig(ResourceConfig.java:1174)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:345)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:392)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:177)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:369)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:671)
	... 53 more
```

**Comment by chenziliang** [comment]
Alright, from `at jersey.repackaged.org.objectweb.asm.ClassReader.<init>(ClassReader.java:171)`, i got the following code. Look like 1.3.17 which has jersey-server-2.25.1 by default doesn't support JRE11 yet ?
```
    public ClassReader(final byte[] b, final int off, final int len) {
        this.b = b;
        // checks the class version
        // added "support" for java 9 compiled classes
        if (readShort(off + 6) > Opcodes.V9) {
            throw new IllegalArgumentException();
        }
```

**Comment by chenziliang** [comment]
Is it possible to package a different jersey-server for dropwizard 1.3.17 ?

**Comment by joschi** [comment]
@chenziliang Please upgrade to Dropwizard 2.0.0 if you want to use Java 11.

**Comment by brentryan** [comment]
@joschi is that a new requirement? We’ve been running on open JRE 11 for the past year and haven’t run into this. Just curious on what changed or causes this? Maybe we’ve just been lucky with certain code paths?

**Comment by joschi** [comment]
@brentryan Maybe you've been lucky or @chenziliang has been unlucky. 😉

**Comment by chenziliang** [comment]
@brentryan may I ask what version of dropwizard and jersey packages are you using ? Would like to try it out with the same version.

@joschi may I ask if there is a migration doc, look like there are breaking API changes in 2.0.0 ?

Thanks so much!

**Comment by joschi** [comment]
> may I ask if there is a migration doc, look like there are breaking API changes in 2.0.0 ?

@chenziliang Yes, there is: https://www.dropwizard.io/en/release-2.0.x/manual/upgrade-notes/upgrade-notes-2_0_x.html

**Comment by chenziliang** [comment]
@joschi Awesome. Thanks !

**Comment by reneploetz** [comment]
Dropwizard 1.3.17 might work for you with Java 11 if you are not relying on jersey classpath scanning. This means you need to register all jersey components directly via io.dropwizard.setup.Environment.jersey().register() instead of using packages().
(We tested this internally for a bit only, so your mileage may vary.)

As Dropwizard has a compile dependency on specific jersey versions and because jersey 2.25.1 -> 2.26 is breaking a lot of APIs you will likely not be able to use a different version.

**Comment by chenziliang** [comment]
Thanks @reneploetz

**Comment by brentryan** [comment]
@chenziliang Today we run 1.3.16 and haven't had issues. But we don't typically use any of the classpath scanning stuff and do rely on registering components directly.

**Comment by chenziliang** [comment]
Thanks folks. Closing it.
