### ISSUE TITLE
CDI Dependency Injection is broken by InjectValidatorFeature

### ISSUE THREAD

**Issue by t3hk0d3** [dropwizard/dropwizard#3225]
CDI2/Weld3 DI is broken when using Dropwizard

I've spent quite some time investigating this issue, and apparently it is coming from `InjectValidatorFeature`

The reason is that HK2 uses `IMMEDIATE` strategy by default for Service registration (https://github.com/eclipse-ee4j/jersey/blob/master/inject/hk2/src/main/java/org/glassfish/jersey/inject/hk2/Hk2InjectionManagerFactory.java#L89)

However CDI does not offer immediate service registration (you need to register all services and create `BeanManager`, and only after that you can instantiate new services).

For that reason, there is a method call `InjectionManager.completeRegistration`, which is called  (https://github.com/eclipse-ee4j/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/ApplicationHandler.java#L347) only after 
Jersey Features are configured (https://github.com/eclipse-ee4j/jersey/blob/master/core-server/src/main/java/org/glassfish/jersey/server/ApplicationHandler.java#L328)

So If CDI or HK2 (with `DELAYED` strategy) InjectionManagers are used, an application will throw an error during initialization.

You can test it yourself by adding this to your `pom.xml`:

```
<dependency>
   <groupId>org.glassfish.jersey.inject</groupId>
   <artifactId>jersey-cdi2-se</artifactId>
   <version>2.30</version>
</dependency>
```

Exception stacktrace:
```
java.lang.NullPointerException
	at io.dropwizard.validation.InjectValidatorFeature.configure(InjectValidatorFeature.java:33)
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:702)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:627)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	at javax.servlet.GenericServlet.init(GenericServlet.java:203)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:594)
```

**Comment by sblour2020** [comment]
Please help.
I have this issue and I have added jersey-cdi2-se.jar but still getting exactl these stacktrace error.
I am pasting all the error message here. 

ERROR [2020-08-17 17:33:16,923] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.NullPointerException: null
! at io.dropwizard.validation.InjectValidatorFeature.configure(InjectValidatorFeature.java:33)
! at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:713)
! at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:632)
! at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
! at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
! at org.glassfish.jersey.server.ApplicationHandler$$Lambda$352/436399072.call(Unknown Source)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
! at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
! at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
! at javax.servlet.GenericServlet.init(GenericServlet.java:203)
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
! ... 51 common frames omitted
! Causing: javax.servlet.ServletException: io.dropwizard.jersey.setup.JerseyServletContainer-2da5fdc@418b3aa1==io.dropwizard.jersey.setup.JerseyServletContainer,jsp=null,order=1,inst=true,async=true
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:620)
! at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:413)
! at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:767)
! at org.eclipse.jetty.servlet.ServletHandler$$Lambda$314/739241900.accept(Unknown Source)
! at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$317/1915196011.accept(Unknown Source)
! at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
! at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
! at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
! at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
! at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
! at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:855)
! at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:110)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at io.dropwizard.jetty.ContextRoutingHandler.doStart(ContextRoutingHandler.java:43)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:425)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:255)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.server.Server.start(Server.java:408)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.Server.doStart(Server.java:372)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at edu.mayo.qia.pacs.Notion.main(Notion.java:23)
INFO  [2020-08-17 17:33:16,927] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@4f82248f{/,null,UNAVAILABLE}
javax.servlet.ServletException: io.dropwizard.jersey.setup.JerseyServletContainer-2da5fdc@418b3aa1==io.dropwizard.jersey.setup.JerseyServletContainer,jsp=null,order=1,inst=true,async=true
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:620)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:413)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:767)
	at org.eclipse.jetty.servlet.ServletHandler$$Lambda$314/739241900.accept(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$317/1915196011.accept(Unknown Source)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:855)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:110)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at io.dropwizard.jetty.ContextRoutingHandler.doStart(ContextRoutingHandler.java:43)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:425)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:255)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at edu.mayo.qia.pacs.Notion.main(Notion.java:23)
Caused by: java.lang.NullPointerException
	at io.dropwizard.validation.InjectValidatorFeature.configure(InjectValidatorFeature.java:33)
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:713)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:632)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.server.ApplicationHandler$$Lambda$352/436399072.call(Unknown Source)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	at javax.servlet.GenericServlet.init(GenericServlet.java:203)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
	... 51 more
INFO  [2020-08-17 17:33:16,942] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler: Shutting down ExecutorService 'taskScheduler'
