### ISSUE TITLE
Request log async logging appender worker threads not stopped

### ISSUE THREAD

**Issue by oeddyo** [dropwizard/dropwizard#3226]
This is the same issue as seen in 
https://github.com/dropwizard/dropwizard/issues/1994

But somehow got closed.

Long story short I'm using a testing helper which detects leaked threads and it seems the logging thread is not stopped correctly:

```
1 thread leaked from SUITE scope at com.kalasearch.restful.dropwizard.MyTEst: 
   1) Thread[id=22, name=AsyncAppender-Worker-async-console-appender, state=WAITING, group=TGRP-MyTEst]
        at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
        at java.base@11.0.5/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417)
        at app//ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:289)
com.carrotsearch.randomizedtesting.ThreadLeakError: 1 thread leaked from SUITE scope at com.kalasearch.restful.dropwizard.MyTEst: 
   1) Thread[id=22, name=AsyncAppender-Worker-async-console-appender, state=WAITING, group=TGRP-MyTEst]
        at java.base@11.0.5/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.5/java.util.concurrent.locks.LockSupport.park(LockSupport.java:194)
        at java.base@11.0.5/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2081)
        at java.base@11.0.5/java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:417)
        at app//ch.qos.logback.core.AsyncAppenderBase$Worker.run(AsyncAppenderBase.java:289)
	at __randomizedtesting.SeedInfo.seed([A1098A089DAFEB54]:0)
```

**Comment by alkoclick** [comment]
Can you check if your appender is actually an instance of AsyncAppender or not? DefaultLoggingFactory has some pretty weird behavior overall, it doesn't close the appenders at all, it just lets them "flush" themselves. We're also experiencing issues with this functionality

**Comment by joschi** [comment]
@oeddyo Which version of Dropwizard are you using?

**Comment by natan-abolafya** [comment]
This still happens on 2.0.18
Minimally, I reproduced this getting dropwizard-example and running the Integration test over and over using Intellij's "Repeat" feature.
![image](https://user-images.githubusercontent.com/64091305/148802696-d87bc1d7-15db-430b-a001-d9a7f5a48a13.png)

Here is the thread count going nuts on VisualVM while the tests are going on
![image](https://user-images.githubusercontent.com/64091305/148802782-f694f0bc-bbab-40f0-ba05-ff8b2ae23fa7.png)
And the culprit threads' names:
![image](https://user-images.githubusercontent.com/64091305/148802900-985b7a7a-ee9b-443f-aa9a-50c9c1ba7c4c.png)


It can be worked around by removing the request logger from the test configuration.
https://stackoverflow.com/questions/23505403/turning-off-requestlog

**Comment by joschi** [comment]
@natan-abolafya Thanks for gathering this information! We'll see what we can do about it.
@oeddyo Thanks for reporting this issue!

**Comment by zUniQueX** [comment]
I think, I've now found the cause of this issue. The `start` and `stop` methods of the `RequestLogImpl` seem to be never called. The async appender for the request logging isn't added to any logger but rather to the `AppenderAttachableImpl` of the `RequestLogImpl` directly. Therefore, if the logging is reset on application shutdown, the thread of the async appender in the request log isn't stopped because the `stop` method of the request log isn't invoked.

If the `RequestLogImpl` is manually stopped at application shutdown, the threads are correctly released.

The request log implementation should be managed automatically, as it is [registered as a bean](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-core/src/main/java/io/dropwizard/server/AbstractServerFactory.java#L686), but somehow it won't. I'll investigate this further and post the results here.
