### ISSUE TITLE
JUnit 5 test with HttpSession fails with DropwizardExtensionsSupport

### ISSUE THREAD

**Issue by brentryan** [dropwizard/dropwizard#3340]
We came across a scenario where we wanted to write a unit test for `@Session HttpSession session` being injected into a resource.

We were trying to mimic the behavior of DockerIntegrationTest.java which is included with dropwizard-example project. You can mimic the failure by simply adding `@Session HttpSession session` to `HelloWorldResource` and re-running the test.

It was obvious if this was a limitation in the underlying test container being used here or if there was a way to enable session support in a test.

Here's the output of the error:
```
ERROR [2020-06-19 21:41:38,961] io.dropwizard.jersey.errors.IllegalStateExceptionMapper: Error handling a request: 77e5c65c7de94fa7
! java.lang.IllegalStateException: No SessionManager
! at org.eclipse.jetty.server.Request.getSession(Request.java:1605)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.base/java.lang.reflect.Method.invoke(Method.java:566)
! at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1268)
! at org.jvnet.hk2.internal.MethodInterceptorImpl.internalInvoke(MethodInterceptorImpl.java:85)
! at org.jvnet.hk2.internal.MethodInterceptorImpl.invoke(MethodInterceptorImpl.java:101)
! at org.jvnet.hk2.internal.MethodInterceptorInvocationHandler.invoke(MethodInterceptorInvocationHandler.java:39)
! at com.sun.proxy.$Proxy110.getSession(Unknown Source)
! at io.dropwizard.jersey.sessions.HttpSessionFactory.provide(HttpSessionFactory.java:22)
! at io.dropwizard.jersey.sessions.SessionFactoryProvider.lambda$createValueProvider$0(SessionFactoryProvider.java:40)
! at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
! at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:64)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:469)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:391)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:80)
! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:253)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:232)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:50)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1631)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1618)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:549)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1369)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:489)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1284)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:249)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:767)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:173)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at org.eclipse.jetty.server.Server.handle(Server.java:501)
! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:556)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:272)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:135)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
! at java.base/java.lang.Thread.run(Thread.java:834)
127.0.0.1 - - [19/Jun/2020:21:41:38 +0000] "GET /hello-world?name=Dr.+IntegrationTest HTTP/1.1" 500 110 "-" "Jersey/2.31 (HttpUrlConnection 11.0.4)" 31
INFO  [2020-06-19 21:41:39,020] org.eclipse.jetty.server.AbstractConnector: Stopped application@69d1ad64{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
INFO  [2020-06-19 21:41:39,022] org.eclipse.jetty.server.AbstractConnector: Stopped admin@458b4487{HTTP/1.1, (http/1.1)}{0.0.0.0:0}
INFO  [2020-06-19 21:41:39,024] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@29dcad7e{/,null,UNAVAILABLE}
INFO  [2020-06-19 21:41:39,030] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@350ede1{/,null,UNAVAILABLE}
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 43.681 s <<< FAILURE! - in com.example.helloworld.DockerIntegrationTest
testHelloWorld  Time elapsed: 27.259 s  <<< ERROR!
javax.ws.rs.InternalServerErrorException: HTTP 500 Internal Server Error
	at com.example.helloworld.DockerIntegrationTest.testHelloWorld(DockerIntegrationTest.java:56)

```

Any thoughts on how it might be possible to test sessions like this?

I noticed that HttpSessionFactoryTest.java tests the built in dropwizard session handler code differently but it wasn't obvious to me why it wouldn't just work with DropwizardExtensionsSupport.

**Comment by joschi** [comment]
Please try using the Grizzly or Jetty-based test containers for being able to inject "real" sessions.

https://www.dropwizard.io/en/latest/manual/testing.html#test-containers

**Comment by brentryan** [comment]
That may work with default @Session behavior. However, once you've had to customize session handler code so that sessions can be stored in couchbase and we have a dropwizard bundle for enabling this behavior, we'd like to be able to test this using DropwizardAppExtension. The primary reason for using DropwizardAppExtension is because the application bundle has all the code to init the custom session handling code. If I use the ResourceExtension then I don't see any handy way to customize this with the tests.

I essentially need a way to initialize a custom session handler and call: 

```
environment.servlets().setSessionHandler(sessionHandler);
```

We can stick to just using fully deployed integration tests for this but I was hoping to be able to wrap this in a test that didn't require a fully deployed test service in order to test it.

**Comment by joschi** [comment]
After looking into this a bit more, the issue is that the Jersey test framework (in-memory, Grizzly, Jetty) doesn't set up a full Servlet-environment but is using the respective handler-functionality of each test container instead.

Without a Servlet-environment, it's not possible to create an `javax.servlet.http.HttpSession` instance or to add another session handler.

To address this issue, we'd have to provide a specific [Jersey test container](https://eclipse-ee4j.github.io/jersey.github.io/documentation/2.33/test-framework.html#d0e17757) which creates a proper Servlet-environment.

**Comment by zUniQueX** [comment]
@joschi Actually your linked doc article explains that Grizzly supports this with the `GrizzlyWebTestContainerFactory`.

**Comment by zUniQueX** [comment]
I just recognized that I misunderstood the question. When using `DropwizardAppExtension` you don't depend on the Jersey test framework, but instead on a lightweight Dropwizard application.

Actually you can call the `getEnvironment()` method on your `DropwizardAppExtension` field to do what you already explained. But at that point the server has already started and you cannot register a `SessionHandler` any more. To do it before the server starts, you'll need a `ServiceListener`.
When adding the following code to the `IntegrationTest`, I get the session injected:
```java
static {
    APP.addListener(new DropwizardAppExtension.ServiceListener<>() {
        @Override
        public void onRun(HelloWorld Configuration c, Environment e, DropwizardAppExtension<HelloWorldConfiguration> rule) throws Exception {
            e.servlets().setSessionHandler(new org.eclipse.jetty.server.session.SessionHandler());
        }
    });
}
```

I just wondered, why this doesn't work correctly in the default configuration. I just tested it with a "normal" Dropwizard application and experienced the same behaviour.

@joschi Should we do anything about this?

**Comment by zUniQueX** [comment]
@brentryan did the solution with the `ServiceListener` work out fou you?

In the referenced PR we have discussed session support and ended up with not enabling it by default.

**Comment by zUniQueX** [comment]
@brentryan Any update on this? If not, I'd assume this isn't a problem any more and would close this.

**Comment by brentryan** [comment]
We wound up living with full fledged integration tests instead. We could not get a unit test to work properly.

**Comment by zUniQueX** [comment]
Okay, then I'll convert this issue to a discussion. As the `ServiceListener` generally provides a way to archive setting a `SessionHandler`, I don't see the need to change something in the framework about this. But maybe the discussion will help others tackling a bug like this.

If you have an idea about how we can improve this in any way to help you and others bringing a unit test for this, maybe you could provide this idea for a future integration.
