### ISSUE TITLE
Application run time error after upgraded sun.jsersey to glassfish.jersey and upgraded dropwizard

### ISSUE THREAD

**Issue by sblour2020** [dropwizard/dropwizard#3418]
Please help.
Server Jetty cannot start after upgraded sun.jsersey to glassfish.jersey and upgraded dropwizard-0.7.1 to 2.0.11
Althoug I have added jersey-cdi2-se.jar but still getting these stacktrace error.
```
ERROR [2020-08-17 17:33:16,923] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.NullPointerException: null
! at io.dropwizard.validation.InjectValidatorFeature.configure(InjectValidatorFeature.java:33)
! at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:713)
! at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:632)
! at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
! at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
! at org.glassfish.jersey.server.ApplicationHandler$$Lambda$352/436399072.call(Unknown Source)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
! at org.glassfish.jersey.server.ApplicationHandler.(ApplicationHandler.java:259)
! at org.glassfish.jersey.servlet.WebComponent.(WebComponent.java:311)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
! at javax.servlet.GenericServlet.init(GenericServlet.java:203)
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
! ... 51 common frames omitted
! Causing: javax.servlet.ServletException: io.dropwizard.jersey.setup.JerseyServletContainer-2da5fdc@418b3aa1==io.dropwizard.jersey.setup.JerseyServletContainer,jsp=null,order=1,inst=true,async=true
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:620)
! at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:413)
! at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:767)
! at org.eclipse.jetty.servlet.ServletHandler$$Lambda$314/739241900.accept(Unknown Source)
! at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$317/1915196011.accept(Unknown Source)
! at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
! at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
! at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
! at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
! at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
! at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
! at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:855)
! at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:110)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at io.dropwizard.jetty.ContextRoutingHandler.doStart(ContextRoutingHandler.java:43)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:425)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:255)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.server.Server.start(Server.java:408)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.Server.doStart(Server.java:372)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at edu.mayo.qia.pacs.Notion.main(Notion.java:23)
INFO [2020-08-17 17:33:16,927] org.eclipse.jetty.server.handler.ContextHandler: Stopped i.d.j.MutableServletContextHandler@4f82248f{/,null,UNAVAILABLE}
javax.servlet.ServletException: io.dropwizard.jersey.setup.JerseyServletContainer-2da5fdc@418b3aa1==io.dropwizard.jersey.setup.JerseyServletContainer,jsp=null,order=1,inst=true,async=true
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:620)
at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:413)
at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:767)
at org.eclipse.jetty.servlet.ServletHandler$$Lambda$314/739241900.accept(Unknown Source)
at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$317/1915196011.accept(Unknown Source)
at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:791)
at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:855)
at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:110)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at io.dropwizard.jetty.ContextRoutingHandler.doStart(ContextRoutingHandler.java:43)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:425)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:255)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
at org.eclipse.jetty.server.Server.start(Server.java:408)
at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
at org.eclipse.jetty.server.Server.doStart(Server.java:372)
at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
at io.dropwizard.cli.Cli.run(Cli.java:78)
at io.dropwizard.Application.run(Application.java:94)
at edu.mayo.qia.pacs.Notion.main(Notion.java:23)
Caused by: java.lang.NullPointerException
at io.dropwizard.validation.InjectValidatorFeature.configure(InjectValidatorFeature.java:33)
at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:713)
at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:632)
at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
at org.glassfish.jersey.server.ApplicationHandler$$Lambda$352/436399072.call(Unknown Source)
at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
at org.glassfish.jersey.server.ApplicationHandler.(ApplicationHandler.java:259)
at org.glassfish.jersey.servlet.WebComponent.(WebComponent.java:311)
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
at javax.servlet.GenericServlet.init(GenericServlet.java:203)
at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
... 51 more
INFO [2020-08-17 17:33:16,942] org.springframework.scheduling.concurrent.ThreadPoolTaskScheduler: Shutting down ExecutorService 'taskScheduler'
```

**Comment by joschi** [comment]
Please check the upgrade notes for the versions you've covered in your upgrade:
https://www.dropwizard.io/en/latest/manual/upgrade-notes.html

There might be some incompatible libraries in your Dropwizard project which pull in incompatible dependencies.

**Comment by sblour2020** [comment]
Thank you. One more question, does the dropwizard.2x jetty uses embadded jetty also? I am using jetty 9.4xx now. I am not sure it's embedded or not. If not, should I add this server in Eclipse and start it before running the application? Best.

**Comment by sblour2020** [comment]
Also, where I can download the io.dropwizard-dependencies? The Maven Repository doesn't have it.

**Comment by joschi** [comment]
> One more question, does the dropwizard.2x jetty uses embadded jetty also?

Yes, Dropwizard 2.x is also embedding Jetty. You do not have to set it up explicitly and deploy a WAR archive in it.

> Also, where I can download the io.dropwizard-dependencies? The Maven Repository doesn't have it.

https://search.maven.org/artifact/io.dropwizard/dropwizard-dependencies

**Comment by sblour2020** [comment]
After matched completely all dependencies with droqwizard 2.012, hibernate 5.4.18, jetty 9.4.30xx, ... still getting same issue that I've seen before. Seraching Google is not getting me a proper anser. Please help. 

java.util.ServiceConfigurationError: org.hibernate.integrator.spi.Integrator: Provider org.jadira.usertype.dateandtime.joda.integrator.UserTypeJodaTimeHibernateIntegrator could not be instantiated
	at java.util.ServiceLoader.fail(Unknown Source)
	at java.util.ServiceLoader.access$100(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.nextService(Unknown Source)
	at java.util.ServiceLoader$LazyIterator.next(Unknown Source)
	at java.util.ServiceLoader$1.next(Unknown Source)
	at org.hibernate.boot.registry.classloading.internal.AggregatedServiceLoader$ClassPathOnlyAggregatedServiceLoader.getAll(AggregatedServiceLoader.java:108)
	at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.loadJavaServices(ClassLoaderServiceImpl.java:251)
	at org.hibernate.integrator.internal.IntegratorServiceImpl.<init>(IntegratorServiceImpl.java:40)
	at org.hibernate.boot.registry.BootstrapServiceRegistryBuilder.build(BootstrapServiceRegistryBuilder.java:224)
	at io.dropwizard.hibernate.SessionFactoryFactory.buildSessionFactory(SessionFactoryFactory.java:76)
	at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:51)
	at io.dropwizard.hibernate.SessionFactoryFactory.build(SessionFactoryFactory.java:41)
	at io.dropwizard.hibernate.HibernateBundle.run(HibernateBundle.java:74)
	at io.dropwizard.setup.Bootstrap.run(Bootstrap.java:199)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at edu.mayo.qia.pacs.Notion.main(Notion.java:23)
Caused by: java.lang.NoClassDefFoundError: org/jadira/usertype/spi/shared/AbstractParameterizedTemporalUserType
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(Unknown Source)
	at java.security.SecureClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.defineClass(Unknown Source)
	at java.net.URLClassLoader.access$100(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.net.URLClassLoader$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at org.jadira.usertype.dateandtime.joda.integrator.UserTypeJodaTimeHibernateIntegrator.<clinit>(UserTypeJodaTimeHibernateIntegrator.java:60)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.lang.Class.newInstance(Unknown Source)
	... 17 more
Caused by: java.lang.ClassNotFoundException: org.jadira.usertype.spi.shared.AbstractParameterizedTemporalUserType
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 35 more

**Comment by sblour2020** [comment]
part of dependencies of dropwizard, I have joda-time-2.10.6,  userType.core-7.0.0.CR1. Then I added userType.spi.6.0.1.GA  needed by hibernate.

**Comment by sblour2020** [comment]
I removed the org.jadira.userType.spi.6.0.1.GA, added org.jadira.userType.spi.70.0.CR1. I passed the error. Now getting this error:

java.lang.NoClassDefFoundError: org/glassfish/jersey/server/validation/internal/InjectingConstraintValidatorFactory
	at io.dropwizard.validation.InjectValidatorFeature.configure(InjectValidatorFeature.java:32)
	at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:713)
	at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:632)
	at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:823)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:328)
	at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:293)
	at org.glassfish.jersey.server.ApplicationHandler$$Lambda$377/319061309.call(Unknown Source)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:292)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:259)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
	at javax.servlet.GenericServlet.init(GenericServlet.java:244)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:602)
	at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:413)
	at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:749)
	at org.eclipse.jetty.servlet.ServletHandler$$Lambda$326/1948456514.accept(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator$$Lambda$329/1374962590.accept(Unknown Source)
	at java.util.stream.SortedOps$SizedRefSortingSink.end(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.ReferencePipeline$Head.forEach(Unknown Source)
	at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:773)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:360)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:844)
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:275)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:110)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at io.dropwizard.jetty.ContextRoutingHandler.doStart(ContextRoutingHandler.java:43)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:425)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:255)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:408)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
	at org.eclipse.jetty.server.Server.doStart(Server.java:372)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at edu.mayo.qia.pacs.Notion.main(Notion.java:23)
Caused by: java.lang.ClassNotFoundException: org.glassfish.jersey.server.validation.internal.InjectingConstraintValidatorFactory
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 68 more

**Comment by joschi** [comment]
> part of dependencies of dropwizard, I have joda-time-2.10.6, org.jadira..userType.core-7.0.0.CR1. Then I added org.jadira.userType.spi.6.0.1.GA needed by hibernate.

You added an incompatible version of `org.jadira.userType.spi`. In fact, you shouldn't add this dependency manually at all.
