### ISSUE TITLE
NPE with OptionalDouble

### ISSUE THREAD

**Issue by edovale** [dropwizard/dropwizard#3430]
This happens on DW v: 2.0.9

When using a @BeanParam object with an OptionalDouble field in it. If the value is not sent in the request the following error is produced. 

It seems to me that the possibility of a null value is being overseen here. 

```
Caused by: java.lang.NullPointerException
	at java.base/jdk.internal.math.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1838)
	at java.base/jdk.internal.math.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
	at java.base/java.lang.Double.parseDouble(Double.java:549)
	at io.dropwizard.jersey.optional.OptionalDoubleParamConverterProvider$OptionalDoubleParamConverter.fromString(OptionalDoubleParamConverterProvider.java:50)
	at io.dropwizard.jersey.optional.OptionalDoubleParamConverterProvider$OptionalDoubleParamConverter.fromString(OptionalDoubleParamConverterProvider.java:32)
	at org.glassfish.jersey.server.internal.inject.AbstractParamValueExtractor.convert(AbstractParamValueExtractor.java:116)
	at org.glassfish.jersey.server.internal.inject.AbstractParamValueExtractor.fromString(AbstractParamValueExtractor.java:107)
	at org.glassfish.jersey.server.internal.inject.SingleValueExtractor.extract(SingleValueExtractor.java:61)
	at org.glassfish.jersey.server.internal.inject.QueryParamValueParamProvider$QueryParamValueProvider.apply(QueryParamValueParamProvider.java:78)
```

**Comment by edovale** [comment]
Thanks @joschi for looking into this so quickly!!
