### ISSUE TITLE
OutOfMemoryError with v2.0.14 when processing configuration files

### ISSUE THREAD

**Issue by peetzen** [dropwizard/dropwizard#3528]
After upgrading from Dropwizard `v2.0.13` to `v2.0.14` the application no longer starts. Instead a `java.lang.OutOfMemoryError` occurs. 

The root cause seems to be a method within my configuration file that returns an `ObjectMapper`. Looking into `ConfigurationMetadata:117` it is obvious that the `currentPrefix` grows beyond the actual configuration, eg. `currentPrefix = services.fancy-service.mapper.serializationConfig.defaultPropertyInclusion`.

```java
@Getter
public class FancyServiceClientConfiguration extends JerseyClientConfiguration implements CustomMapperAware {

    private URI uri;
    private String username;
    private String password;

    @Override
    public ObjectMapper getMapper() {
        return new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES)
            .setSerializationInclusion(JsonInclude.Include.NON_ABSENT)
            // using serialization/deserialization on property names only
            .setVisibility(PropertyAccessor.ALL, JsonAutoDetect.Visibility.ANY)
            .setVisibility(PropertyAccessor.FIELD, JsonAutoDetect.Visibility.ANY);
    }
}
```

Exception:
```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOfRange(Arrays.java:4030)
	at java.base/java.lang.StringLatin1.newString(StringLatin1.java:715)
	at java.base/java.lang.StringBuilder.toString(StringBuilder.java:448)
	at io.dropwizard.configuration.ConfigurationMetadata.access$184(ConfigurationMetadata.java:48)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:133)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:839)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:864)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4062)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4041)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:145)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:839)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:864)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4062)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4041)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:145)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:839)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:864)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4062)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4041)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:145)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:839)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:864)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4062)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4041)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:145)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:839)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:864)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)

```

**Comment by joschi** [comment]
@peetzen Thanks for reporting this!

We will fix this bug in Dropwizard 2.0.15.

**Comment by peetzen** [comment]
@joschi Great support! Thanks for fixing it immediately!

**Comment by joschi** [comment]
@peetzen You're welcome!

You might also want to add `@JsonIgnore` to the getters or fields in your configuration classes which _should not_ serve as actual configuration settings, such as the getter for `ObjectMapper`.

**Comment by peetzen** [comment]
Thanks for the hint. I actually added `@JsonIgnore` annotation in the meantime. I can confirm it is working.
