### ISSUE TITLE
DropwizardExtensionSupport multiple extensions cannot be ordered

### ISSUE THREAD

**Issue by jaredculp** [dropwizard/dropwizard#3549]
I'd like to be able to set up a stub DropwizardClientExtension to mock an upstream service that my dropwizard app is dependent on. This was possible in junit4 but does not appear possible in junit5.

  ```
  @Path("/")
  public static final class Resource {
    @GET
    public Response response() {
      return Response.ok().build();
    }
  }
  public static final DropwizardClientExtension UPSTREAM = new DropwizardClientExtension(new Resource());

  public static final DropwizardAppExtension<Configuration> APP =
      new DropwizardAppExtension<>(
          Application.class,
          ResourceHelpers.resourceFilePath("configuration.yml"),
          ConfigOverride.config("dependentServiceUrl", () -> UPSTREAM.baseUri().toString()));
```

This fails with a NPE:
```
java.lang.RuntimeException: java.lang.NullPointerException

	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:63)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:355)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:355)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:77)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
	Suppressed: java.lang.RuntimeException: java.lang.NullPointerException
		at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.afterAll(DropwizardExtensionsSupport.java:39)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$13(ClassBasedTestDescriptor.java:421)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeAfterAllCallbacks$14(ClassBasedTestDescriptor.java:421)
		at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeAfterAllCallbacks(ClassBasedTestDescriptor.java:421)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:213)
		at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.after(ClassBasedTestDescriptor.java:77)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:145)
		at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
		at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:145)
		... 27 more
```

In junit4 we could use a rule chain in order to specify the order of these dependencies; however adding `@Order` to these two fields does not appear to work.

**Comment by jaredculp** [comment]
I am able to work around it with these two classes:

```
package com.oracle.ugbu.opower.her3.test;

import io.dropwizard.Application;
import io.dropwizard.Configuration;
import io.dropwizard.testing.ConfigOverride;
import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

public class DropwizardAppExtension<C extends Configuration> extends
    io.dropwizard.testing.junit5.DropwizardAppExtension<C> implements BeforeAllCallback,
    AfterAllCallback {

  public DropwizardAppExtension(Class<? extends Application<C>> applicationClass,
      String resourceFilePath, ConfigOverride... configOverrides) {
    super(applicationClass, resourceFilePath, configOverrides);
  }

  @Override
  public void beforeAll(ExtensionContext context) throws Exception {
    super.before();
  }

  @Override
  public void afterAll(ExtensionContext context) throws Exception {
    super.after();
  }
}
```

```
package com.oracle.ugbu.opower.her3.test;

import org.junit.jupiter.api.extension.AfterAllCallback;
import org.junit.jupiter.api.extension.BeforeAllCallback;
import org.junit.jupiter.api.extension.ExtensionContext;

public class DropwizardClientExtension extends
    io.dropwizard.testing.junit5.DropwizardClientExtension implements BeforeAllCallback,
    AfterAllCallback {

  public DropwizardClientExtension(Object... resources) {
    super(resources);
  }

  @Override
  public void beforeAll(ExtensionContext context) {
    try {
      super.before();
    } catch (Throwable throwable) {
      throw new RuntimeException(throwable);
    }
  }

  @Override
  public void afterAll(ExtensionContext context) {
    super.after();
  }
}
```

and changing the snippet above to no longer use `@ExtendWith(DropwizardExtensionSupport.class)` and instead:
```
@RegisterExtension
@Order(1)
public static final DropwizardClientExtension UPSTREAM = new DropwizardClientExtension(
    new Object() {
      @POST
      @Path("/foo")
     Response compose() {
        return javax.ws.rs.core.Response.ok().build();
      }
    });

@RegisterExtension
@Order(2)
public static final DropwizardAppExtension<Configuration> APP =
    new DropwizardAppExtension<>(
        Application.class,
        ResourceHelpers.resourceFilePath("configuration.yml"),
        ConfigOverride.config("dependentServiceUrl", () -> UPSTREAM.baseUri().toString()));
```

Is there a reason that the dropwizard extensions don't implement the junit5 interfaces directly like this?
