### ISSUE TITLE
NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener

### ISSUE THREAD

**Issue by beena-yatin-kanyal** [dropwizard/dropwizard#3554]
We are using the `dropwizard-core` jar version 1.3.27 and getting the `NoClassDefFoundError` while running one of our services. Can you please take a look and suggest?
```
java.lang.NoClassDefFoundError: javax/servlet/http/HttpSessionIdListener
	at org.eclipse.jetty.server.handler.ContextHandler.<clinit>(ContextHandler.java:121)
	at io.dropwizard.setup.Environment.<init>(Environment.java:69)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:37)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at com.myconnector.main.MyConnector.main(MyConnector.java:58)
Caused by: java.lang.ClassNotFoundException: javax.servlet.http.HttpSessionIdListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 7 more

Process finished with exit code 1
```

**Comment by joschi** [comment]
Please share the POM file(s) of your project and the output of `mvn dependency:tree`.

**Comment by beena-yatin-kanyal** [comment]
Thank @joschi. Does this mean that there will be no further developments in the Dropwizard 1.x series? Also, I was able to resolve the above issues by adding an exclusion for the `javax.servlet-api` jar inside the dependency - `jersey-test-framework-provider-grizzly2`

```
<dependency>
	<groupId>org.glassfish.jersey.test-framework.providers</groupId>
	<artifactId>jersey-test-framework-provider-grizzly2</artifactId>
	<version>2.21</version>
	<exclusions>
		<exclusion>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```

**Comment by beena-yatin-kanyal** [comment]
@joschi - Please comment on this - _Does this mean that there will be no further developments in the Dropwizard 1.X series?_

And you may close the issue as we are not encountering it anymore and our service is running fine now. Thanks and advance.

**Comment by joschi** [comment]
> Does this means that there will be no further developments in the Dropwizard 1.X series?

Yes, as stated in https://groups.google.com/g/dropwizard-user/c/6gpDMuSb4_Y.
