### ISSUE TITLE
Dropwizard Configuration Error with Junit5 and OpenJDK 11

### ISSUE THREAD

**Issue by vabs** [dropwizard/dropwizard#3846]
I have a dropwizard integration test which runs the application and call to the resource to ensure code's business logic's validity. 
Whenever I run the integration test, I get this error. 

The guidelines which I followed to create the test are from: https://www.dropwizard.io/en/latest/manual/testing.html#junit-5

Dropwizard Version: 2.0.20
OpenJDK: 11

```
Test ignored.

java.lang.Exception: java.lang.NoSuchMethodError: 'io.dropwizard.Configuration io.dropwizard.cli.EnvironmentCommand.getConfiguration()'

	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:87)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
Caused by: java.lang.NoSuchMethodError: 'io.dropwizard.Configuration io.dropwizard.cli.EnvironmentCommand.getConfiguration()'
	at io.dropwizard.testing.DropwizardTestSupport.startIfRequired(DropwizardTestSupport.java:331)
	at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:225)
	at io.dropwizard.testing.junit5.DropwizardAppExtension.before(DropwizardAppExtension.java:195)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:97)
	at io.dropwizard.testing.junit5.DropwizardExtensionsSupport.beforeAll(DropwizardExtensionsSupport.java:83)
	... 37 more
```

**Comment by vabs** [comment]
I believe the error is originating from :

Class: `DropwizardTestSupport`
Method Name: `startIfRequired`
Possible Error Line: `this.configuration = environmentCommand.getConfiguration();` 

This line is throwing a null pointer exception. On debugging, this should be replaced with: `environmentCommand.getConfigurationClass()` 


```
private void startIfRequired() throws Exception {

....
      Namespace namespace = new Namespace(namespaceAttributes);
      Command command = (Command)this.commandInstantiator.apply(this.application);
      command.run(bootstrap, namespace);
      if (command instanceof EnvironmentCommand) {
        EnvironmentCommand<C> environmentCommand = (EnvironmentCommand)command;
        this.configuration = environmentCommand.getConfiguration();
        this.environment = environmentCommand.getEnvironment();
      } else if (command instanceof ConfiguredCommand) {
        ConfiguredCommand<C> configuredCommand = (ConfiguredCommand)command;
        this.configuration = configuredCommand.getConfiguration();
      }
...
}
```

**Comment by joschi** [comment]
@vabs Check and ensure that you're using the correct version of Dropwizard dependencies in your project, for example by importing `dropwizard-bom` or `dropwizard-dependencies`.

**Comment by vabs** [comment]
Yes @joschi , you were correct. There was a dependency issue. Thanks for the quick response. I managed to fix it by using `dropwizard-bom`

**Comment by joschi** [comment]
@vabs Glad we could resolve it. 😄
