### ISSUE TITLE
Can't get basic application to connect to database and start.

### ISSUE THREAD

**Issue by rossedwardsus** [dropwizard/dropwizard#4012]
Hello.  I have been going through the getting started guide.  When i try to connect to a local postgresql database and start the server i keep getting an admin error.  I don't even need the admin as i am just testing the code for possible use in an application.

This is the command i am running, 
java -jar target/DWGettingStarted-1.0-SNAPSHOT.jar server dwgettingstarted.yaml

This is the error i am getting, 
```
INFO  [2021-06-01 19:50:56,509] org.eclipse.jetty.util.log: Logging initialized @10234ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2021-06-01 19:50:57,014] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /application
INFO  [2021-06-01 19:50:57,022] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
java.lang.NullPointerException
	at com.javaeeeee.dwstart.HelloJsonResource.<init>(HelloJsonResource.java:28)
	at com.javaeeeee.dwstart.DWGettingStartedApplication.run(DWGettingStartedApplication.java:43)
	at com.javaeeeee.dwstart.DWGettingStartedApplication.run(DWGettingStartedApplication.java:11)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.javaeeeee.dwstart.DWGettingStartedApplication.main(DWGettingStartedApplication.java:14)
```
Most of the code is nothing more then a direct copy from the getting started and various example code i found.  So i am at a loss as to what the problem might be.

**Comment by joschi** [comment]
Please post your `DWGettingStartedApplication` and `HelloJsonResource` (or the complete project sources).

**Comment by rossedwardsus** [comment]
DWGettingStartedApplication:

import io.dropwizard.setup.Environment;
import io.dropwizard.jdbi3.JdbiFactory;
//import org.skife.jdbi;
//import resources.EventResource;
import org.jdbi.v3.core.Jdbi;

public class DWGettingStartedApplication extends Application<DWGettingStartedConfiguration> {

    public static void main(final String[] args) throws Exception {
        new DWGettingStartedApplication().run(args);
    }

    @Override
    public String getName() {
        return "DWGettingStarted";
    }

    @Override
    public void initialize(final Bootstrap<DWGettingStartedConfiguration> bootstrap) {
        // TODO: application initialization
    }

    @Override
    public void run(final DWGettingStartedConfiguration configuration,
                    final Environment environment) {
        // TODO: implement application
        
        final JdbiFactory factory = new JdbiFactory();
        final Jdbi jdbi = factory.build(environment, configuration.getDataSourceFactory(), "postgresql");
        //environment.jersey().register(new UserResource(jdbi));

        //final JdbiFactory factory = new JdbiFactory();
        //final DBI jdbi = factory.build(environment, configuration.getDataSourceFactory(), "database");
        //final EventDao eventDao = jdbi.onDemand(EventDao.class);
 
        //e.jersey().register(new EventResource(eventDao));

        //final MyDAO mydao = jdbi.onDemand(MyDAO.class);
    

        environment.jersey().register(new HelloResource());
        environment.jersey().register(new HelloJsonResource(jdbi));

 
    }

}

HelloJsonResource:
package com.javaeeeee.dwstart;

import javax.ws.rs.POST;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;
import com.codahale.metrics.annotation.Timed;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.dropwizard.db.DataSourceFactory;
//import io.dropwizard.jdbi3.JdbiFactory;
import javax.validation.Valid;
import org.jdbi.v3.core.Jdbi;

import java.util.List;

//MyDAO mydao = new MyDAO();

@Path("/hello_json")
public class HelloJsonResource {

    //@Valid
    //@NotNull
    //private DataSourceFactory database = new DataSourceFactory();

    private Jdbi database;

    HelloJsonResource(Jdbi database){
        this.database = database;
        
    }

    final MyDAO dao = database.onDemand(MyDAO.class);

    //public User user = new User();


    @GET
    @Produces(MediaType.APPLICATION_JSON)
    public List<User> getJSONGreeting() {
        //final MyDAO dao = database.onDemand(MyDAO.class);
        List<User> users = dao.getAllUsers();

        //return new User(email);

        return users;

        //return new Greeting("Hello world get!");
    }

    public static class TestClass {

        @JsonProperty("name")
        public String name;

    }

    @POST
    @Timed
    @Produces(MediaType.APPLICATION_JSON)
    public Greeting postJSONGreeting(TestClass test) {
        return new Greeting("Hello world post!" + test.name);
    }

    //curl -X POST -H "Content-Type: application/json" -d '{"name": "linuxize@example.com"}' http://localhost:8080/hello_json
}

**Comment by joschi** [comment]
> ```java
>     HelloJsonResource(Jdbi database){
>         this.database = database;
>         
>     }
> 
>     final MyDAO dao = database.onDemand(MyDAO.class);
> ```

`database` is `null` when you're trying to use it in the assignment of `dao`.

Try pulling the assignment of `dao` into the constructor (`HelloJsonResource(Jdbi database)`).

**Comment by rossedwardsus** [comment]
Sorry can you clarify what you mean?

**Comment by rossedwardsus** [comment]
I get a different error but my code might not be right.

private Jdbi database;
    final MyDAO dao;

HelloJsonResource(Jdbi database){
        this.database = database;
        this.dao = database.onDemand(MyDAO.class);
    }

java -jar target/DWGettingStarted-1.0-SNAPSHOT.jar server dwgettingstarted.yaml
INFO  [2021-06-01 22:44:41,538] org.eclipse.jetty.util.log: Logging initialized @13632ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2021-06-01 22:44:42,287] io.dropwizard.server.DefaultServerFactory: Registering jersey handler with root path prefix: /
INFO  [2021-06-01 22:44:42,300] io.dropwizard.server.DefaultServerFactory: Registering admin handler with root path prefix: /
org.jdbi.v3.core.extension.NoSuchExtensionException: Extension not found: interface com.javaeeeee.dwstart.MyDAO
	at org.jdbi.v3.core.Jdbi.onDemand(Jdbi.java:510)
	at com.javaeeeee.dwstart.HelloJsonResource.<init>(HelloJsonResource.java:31)
	at com.javaeeeee.dwstart.DWGettingStartedApplication.run(DWGettingStartedApplication.java:46)
	at com.javaeeeee.dwstart.DWGettingStartedApplication.run(DWGettingStartedApplication.java:11)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:59)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at com.javaeeeee.dwstart.DWGettingStartedApplication.main(DWGettingStartedApplication.java:14)

**Comment by rossedwardsus** [comment]
I have gotten the code to build however this line, this.dao = jdbi.onDemand(MyDao1.class) keeps throwing an error at runtime.

org.jdbi.v3.core.extension.NoSuchExtensionException: Extension not found: interface com.javaeeeee.dwstart.db.MyDao1

I have placed it within the constructor and outside and still get the same error.

**Comment by j4n1** [comment]
@rossedwardsus can you share complete project in a repo?

**Comment by rossedwardsus** [comment]
Someone in the JDBI community ended up figuring it out.  It was a simple issue related to using the wrong imports which i didn't even notice i had done.  So the code was compiling but there was probably an error being thrown, possibly related to incompatible types, but it was disappearing and instead i was getting the one i mentioned.  Once i changed the imports it worked as expected.

Thanks!
