### ISSUE TITLE
Spurious liquibase errors: 'Cannot read liquibase.build.properties'

### ISSUE THREAD

**Issue by johnv-git** [dropwizard/dropwizard#4096]
Liquibase 3.8.1 introduced a bug where its internal version getter fails and complains loudly under some (all?) circumstances.  All subsequent liquibase 3.x versions contain the issue (3.10.2 specifically).  Dropwizard introduced this in 1.3.25 when it updated from liquibase 3.6.3 => 3.10.2.  While the bug seems fixed in liquibase 4.x (and thus in DW 2.1.x), I've managed not to notice this error (warning) deep in the Integration Test output since DW 1.3.25 (until I went to update to 2.0.23 today).

Feel free to close because you've already addressed this in DW 2.1.x, but if anyone else sees this output when migrating a db in the context of integration tests: you're not alone, you're not crazy, and it doesn't seem to matter.  (You can force a 4.x dependency if sufficiently offended -- I did and it works fine.)

```
ERROR [2021-07-01 15:25:06,069] liquibase.util.LiquibaseUtil: Cannot read liquibase.build.properties
! java.io.IOException: Found 2 files that match liquibase.build.properties
! at liquibase.util.StreamUtil.singleInputStream(StreamUtil.java:206)
! at liquibase.util.StreamUtil.openFromClasspath(StreamUtil.java:241)
! at liquibase.util.StreamUtil.openStream(StreamUtil.java:151)
! at liquibase.util.LiquibaseUtil.getBuildInfo(LiquibaseUtil.java:31)
! at liquibase.util.LiquibaseUtil.getBuildVersion(LiquibaseUtil.java:15)
! at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:95)
! at liquibase.sqlgenerator.core.MarkChangeSetRanGenerator.generateSql(MarkChangeSetRanGenerator.java:25)
! at liquibase.sqlgenerator.SqlGeneratorChain.generateSql(SqlGeneratorChain.java:30)
! at liquibase.sqlgenerator.SqlGeneratorFactory.generateSql(SqlGeneratorFactory.java:222)
! at liquibase.executor.AbstractExecutor.applyVisitors(AbstractExecutor.java:105)
! at liquibase.executor.jvm.JdbcExecutor.access$600(JdbcExecutor.java:43)
! at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:412)
! at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:87)
! at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:159)
! at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:139)
! at liquibase.changelog.StandardChangeLogHistoryService.setExecType(StandardChangeLogHistoryService.java:388)
! at liquibase.database.AbstractJdbcDatabase.markChangeSetExecStatus(AbstractJdbcDatabase.java:1133)
! at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:64)
! at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:97)
! at liquibase.Liquibase.update(Liquibase.java:201)
! at liquibase.Liquibase.update(Liquibase.java:178)
! at liquibase.Liquibase.update(Liquibase.java:174)
! at liquibase.Liquibase.update(Liquibase.java:167)
! at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:65)
! at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
! at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at com.enterprise.resources.AbstractResourceIT.setUpDatabases(AbstractResourceIT.java:54)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:498)
! at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
! at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
! at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
! at org.junit.internal.runners.statements.RunBefores.invokeMethod(RunBefores.java:33)
! at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
! at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
! at org.junit.rules.RunRules.evaluate(RunRules.java:20)
! at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
! at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
! at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
! at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
! at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
! at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
! at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
! at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
! at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
! at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
INFO  [2021-07-01 15:25:06,248] liquibase.changelog.ChangeSet: Custom SQL executed
INFO  [2021-07-01 15:25:06,248] liquibase.changelog.ChangeSet: ChangeSet migrations.sql::85::cptnkirk ran successfully in 174ms 
```

**Comment by joschi** [comment]
> Liquibase 3.8.1 introduced a bug where its internal version getter fails and complains loudly under some (all?) circumstances. All subsequent liquibase 3.x versions contain the issue (3.10.2 specifically).

@johnv-git Thanks for reporting this! Do you know if there is a GitHub issue for Liquibase which we could track or reference for this?

**Comment by jmini** [comment]
The liquibase lib is reading this file:

```StreamUtil.openStream("liquibase.build.properties", false, null, new ClassLoaderResourceAccessor(LiquibaseUtil.class.getClassLoader()))```

source: https://github.com/liquibase/liquibase/blob/46fc9ce9ba08806d9ad943983cc99f4f9160aeb7/liquibase-core/src/main/java/liquibase/util/LiquibaseUtil.java#L31
