### ISSUE TITLE
Dropwizard do not supports PKCS11 keyStoreType

### ISSUE THREAD

**Issue by duttarnab** [dropwizard/dropwizard#4127]
Dropwizard throwing error when `keyStoreType` is set to `PKCS11` for  FIPS-compliant key store.

```
ERROR  [10:13:06.153] [main] i.d.c.ServerCommand -  Unable to start server, shutting down 
java.security.KeyManagementException: FIPS mode: only SunJSSE KeyManagers may be used
        at java.base/sun.security.ssl.SSLContextImpl.chooseKeyManager(SSLContextImpl.java:167)
        at java.base/sun.security.ssl.SSLContextImpl.engineInit(SSLContextImpl.java:83)
        at java.base/javax.net.ssl.SSLContext.init(SSLContext.java:297)
        at org.eclipse.jetty.util.ssl.SslContextFactory.load(SslContextFactory.java:379)
        at org.eclipse.jetty.util.ssl.SslContextFactory.doStart(SslContextFactory.java:245)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
        at org.eclipse.jetty.server.Server.start(Server.java:408)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
        at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
        at org.eclipse.jetty.server.Server.doStart(Server.java:372)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
        at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
        at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:45)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at org.gluu.oxd.server.OxdServerApplication.main(OxdServerApplication.java:23)
```

It doesn't support `PKCS11` (where Keystore isn't file-based)

**Comment by joschi** [comment]
@duttarnab Thanks for reporting this!

Could you please provide a minimal example to reproduce the issue and exact information about the version of Dropwizard you're using and the JRE you're using to run the application?
