### ISSUE TITLE
If request '“Content-Encoding:gzip” with raw string in body instead of binary , the response error code should be 400 instead of 500

### ISSUE THREAD

**Issue by wenjin-huang** [dropwizard/dropwizard#4176]
If the request has the “Content-Encoding:gzip” in the header, but instead of having binary .gz file as payload, it has a raw string as body payload. The response is 500 error, but it should be 400 BAD request. 
```
o.eclipse.jetty.server.HttpChannelState - unhandled due to prior sendError
! java.util.zip.ZipException: Invalid gzip bytes
! at org.eclipse.jetty.http.GZIPContentDecoder.decodeChunks(GZIPContentDecoder.java:272)
! ... 98 common frames omitted
! Causing: java.lang.RuntimeException: java.util.zip.ZipException: Invalid gzip bytes
! at org.eclipse.jetty.http.GZIPContentDecoder.decodeChunks(GZIPContentDecoder.java:402)
! at org.eclipse.jetty.server.handler.gzip.GzipHttpInputInterceptor$Decoder.decodeChunks(GzipHttpInputInterceptor.java:91)
! at org.eclipse.jetty.server.handler.gzip.GzipHttpInputInterceptor.readFrom(GzipHttpInputInterceptor.java:45)
! at org.eclipse.jetty.server.HttpInput.intercept(HttpInput.java:500)
! ... 95 common frames omitted
! Causing: java.io.IOException: Bad content
! at org.eclipse.jetty.server.HttpInput.intercept(HttpInput.java:504)
! at org.eclipse.jetty.server.HttpInput.nextInterceptedContent(HttpInput.java:464)
! at org.eclipse.jetty.server.HttpInput.addContent(HttpInput.java:629)
! at org.eclipse.jetty.server.HttpChannel.onContent(HttpChannel.java:778)
! at org.eclipse.jetty.server.HttpChannelOverHttp.content(HttpChannelOverHttp.java:245)
! at org.eclipse.jetty.http.HttpParser.parseContent(HttpParser.java:1710)
! at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1545)
! at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:376)
! at org.eclipse.jetty.server.HttpConnection.fillAndParseForContent(HttpConnection.java:323)
! at org.eclipse.jetty.server.HttpInputOverHTTP.produceContent(HttpInputOverHTTP.java:33)
! at org.eclipse.jetty.server.HttpInput.nextContent(HttpInput.java:382)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:316)
! at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:79)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream.read(ReaderInterceptorExecutor.java:273)
! at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.ensureLoaded(ByteSourceJsonBootstrapper.java:539)
! at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.detectEncoding(ByteSourceJsonBootstrapper.java:133)
! at com.fasterxml.jackson.core.json.ByteSourceJsonBootstrapper.constructParser(ByteSourceJsonBootstrapper.java:256)
! at com.fasterxml.jackson.core.JsonFactory._createParser(JsonFactory.java:1656)
! at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:1085)
! at com.fasterxml.jackson.jaxrs.base.ProviderBase._createParser(ProviderBase.java:830)
! at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:771)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
! at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundReadFrom(MappableExceptionWrapperInterceptor.java:49)
! at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
! at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
! at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
! at org.glassfish.jersey.server.ContainerRequest.readEntity(ContainerRequest.java:282)
! at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:73)
! at org.glassfish.jersey.server.internal.inject.EntityParamValueParamProvider$EntityValueSupplier.apply(EntityParamValueParamProvider.java:56)
! at org.glassfish.jersey.server.spi.internal.ParamValueFactoryWithSource.apply(ParamValueFactoryWithSource.java:50)
! at org.glassfish.jersey.server.spi.internal.ParameterValueHelper.getParameterValues(ParameterValueHelper.java:68)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$AbstractMethodParamInvoker.getParamValues(JavaResourceMethodDispatcherProvider.java:109)
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:219)
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:79)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:475)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:397)
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:81)
! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:255)
! ... 56 common frames omitted
! Suppressed: java.lang.Throwable: HttpInput failure
!              at org.eclipse.jetty.server.HttpInput.failed(HttpInput.java:895)
!              at org.eclipse.jetty.server.HttpInput.addContent(HttpInput.java:638)
!              ... 93 common frames omitted
! Causing: org.glassfish.jersey.server.ContainerException: java.io.IOException: Bad content
! at org.glassfish.jersey.servlet.internal.ResponseWriter.rethrow(ResponseWriter.java:254)
! at org.glassfish.jersey.servlet.internal.ResponseWriter.failure(ResponseWriter.java:236)
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:438)
! at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:263)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
! ... 47 common frames omitted
! Causing: javax.servlet.ServletException: org.glassfish.jersey.server.ContainerException: java.io.IOException: Bad content
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:410)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
! at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
! at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:35)
! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:47)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:41)
! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
! at com.pros.b2b.commons.dropwizard.filter.RequestTraceFilter.doFilter(RequestTraceFilter.java:110)
! at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193)
! at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1435)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1350)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:313)
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:52)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:763)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:54)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
! at org.eclipse.jetty.server.Server.handle(Server.java:516)
! at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388)
! at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
! at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
! at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
! at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:383)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:882)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1036)
! at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by zUniQueX** [comment]
@wenjin-huang This should be fixed in 2.1.0-beta.6 onwards.
