### ISSUE TITLE
`DropwizardSSLConnectionSocketFactoryTest` failing on Windows

### ISSUE THREAD

**Issue by joschi** [dropwizard/dropwizard#4330]
After re-enabling `DropwizardSSLConnectionSocketFactoryTest` (#4260, #4299), it's failing on Windows:
```
[ERROR] Tests run: 17, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 5.504 s <<< FAILURE! - in io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest
[ERROR] shouldSucceedWithBcProvider  Time elapsed: 0.253 s  <<< ERROR!
javax.ws.rs.ProcessingException: javax.net.ssl.SSLProtocolException: Unsupported handshake message: server_hello_done
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldSucceedWithBcProvider(DropwizardSSLConnectionSocketFactoryTest.java:274)
Caused by: javax.net.ssl.SSLProtocolException: Unsupported handshake message: server_hello_done
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldSucceedWithBcProvider(DropwizardSSLConnectionSocketFactoryTest.java:274)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldSucceedWithBcProvider(DropwizardSSLConnectionSocketFactoryTest.java:274)
[ERROR] shouldReturn200IfAbleToClientAuthSpecifyingCertAliasForGoodCert  Time elapsed: 0.094 s  <<< ERROR!
javax.ws.rs.ProcessingException: javax.net.ssl.SSLProtocolException: Unsupported handshake message: server_hello_done
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldReturn200IfAbleToClientAuthSpecifyingCertAliasForGoodCert(DropwizardSSLConnectionSocketFactoryTest.java:178)
Caused by: javax.net.ssl.SSLProtocolException: Unsupported handshake message: server_hello_done
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldReturn200IfAbleToClientAuthSpecifyingCertAliasForGoodCert(DropwizardSSLConnectionSocketFactoryTest.java:178)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldReturn200IfAbleToClientAuthSpecifyingCertAliasForGoodCert(DropwizardSSLConnectionSocketFactoryTest.java:178)
[ERROR] shouldReturn200IfAbleToClientAuth  Time elapsed: 0.047 s  <<< ERROR!
javax.ws.rs.ProcessingException: javax.net.ssl.SSLProtocolException: Unsupported handshake message: server_hello_done
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldReturn200IfAbleToClientAuth(DropwizardSSLConnectionSocketFactoryTest.java:155)
Caused by: javax.net.ssl.SSLProtocolException: Unsupported handshake message: server_hello_done
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldReturn200IfAbleToClientAuth(DropwizardSSLConnectionSocketFactoryTest.java:155)
Caused by: java.lang.UnsupportedOperationException: Not supported yet.
	at io.dropwizard.client.DropwizardSSLConnectionSocketFactoryTest.shouldReturn200IfAbleToClientAuth(DropwizardSSLConnectionSocketFactoryTest.java:155)
```

**Comment by zUniQueX** [comment]
@joschi I checked this today with Corretto 17.0.1 and can't reproduce the issue. Could this be a JDK problem?

**Comment by zUniQueX** [comment]
It seems that recently more builds failed on Appveyor due to condition timeouts. Our Windows testing is therefore not that reliable at the moment.

What should we do about that? If the GitHub Windows runners are more reliable, I'd appreciate having them re-enabled. But we could/should also do something about Appveyor. Should we adjust the timeouts so that the builds hopefully will succeed?
