### ISSUE TITLE
PATCH tests failing under Java 17

### ISSUE THREAD

**Issue by JonathanBlood** [dropwizard/dropwizard#4404]
Hey all,

I'm upgrading a Dropwizard project to Java 17 and I encountered issues with tests that are using PATCH endpoints such as:

```
final Response response = client().target(baseUrl() + Endpoints.TEXT + "/" + UUID.randomUUID()")
                                          .request()
                                          .build("PATCH", Entity.entity(patch, MediaType.APPLICATION_JSON_TYPE))
                                          .invoke();
```

When the client triggers this call it fails with:

```
javax.ws.rs.ProcessingException: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @2d3fcdbd

	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:309)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:643)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:665)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:659)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:659)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:642)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:445)
	at com.blah.mars.contentservice.resources.TextResourceIntegrationTest.patch_recordNotFound(TextResourceIntegrationTest.java:392)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.RuntimeException: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @2d3fcdbd
	at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:518)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.setRequestMethodViaJreBugWorkaround(HttpUrlConnector.java:479)
	at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:323)
	at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:265)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:297)
	... 76 more
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field protected java.lang.String java.net.HttpURLConnection.method accessible: module java.base does not "opens java.net" to unnamed module @2d3fcdbd
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
	at org.glassfish.jersey.client.internal.HttpUrlConnector$3.run(HttpUrlConnector.java:513)
	... 81 more
```

I was running Dropwizard 2.0.25.

**Comment by zUniQueX** [comment]
The message of the exception seems to be related to Java modiles. Currently Dropwizard is not compliant with the JPMS. See #3233, #2926

**Comment by devoto13** [comment]
IIRC We've resolved it in our project by switching to the [Jersey connector](https://eclipse-ee4j.github.io/jersey.github.io/documentation/latest/client.html#d0e4979), which does not rely on [workarounds](http://javadox.com/org.glassfish.jersey.core/jersey-client/2.7/org/glassfish/jersey/client/HttpUrlConnectorProvider.html#SET_METHOD_WORKAROUND) to support PATCH protocol. E.g.

```java
var clientConfig = new ClientConfig();
clientConfig.connectorProvider(new ApacheConnectorProvider());
var client = ClientBuilder.newClient(clientConfig);
```

**Comment by zUniQueX** [comment]
From the `jersey-apache-connector` package only the `LocalizationMessages` class was used. Therefore it was recently removed: https://github.com/dropwizard/dropwizard/pull/4413

**Comment by zUniQueX** [comment]
@devoto13 After searching a bit more, I found this line actually using workarounds: https://github.com/dropwizard/dropwizard/blob/4082301e48148a62d48b3265058fae5fb127bdc1/dropwizard-testing/src/main/java/io/dropwizard/testing/junit5/DropwizardAppExtension.java#L282

As the JavaDoc describes, there can be inconsistent behaviour when doing this. I'm not quite sute what to do about this

**Comment by zUniQueX** [comment]
When using a connector, I think only the Apache connector would be a good choice, since we use the Apache http client. But we just removed the existing unused connector dependency and added deprecations in favor of httpclient5. When re-adding the connector we would have to wait for Jersey to provide a connector for httpclient5 until we can upgrade.

**Comment by zUniQueX** [comment]
After rethinking this, I believe using Jersey connectors could actually be the best option for this. The cleanest way would have been to get a dependency on `dropwizard-client`, but this depends itself on `dropwizard-testing` and therefore this would lead to a cyclic dependency.

As I said before, we shouldn't use the Apache connector, since it doesn't support httpclient5 and I personally don't want to have two Apache client dependencies with different versions. `dropwizard-http2` already uses Jetty's client, so I'd suggest using this client in combination with the Jersey connector. But I have no experience with Jersey connectors.

@devoto13 Do you think, this would be a good solution?

**Comment by devoto13** [comment]
Sounds pretty reasonable to me.

Just note that it may be a mild breaking change. At least our app didn't include `WWW-Authenticate` header in 401 responses, which caused some tests to fail with `javax.ws.rs.ProcessingException: java.util.concurrent.ExecutionException: org.eclipse.jetty.client.HttpResponseException: HTTP protocol violation: Authentication challenge without WWW-Authenticate header`. I'm not sure if the Jetty client is more strict than the default connector in some other extents as well.

**Comment by zUniQueX** [comment]
I think this change could be reasonable in favor of Java 17 support. When documenting it well, that should be no problem.

If other connectors handle it differently, I personally have no preference for a specific client. Therefore I'd suggest testing different connectors on the existing codebase and picking the "best" one. As this _should_ be a minor change in my opinion, I hope there is a client not breaking anything.

**Comment by zUniQueX** [comment]
After testing the connectors, I don't see an "optimal" connector at the moment. The Jetty and Grizzly connectors pass all existing tests in `dropwizard-testing`, while the Netty and Apache connectors fail at the `GzipDefaultVaryBehaviourTest`. Therefore only the Jetty and Grizzly connectors look viable to me.

The JavaDoc of the `JettyConnectorProvider` lists supported http methods but leaves out the PATCH method (although this issue seems to be fixed with this connector). Therefore I wouldn't rely on this connector too.

The Grizzly connector overall looks very promising, although it fails with the dependency convergence because it pulls in different versions of two dependencies. When explicitly excluding the conflicting dependencies and manually re-adding them to `dropwizard-testing`, this connector passes all existing tests of the framework (except one with a small fix).

I just wonder, if we should include the dependency workaround to address this issue. I think we shouldn't break users upgrading to Java 17 and therefore address this fast, but I also fear manually taking care of Grizzly dependencies as we don't use these ourselves.

**Comment by zUniQueX** [comment]
Issue for the Grizzly connector: https://github.com/eclipse-ee4j/jersey/issues/4917

**Comment by mattnelson** [comment]
> After testing the connectors, I don't see an "optimal" connector at the moment.

I know this isn't a great option, but there might be an option for people who run on jdk11. @zUniQueX added a JDK HttpClient connector for jersey3. Would a similar connector for jersey2 pass all the tests?

https://github.com/eclipse-ee4j/jersey/pull/4940

**Comment by zUniQueX** [comment]
@mattnelson This shouldn't be a good option in any case. Dropwizard will stay on Java 8 in versions 2.x.x and using a JDK 11 feature will probably cause problems. Additionally, mixing up different versions of `jersey-client` dependencies (thereby including connectors) frequently breaks projects. So the Java HttpClient shouldn't be a good option at the moment.

As I wrote before, the Grizzly connector looks good. My PR regarding the dependency convergence error was accepted, so we can use the connector hopefully after the release of Jersey 2.36.
