### ISSUE TITLE
JDK 17 support? Unsupported class file major version 61

### ISSUE THREAD

**Issue by chriskessel** [dropwizard/dropwizard#4690]
I'm trying to upgrade from JDK 14->17 and after resolving a couple other things, I'm now blocked by this issue on dropwizard startup. Is there some dependency I'm missing or maybe a known conflict with an existing dependency? Usually this is a sign of something compiled with a new JDK being loaded by an old JDK, but that's not the issue here. I'm definitely running with JDK 17. Looks like something with a google asm library being used in Dropwizard?

```
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2055)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3966)
	at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3989)
	at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4950)
	at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4956)
	at com.google.inject.internal.util.StackTraceElements.forMember(StackTraceElements.java:71)
	at com.google.inject.internal.ProviderMethod.toString(ProviderMethod.java:215)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.visitor.GuiceBindingVisitor.visit(GuiceBindingVisitor.java:40)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.visitor.GuiceBindingVisitor.visit(GuiceBindingVisitor.java:21)
	at com.google.inject.internal.ProviderMethod.acceptExtensionVisitor(ProviderMethod.java:202)
	at com.google.inject.internal.ProviderInstanceBindingImpl.acceptTargetVisitor(ProviderInstanceBindingImpl.java:68)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.visitor.GuiceElementVisitor.visit(GuiceElementVisitor.java:22)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.visitor.GuiceElementVisitor.visit(GuiceElementVisitor.java:16)
	at com.google.inject.internal.BindingImpl.acceptVisitor(BindingImpl.java:99)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.GuiceModelParser.parseElement(GuiceModelParser.java:88)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.GuiceModelParser.indexElements(GuiceModelParser.java:116)
	at ru.vyarus.dropwizard.guice.debug.report.guice.util.GuiceModelParser.parse(GuiceModelParser.java:52)
	at ru.vyarus.dropwizard.guice.debug.report.guice.GuiceBindingsRenderer.renderReport(GuiceBindingsRenderer.java:97)
	at ru.vyarus.dropwizard.guice.debug.GuiceBindingsDiagnostic.applicationStarted(GuiceBindingsDiagnostic.java:32)
	at ru.vyarus.dropwizard.guice.module.lifecycle.GuiceyLifecycleAdapter.onEvent(GuiceyLifecycleAdapter.java:108)
	at ru.vyarus.dropwizard.guice.module.lifecycle.internal.LifecycleSupport.lambda$broadcast$1(LifecycleSupport.java:219)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at ru.vyarus.dropwizard.guice.module.lifecycle.internal.LifecycleSupport.broadcast(LifecycleSupport.java:219)
	at ru.vyarus.dropwizard.guice.module.lifecycle.internal.LifecycleSupport.applicationStarted(LifecycleSupport.java:224)
	at ru.vyarus.dropwizard.guice.module.lifecycle.internal.LifecycleSupport.access$000(LifecycleSupport.java:42)
	at ru.vyarus.dropwizard.guice.module.lifecycle.internal.LifecycleSupport$1.lifeCycleStarted(LifecycleSupport.java:136)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.setStarted(AbstractLifeCycle.java:194)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:74)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:53)
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 61
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:195)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:176)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:162)
	at com.google.inject.internal.asm.$ClassReader.<init>(ClassReader.java:283)
	at com.google.inject.internal.util.LineNumbers.<init>(LineNumbers.java:69)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:49)
	at com.google.inject.internal.util.StackTraceElements$1.load(StackTraceElements.java:45)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3533)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2282)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2159)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2049)
```

**Comment by zUniQueX** [comment]
I'm not sure this is a framework issue. GitHub Actions performs a build and therefore the integration tests with Java 17 on every commit.

From the stacktrace I'm assuming you use guice in your project. Guice is not a part of the core framework. As the exception gets thrown from that component, I'm expecting the issue there. If you're using a bundle for guice integration maybe you could try asking there.

**Comment by chriskessel** [comment]
That was it, I needed the Dropwizard Guicey library upgraded. That didn't occur to me, sorry. I just saw our code wasn't in the stack and thought it must be part of the Dropwizard stack. I didn't consider the guice stuff plugging itself into the stack!

**Comment by chriskessel** [comment]
Upgraded the guice dependency we were using.
