### ISSUE TITLE
UnitOfWork - java.lang.IllegalStateException: Existing session transaction state (false) does not match requested (true)

### ISSUE THREAD

**Issue by rbobbaa** [dropwizard/dropwizard#4715]
After upgrading the dropwizard to 2.0.25, I am started getting this exception in the methods having @unitOfwork annotations ,

Can you help me out to rectify these errors ? why I am getting these errors now ?

`Caused by: java.lang.IllegalStateException: Existing session transaction state (false) does not match requested (true)
at io.dropwizard.hibernate.UnitOfWorkAspect.validateSession(UnitOfWorkAspect.java:178)
at io.dropwizard.hibernate.UnitOfWorkAspect.beforeStart(UnitOfWorkAspect.java:85)`

**Comment by zUniQueX** [comment]
@rbobbaa This exception can only occur, when the `SessionFactory` for the `HibernateBundle` referenced by the `@UnitOfWork.value()` has already been bound to Hibernate's `ManagedSessionContext` and when the `getCurrentSession()` method of this `SessionFactory` returns an existing `Session` whose `Transaction` is not active. This means an other `Session` is managed by Hibernate and the transaction hasn't started yet or is already committed or aborted.

If you don't manually bind to Hibernate's `ManagedSessionContext`, I think there's a race condition in your application. Do you manually register a `UnitOfWorkApplicationListener` or do you use the `UnitOfWorkAwareProxyFactory`?

**Comment by rbobbaa** [comment]
I only add the anotation of unitOfWork on methods, One thing I noticed is there are multiple UnitOfWork anotations present in my code like calling method is also having unitofWork annotation , is this the issue ?

**Comment by rbobbaa** [comment]
for some of them I am not having this nested condition and still getting errors.

**Comment by zUniQueX** [comment]
Could you provide a test for this? I think this is really hard to debug and would appreciate an example to reproduce this.

**Comment by zUniQueX** [comment]
@rbobbaa Any update on this?

**Comment by zUniQueX** [comment]
Closing this due to inactivity of the author.
