### ISSUE TITLE
`dropwizard-migrations` doesn't find migrations file in `2.1.0-beta.8`

### ISSUE THREAD

**Issue by zUniQueX** [dropwizard/dropwizard#5150]
As the docs state, Liquibase [changed the file handling](https://docs.liquibase.com/concepts/changelogs/how-liquibase-finds-files.html) in 4.x.x. Therefore migration files from the file system aren't found any more.

```
liquibase.exception.ChangeLogParseException: The file db/changelog/migrations.xml was not found in
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
	at liquibase.parser.core.xml.XMLChangeLogSAXParser.parseToNode(XMLChangeLogSAXParser.java:99)
	at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:15)
	at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:369)
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:224)
	at liquibase.Scope.lambda$child$0(Scope.java:180)
	at liquibase.Scope.child(Scope.java:189)
	at liquibase.Scope.child(Scope.java:179)
	at liquibase.Scope.child(Scope.java:158)
	at liquibase.Liquibase.runInScope(Liquibase.java:2405)
	at liquibase.Liquibase.update(Liquibase.java:211)
	at liquibase.Liquibase.update(Liquibase.java:197)
	at liquibase.Liquibase.update(Liquibase.java:193)
	at liquibase.Liquibase.update(Liquibase.java:185)
	at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:65)
	at io.dropwizard.migrations.DbCommand.run(DbCommand.java:70)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
```

This should be caused from [not setting any root path to the `FileSystemResourceAccessor`](https://github.com/dropwizard/dropwizard/blob/release/2.1.x/dropwizard-migrations/src/main/java/io/dropwizard/migrations/CloseableLiquibaseWithFileSystemMigrationsFile.java#L20).

**Comment by zUniQueX** [comment]
While debugging, I found adding the [location of the source code](https://docs.oracle.com/javase/8/docs/api/java/security/CodeSource.html#getLocation--) to the root paths of the `FileSystemResourceAccessor` would allow to use files located under `src/main/resources` within a relative path from that folder.
