### ISSUE TITLE
BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn. Blackbird is not performing optimally!

### ISSUE THREAD

**Issue by lfoppiano** [dropwizard/dropwizard#5318]
I'm running a dropwizard application which I've just updated to dropwizard 2.1. I'm also using 

    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.0'
    implementation 'com.fasterxml.jackson.core:jackson-databind:2.13.3'
    implementation 'com.fasterxml.jackson.module:jackson-module-afterburner:2.13.0'
    implementation 'com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.13.3'

I'm using afterburner and jdk 8 and I get `com.fasterxml.jackson.module.blackbird.BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!` at startup. See below for the full stacktrace. 

1. Run the application using java 8 
2. At startup an exception is thrown: 
```WARN  [2022-05-23 16:03:31,703] com.fasterxml.jackson.module.blackbird.BlackbirdModule: Unable to find Java 9+ MethodHandles.privateLookupIn.  Blackbird is not performing optimally!
! java.lang.NoSuchMethodError: java.lang.invoke.MethodHandles.privateLookupIn(Ljava/lang/Class;Ljava/lang/invoke/MethodHandles$Lookup;)Ljava/lang/invoke/MethodHandles$Lookup;
! at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
! at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
! at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
! ... 28 common frames omitted
! Causing: java.lang.NoSuchMethodException: no such method: java.lang.invoke.MethodHandles.privateLookupIn(Class,Lookup)Lookup/invokeStatic
! at java.lang.invoke.MemberName.makeAccessException(MemberName.java:871)
! at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1003)
! at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1386)
! at java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:780)
! at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.init(ReflectionHack.java:39)
! at com.fasterxml.jackson.module.blackbird.util.ReflectionHack$Java9Up.<clinit>(ReflectionHack.java:34)
! at com.fasterxml.jackson.module.blackbird.util.ReflectionHack.privateLookupIn(ReflectionHack.java:24)
! at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.lambda$findProperties$0(BBSerializerModifier.java:67)
! at com.fasterxml.jackson.module.blackbird.util.Unchecked.lambda$runnable$0(Unchecked.java:31)
! at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.findProperties(BBSerializerModifier.java:68)
! at com.fasterxml.jackson.module.blackbird.ser.BBSerializerModifier.changeProperties(BBSerializerModifier.java:52)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.constructBeanOrAddOnSerializer(BeanSerializerFactory.java:414)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.findBeanOrAddOnSerializer(BeanSerializerFactory.java:294)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:239)
! at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:173)
! at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1495)
! at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1463)
! at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:585)
! at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
! at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4519)
! at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4498)
! at io.dropwizard.configuration.ConfigurationMetadata.<init>(ConfigurationMetadata.java:76)
! at io.dropwizard.configuration.BaseConfigurationFactory.<init>(BaseConfigurationFactory.java:76)
! at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:29)
! at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:18)
! at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:137)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at org.grobid.service.main.GrobidQuantitiesApplication.main(GrobidQuantitiesApplication.java:89)
```
4. if the application is ran with jdk 11, there is no problem. 

I would like to understand what is the issue and how to solve it. Thank you in advance

**Comment by zUniQueX** [comment]
Hi @lfoppiano! Blackbird is a newer version of Afterburner. Afterburner is getting old and doesn't support Java 9+ well, so we switched to Blackbird in the 2.1.0 release to provide better support for recent Java versions.

Java added a `privateLookupIn` method to the `MethodHandles` class [in Java 9](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/lang/invoke/MethodHandles.html#privateLookupIn(java.lang.Class,java.lang.invoke.MethodHandles.Lookup)) on which Blackbird relies. However, there is a compat class `ReflectionHack`, which provides compatibility with Java 8. This cannot use the `MethodHandles#privateLookupIn` method and therefore [logs a message](https://github.com/FasterXML/jackson-modules-base/blob/master/blackbird/src/main/java/com/fasterxml/jackson/module/blackbird/util/ReflectionHack.java#L45-L48) that it is not performing optimally. Please also refer to [this discussion](https://github.com/dropwizard/dropwizard/discussions/5268).
