### ISSUE TITLE
Could not start application due to "Could not find a suitable constructor in io.dropwizard.auth.AuthDynamicFeature class" after upgrading to V2.1.0

### ISSUE THREAD

**Issue by amin3mej** [dropwizard/dropwizard#5364]
Hi,

I have an application based on Dropwizard which worked with Dropwizard 2.0.26. I tried to upgrade it to version 2.1.0. After upgrading the library, I couldn't run the application. I got an error with this message: "Could not find a suitable constructor in io.dropwizard.auth.AuthDynamicFeature class".

Sources:

> build.gradle:
```groovy
    implementation 'io.dropwizard:dropwizard-core:2.1.0'
    implementation 'io.dropwizard:dropwizard-auth:2.1.0'
```

> Application.java:
```java

public class Application extends io.dropwizard.Application<ServiceConfiguration> {
    private static final Logger logger = LogManager.getLogger(Application.class);

    private Binder binder;

    public static void main(String[] args) throws Exception {
        new Application().run(args);
    }

    @Override
    public void run(ServiceConfiguration configuration, Environment environment) {
        Binder binder = createBinder();
        environment.jersey().register(binder);

        ...

        environment.jersey().register(AuthDynamicFeature.class);
        environment.jersey().register(new AuthValueFactoryProvider.Binder<>(Authority.class));
        environment.jersey().register(RolesAllowedDynamicFeature.class);
```

> Binder.java
```java
    protected void configure() {
        bindFactory(AuthDynamicFeatureFactory.class).to(AuthDynamicFeature.class).in(Singleton.class);
        ...
    }
```

> AuthDynamicFeatureFactory.java
```java
public class AuthDynamicFeatureFactory implements Supplier<AuthDynamicFeature> {
    @Override
    public AuthDynamicFeature get() {
        return new AuthDynamicFeature(...);
    }
}

```

> Running application log: 
```log
ERROR [2022-06-02 01:04:44,736] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
! java.lang.NoSuchMethodException: Could not find a suitable constructor in io.dropwizard.auth.AuthDynamicFeature class.
! at org.glassfish.jersey.inject.hk2.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:168)
! at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:156)
! at org.jvnet.hk2.internal.Utilities.justCreate(Utilities.java:1042)
! ... 68 common frames omitted
! Causing: org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
! 1. java.lang.NoSuchMethodException: Could not find a suitable constructor in io.dropwizard.auth.AuthDynamicFeature class.
! 
! at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65)
! at org.jvnet.hk2.internal.Utilities.justCreate(Utilities.java:1044)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.create(ServiceLocatorImpl.java:968)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1072)
! at org.jvnet.hk2.internal.ServiceLocatorImpl.createAndInitialize(ServiceLocatorImpl.java:1064)
! at org.glassfish.jersey.inject.hk2.AbstractHk2InjectionManager.createAndInitialize(AbstractHk2InjectionManager.java:194)
! at org.glassfish.jersey.inject.hk2.ImmediateHk2InjectionManager.createAndInitialize(ImmediateHk2InjectionManager.java:30)
! at org.glassfish.jersey.model.internal.CommonConfig.configureFeatures(CommonConfig.java:709)
! at org.glassfish.jersey.model.internal.CommonConfig.configureMetaProviders(CommonConfig.java:647)
! at org.glassfish.jersey.server.ResourceConfig.configureMetaProviders(ResourceConfig.java:824)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:332)
! at org.glassfish.jersey.server.ApplicationHandler.lambda$initialize$1(ApplicationHandler.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
! at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:232)
! at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:296)
! at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:261)
! at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:154)
! at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:347)
! at javax.servlet.GenericServlet.init(GenericServlet.java:180)
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:632)
! ... 48 common frames omitted
! Causing: javax.servlet.ServletException: jersey==io.dropwizard.jersey.setup.JerseyServletContainer@baa68670{jsp=null,order=-1,inst=true,async=true,src=EMBEDDED:null,STARTED}
! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:650)
! at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:415)
! at org.eclipse.jetty.servlet.ServletHandler.lambda$initialize$0(ServletHandler.java:731)
! at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
! at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
! at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
! at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:312)
! at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
! at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
! at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:755)
! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:379)
! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:916)
! at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:288)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:138)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.doStart(GzipHandler.java:426)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:253)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
! at org.eclipse.jetty.server.Server.start(Server.java:423)
! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:97)
! at org.eclipse.jetty.server.Server.doStart(Server.java:387)
! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:73)
! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:52)
! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:68)
! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
! at io.dropwizard.cli.Cli.run(Cli.java:78)
! at io.dropwizard.Application.run(Application.java:94)
! at dev.applicationName.Application.main(Application.java:84)
```

**Comment by zUniQueX** [comment]
Hi @amin3mej. Thanks for reporting this!

I've now checked, in which version the behaviour change was introduced. Your code still works in 2.1.0-beta.7 but fails in 2.1.0-beta.8. Most likely the behaviour change was introduced in #4563. There the `AuthDynamicFeature` was extended to also implement `Feature` for providing an `InjectionManager` for DI in `AuthFilter` objects.

The documentations for DI in Jersey and HK2 are very small and therefore I can't find specifics on that topic. However, I've tested a few cases and it seems you can provide the `DynamicFeature` as the binding contract. That means you can remove the line
```
environment.jersey().register(AuthDynamicFeature.class);
```
and change the code of your binder to
```
bindFactory(AuthDynamicFeatureFactory.class).to(DynamicFeature.class).in(Singleton.class);
```

As I mentioned, I don't know if there are edge cases where this code can cause errors, but in my test cases it behaves well.

**Comment by amin3mej** [comment]
Hi @zUniQueX,

It worked like a charm. Thanks.
