### ISSUE TITLE
[dropwizard-validation] @PortRange validation throws NullPointerException if value is null

### ISSUE THREAD

**Issue by ro-kr** [dropwizard/dropwizard#5684]
#### Issue description:
Configuration validation of an `Integer` property annotated with `@PortRange` throws a NullPointerException if the property value is unset (that is, `null`):

```
javax.validation.ValidationException: HV000028: Unexpected exception during isValid call.
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:186)
	at org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:62)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:75)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForSingleDefaultGroupElement(ValidatorImpl.java:518)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForDefaultGroup(ValidatorImpl.java:488)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateConstraintsForCurrentGroup(ValidatorImpl.java:450)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateInContext(ValidatorImpl.java:400)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validate(ValidatorImpl.java:172)
	at io.dropwizard.configuration.BaseConfigurationFactory.validate(BaseConfigurationFactory.java:244)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:129)
	at io.dropwizard.configuration.BaseConfigurationFactory.build(BaseConfigurationFactory.java:110)
	at io.dropwizard.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:139)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	…
Caused by: java.lang.NullPointerException
	at io.dropwizard.validation.PortRangeValidator.isValid(PortRangeValidator.java:22)
	at io.dropwizard.validation.PortRangeValidator.isValid(PortRangeValidator.java:10)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateSingleConstraint(ConstraintTree.java:180)
	... 18 more
```
The exception will be thrown even if the property is also annotated with `@NotNull`.

I think the issue is caused by a missing `null` check in `PortRangeValidator.isValid`: https://github.com/dropwizard/dropwizard/blob/d9a937ea62718b80c03bc7d8ffd1d3b444b1ef40/dropwizard-validation/src/main/java/io/dropwizard/validation/PortRangeValidator.java#L22

#### Expected behaviour

The `@PortRange` validator should silently accept a `null` value.

#### Code example
```java
import io.dropwizard.Configuration;
import io.dropwizard.validation.PortRange;
import javax.validation.constraints.NotNull;

public class AppConfiguration extends Configuration {

    @NotNull
    @PortRange
    private Integer port = null;
}
```

**Comment by joschi** [comment]
@ro-kr Thanks for reporting this! The issue will be fixed in the next release of Dropwizard 2.0.x and 2.1.x.
