### ISSUE TITLE
Unable to start application with no resources

### ISSUE THREAD

**Issue by reines** [dropwizard/dropwizard#577]
In Dropwizard 0.6 it was possible to start a service with no resources configured. While uncommon, we do have a couple Dropwizard services in this situation.

In 0.7 this seems to no longer work, causing a ServletException which causes the ServerCommand to bail out. I assume this is a change in behaviour from Jersey.

```
    ERROR [2014-05-12 20:35:59,855] io.dropwizard.cli.ServerCommand: Unable to start server, shutting down
    ! com.sun.jersey.api.container.ContainerException: The ResourceConfig instance does not contain any root resource classes.
    ! at com.sun.jersey.server.impl.application.RootResourceUriRules.<init>(RootResourceUriRules.java:99) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.server.impl.application.WebApplicationImpl._initiate(WebApplicationImpl.java:1359) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.server.impl.application.WebApplicationImpl.access$700(WebApplicationImpl.java:180) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:799) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.server.impl.application.WebApplicationImpl$13.f(WebApplicationImpl.java:795) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.inject.Errors.processWithErrors(Errors.java:193) ~[jersey-core-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:795) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.server.impl.application.WebApplicationImpl.initiate(WebApplicationImpl.java:790) ~[jersey-server-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.container.servlet.ServletContainer.initiate(ServletContainer.java:491) ~[jersey-servlet-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.container.servlet.ServletContainer$InternalWebComponent.initiate(ServletContainer.java:321) ~[jersey-servlet-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.container.servlet.WebComponent.load(WebComponent.java:605) ~[jersey-servlet-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.container.servlet.WebComponent.init(WebComponent.java:207) ~[jersey-servlet-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:376) ~[jersey-servlet-1.18.1.jar:1.18.1]
    ! at com.sun.jersey.spi.container.servlet.ServletContainer.init(ServletContainer.java:559) ~[jersey-servlet-1.18.1.jar:1.18.1]
    ! at javax.servlet.GenericServlet.init(GenericServlet.java:244) ~[javax.servlet-3.0.0.v201112011016.jar:na]
    ! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:540) ~[jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! ... 41 common frames omitted
    ! Causing: javax.servlet.ServletException: com.sun.jersey.spi.container.servlet.ServletContainer-177ed108@1c912cb3==com.sun.jersey.spi.container.servlet.ServletContainer,1,false
    ! at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:561) ~[jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.servlet.ServletHolder.initialize(ServletHolder.java:349) ~[jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.servlet.ServletHandler.initialize(ServletHandler.java:812) ~[jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:288) ~[jetty-servlet-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:732) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at com.codahale.metrics.jetty9.InstrumentedHandler.doStart(InstrumentedHandler.java:89) ~[metrics-jetty9-3.0.1.jar:3.0.1]
    ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.RequestLogHandler.doStart(RequestLogHandler.java:131) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.StatisticsHandler.doStart(StatisticsHandler.java:233) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.Server.start(Server.java:342) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.server.Server.doStart(Server.java:290) ~[jetty-server-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69) ~[jetty-util-9.0.7.v20131107.jar:9.0.7.v20131107]
    ! at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:43) ~[dropwizard-core-0.7.0.jar:0.7.0]
    ! at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:43) [dropwizard-core-0.7.0.jar:0.7.0]
    ! at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:76) [dropwizard-core-0.7.0.jar:0.7.0]
    ! at io.dropwizard.cli.Cli.run(Cli.java:70) [dropwizard-core-0.7.0.jar:0.7.0]
    ! at io.dropwizard.Application.run(Application.java:72) [dropwizard-core-0.7.0.jar:0.7.0]
    ! at com.jamierf.test.TestApplication.main(TestApplication.java:19) [classes/:na]
```

**Comment by kulbhushanchaskar** [comment]
environment.jersey().disable() blocks all rest resources registered with the jersey.
