### ISSUE TITLE
Initialization fails with slf4j-api 2.0.x

### ISSUE THREAD

**Issue by BastianVoigt** [dropwizard/dropwizard#5944]
We use dropwizard 2.1.2.
Other dependencies bumped `slf4j-api` to 2.0.x in our project, now we get an Exception during dropwizard initialization:

    java.lang.IllegalStateException: Unable to acquire the logger context
      at io.dropwizard.logging.LoggingUtil.getLoggerContext(LoggingUtil.java:46)
      at io.dropwizard.logging.DefaultLoggingFactory.<init>(DefaultLoggingFactory.java:74)
      at io.dropwizard.Configuration.getLoggingFactory(Configuration.java:113)
      at io.dropwizard.testing.DropwizardTestSupport.stopIfRequired(DropwizardTestSupport.java:267)
      at io.dropwizard.testing.DropwizardTestSupport.after(DropwizardTestSupport.java:240)
      at io.dropwizard.testing.DropwizardTestSupport.before(DropwizardTestSupport.java:232)
      at io.dropwizard.testing.junit.DropwizardAppRule.before(DropwizardAppRule.java:228)
      at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:50)

**Comment by mattnelson** [comment]
Did you upgrade logback as well?

https://logback.qos.ch/news.html
![image](https://user-images.githubusercontent.com/1894657/192555201-12fd6838-c3ea-4145-bdf9-a906cfc05ec1.png)


For dw-2.1.2 with slf4j 2.x, need to use logback-1.3.x

**Comment by BastianVoigt** [comment]
Nope, because we don't use logback directly. It comes as a transitive dependency. As a result we have both slf4j-api 1.7 and 2.0 on the classpath.

**Comment by zUniQueX** [comment]
Maven uses the ["nearest definition"](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Transitive_Dependencies) of a dependency. If you use a library that only uses `slf4j-api` and not `logback` and this is the "nearest definition" for `slf4j-api`, the Logback version is included from an other dependency and doesn't have to be compatible to the SLF4J version. To resolve this issue, you can specify the `logback` and `slf4j-api` dependencies in your project's pom and these versions will be used. Since SLF4J 2.x is compatible with 1.7.x, I'd suggest to use SLF4J 2 and Logback 1.3.

If you want to ensure compatibility of your dependencies, I'd recommend using the `maven-enforcer-plugin` with the `<dependencyConvergence/>` rule. Then you'll have to exclude incompatible transitive dependencies because incompatibilities will be reported at compile time.
