### ISSUE TITLE
Problem with version 2.1.2 in UnitOfWorkAwareProxyFactory using Java 17

### ISSUE THREAD

**Issue by irineuruiz** [dropwizard/dropwizard#6007]
Hello,

We are using dropwizard version 2.1.1 with Java 17 without any problem in our production environment.
However, today we updated dropwizard to version 2.1.2 in our development environments and to our surprise, it stopped working.

Apparently, our guess is some problem related to the ByteBuddy that is now being used in
at `io.dropwizard.hibernate.UnitOfWorkAwareProxyFactory.create(UnitOfWorkAwareProxyFactory.java:82)`

Here is the stack trace

```
java.lang.IllegalStateException: class io.dropwizard.hibernate.UnitOfWorkAwareProxyFactory$MethodInterceptor is not visible to class br.com.rassystem.rasng.core.auth.RasSystemBasicAuthenticator$ByteBuddy$uzQaONQH
	at net.bytebuddy.implementation.MethodDelegation$ImplementationDelegate$ForField$WithInstance.resolve(MethodDelegation.java:1092)
	at net.bytebuddy.implementation.MethodDelegation$ImplementationDelegate$ForField.compile(MethodDelegation.java:1018)
	at net.bytebuddy.implementation.MethodDelegation.appender(MethodDelegation.java:667)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:234)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Handler$ForImplementation.compile(MethodRegistry.java:206)
	at net.bytebuddy.dynamic.scaffold.MethodRegistry$Default$Prepared.compile(MethodRegistry.java:741)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.toTypeWriter(SubclassDynamicTypeBuilder.java:217)
	at net.bytebuddy.dynamic.scaffold.subclass.SubclassDynamicTypeBuilder.toTypeWriter(SubclassDynamicTypeBuilder.java:203)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$UsingTypeWriter.make(DynamicType.java:4050)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase.make(DynamicType.java:3734)
	at net.bytebuddy.dynamic.DynamicType$Builder$AbstractBase$Delegator.make(DynamicType.java:3986)
	at io.dropwizard.hibernate.UnitOfWorkAwareProxyFactory.create(UnitOfWorkAwareProxyFactory.java:82)
	at br.com.rassystem.rasng.core.RasNGCoreService.registerBasicAuthentication(RasNGCoreService.java:136)
	at br.com.rassystem.rasng.core.RasNGCoreService.run(RasNGCoreService.java:121)
	at br.com.rassystem.rasng.core.RasNGCoreService.run(RasNGCoreService.java:1)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:67)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:94)
	at br.com.rassystem.rasng.core.RasNGCoreService.main(RasNGCoreService.java:223)

```

**Comment by zUniQueX** [comment]
Hi @irineuruiz. This issue was alredy reported and got fixed in #5880. The fix will be released in Dropwizard 2.1.3.

As you already pointed out, the bug was introduced with the replacement of Javassist with ByteBuddy. I suggest to stay on 2.1.1 until the next version is released.

**Comment by irineuruiz** [comment]
Ok, thanks

**Comment by zUniQueX** [comment]
@joschi Do we want to bring a quick release for this since the `UnitOfWorkAwareProxyFactory` is unusable in 2.1.2?

**Comment by joschi** [comment]
➡️ https://github.com/dropwizard/dropwizard/releases/tag/v2.1.3
