### ISSUE TITLE
Updating to 4.0.0-beta.3 breaks AWS SES emailer code

### ISSUE THREAD

**Issue by dougboberg** [dropwizard/dropwizard#6174]
Updating from 4.0.0-beta.2 to 4.0.0-beta.3 causes the exception: `java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found`

I have created a minimal example of an emailer that works with 4.0.0-beta.2 but fails in 4.0.0-beta.3. My example uses AWS SES but because the exception is thrown from Jakarta and not an AWS library, I think this may affect other non-AWS email systems; I don't know for sure.

My guess is that beta.3 loses an assumed dependency that I have not included in my pom.xml. I tried explicitly adding various 'jakarta' related dependancies (like mail-api and activation), but nothing worked other than backing down beta.3 to beta.2. 

Any ideas? 

```
public class Emailer extends Application<Configuration> {

    public static void main(String[] args) throws Exception {
        new Emailer().run(args);
    }


    @Override
    public void run(Configuration config, Environment env) throws Exception {

        Session session = Session.getDefaultInstance(new Properties());

        // Create a new MimeMessage object.
        MimeMessage message = new MimeMessage(session);

        // Add subject, from and to lines.
        message.setSubject("Example email subject line", "UTF-8");
        InternetAddress fromAddress = new InternetAddress("CHANGE-ME@EXAMPLE.TLD");
        message.setFrom(fromAddress);
        InternetAddress toAddress = new InternetAddress("CHANGE-ME@EXAMPLE.TLD");
        message.setRecipient(Message.RecipientType.TO, toAddress);

        // Create a multipart/alternative child container.
        MimeMultipart multipart = new MimeMultipart("alternative");

        // Create a wrapper for the HTML and text parts.
        MimeBodyPart wrap = new MimeBodyPart();

        // Define the HTML part.
        List<String> htmlbody = new ArrayList<>();
        htmlbody.add("<body style=\"font-size:medium\">");
        htmlbody.add("<p>Hi there, I am an HTML message.</p>");
        htmlbody.add("</body>");
        String html = String.join("\n", htmlbody);

        MimeBodyPart htmlPart = new MimeBodyPart();
        htmlPart.setContent(html, "text/html; charset=UTF-8");
        multipart.addBodyPart(htmlPart);

        // Add the child container to the wrapper object.
        wrap.setContent(multipart);

        // Create a multipart/mixed parent container.
        MimeMultipart msg = new MimeMultipart("mixed");

        // Add the parent container to the message.
        message.setContent(msg);

        // Add the multipart/alternative part to the message.
        msg.addBodyPart(wrap);

        // Send the email.
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        message.writeTo(outputStream);
        RawMessage rawMessage = new RawMessage(ByteBuffer.wrap(outputStream.toByteArray()));

        SendRawEmailRequest rawEmailRequest = new SendRawEmailRequest(rawMessage);

        final String accesskey = Optional.ofNullable(System.getenv("AWS_ACCESS_KEY")).orElse(System.getProperty("AWS_ACCESS_KEY"));
        final String secretkey = Optional.ofNullable(System.getenv("AWS_SECRET_KEY")).orElse(System.getProperty("AWS_SECRET_KEY"));
        final AWSStaticCredentialsProvider awsCredentials = new AWSStaticCredentialsProvider(new BasicAWSCredentials(accesskey, secretkey));
        final AmazonSimpleEmailService emailServiceClient = AmazonSimpleEmailServiceClientBuilder.standard().withRegion(Regions.US_EAST_1)
                .withCredentials(awsCredentials).build();

        SendRawEmailResult result = emailServiceClient.sendRawEmail(rawEmailRequest);

        System.out.println(" SENT! " + result.toString());
    }

}
```

```
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>io.dropwizard</groupId>
			<artifactId>dropwizard-core</artifactId>
			<version>4.0.0-beta.3</version> <!-- 4.0.0-beta.2 works, 4.0.0-beta.3 does not -->
		</dependency>

		<dependency>
			<groupId>com.amazonaws</groupId>
			<artifactId>aws-java-sdk-ses</artifactId>
			<version>1.12.336</version>
		</dependency>

		<dependency>
			<groupId>com.sun.mail</groupId>
			<artifactId>jakarta.mail</artifactId>
			<version>2.0.1</version>
		</dependency>
	</dependencies>
```

```
java.lang.RuntimeException: Provider for jakarta.activation.spi.MailcapRegistryProvider cannot be found
        at jakarta.activation.FactoryFinder.find(FactoryFinder.java:90)
        at jakarta.activation.MailcapCommandMap.getImplementation(MailcapCommandMap.java:696)
        at jakarta.activation.MailcapCommandMap.loadFile(MailcapCommandMap.java:284)
        at jakarta.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:154)
        at jakarta.activation.CommandMap.getDefaultCommandMap(CommandMap.java:60)
        at jakarta.activation.DataHandler.getCommandMap(DataHandler.java:128)
        at jakarta.activation.DataHandler.getDataContentHandler(DataHandler.java:590)
        at jakarta.activation.DataHandler.writeTo(DataHandler.java:290)
        at jakarta.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316)
        at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551)
        at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
        at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
        at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
        at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
        at jakarta.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
        at jakarta.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
        at jakarta.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2246)
        at jakarta.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2206)
        at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1885)
        at jakarta.mail.internet.MimeMessage.writeTo(MimeMessage.java:1862)
        at Emailer.run(Emailer.java:80)
        at io.dropwizard.core.cli.EnvironmentCommand.run(EnvironmentCommand.java:66)
        at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:98)
        at io.dropwizard.core.cli.Cli.run(Cli.java:78)
        at io.dropwizard.core.Application.run(Application.java:94)
        at Emailer.main(Emailer.java:30)
```

**Comment by zUniQueX** [comment]
Hi @dougboberg. You've pointed out that the exception is thrown because of a missing class in the `jakarta.activation` package.

In 4.0.0-beta.3 we updated to Jackson 2.13.4. There the dependency `com.sun.activation:jakarta.activation` was removed from `com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations`. When looking at the sources of the new Jakarta Activation implementation Eclipse Angus, there is a [service file for a `MailcapRegistryProvider`](https://github.com/eclipse-ee4j/angus-activation/blob/master/activation-registry/src/main/resources/META-INF/services/jakarta.activation.spi.MailcapRegistryProvider). So you're probably missing an Activation implementation.

`com.sun.mail:jakarta.mail` should transitively pull in `com.sun.activation:jakarta.activation`. But Jackson 2.13.4 updated to `jakarta.activation:jakarta.activation-api:2.1.0`, so the version 2.0.1 of the `com.sun.activation:jakarta.activation` dependency won't be fully compatible.

So you have to decide whether to use the EE9 or EE10 Activation implementation. If you want to use the EE9 implementation, you'll have to exclude the `activation-api` from Jackson. If you're using EE10, you'll have to provide a compatible implementation for the Activation spec 2.1.

**Comment by dougboberg** [comment]
Great @zUniQueX thank you very much!

I added the following dependency and email seems to be working again: 
```
<dependency>
	<groupId>jakarta.activation</groupId>
	<artifactId>jakarta.activation-api</artifactId>
	<version>2.1.0</version>
</dependency>
```
I don't see a newer version of `com.sun.mail:jakarta.mail`, one that might pull the `jakarta.activation:jakarta.activation-api:2.1.0` that Jackson 2.13.4 (and Dropwizard 4.0.0-beta.3) is using.

Do we need to document this anywhere? Should I just close this issue? Just because it "works for me" doesn't mean there is not other work to be done. Thanks!

**Comment by zUniQueX** [comment]
Mailing is not a general functionality we provide with the framework. So I don't think we have to document this.
