### ISSUE TITLE
NoClassDefFoundError when Using SLF4J 2.x.x and LogBack 1.3.5

### ISSUE THREAD

**Issue by JKomoroski** [dropwizard/dropwizard#6439]
I have several libraries that have moved on to SLF4J 2.x, which seems to need Logback 1.3.x. The following [issue](https://github.com/dropwizard/dropwizard/issues/5944) seems to suggest managing those dependencies up, but this fails as logback seems to have [removed the jmx package for security and lack of use](https://logback.qos.ch/news.html#1.3.0).

As such on startup I'm getting the following `NoClassDefFoundError`:

```
$ java -jar app/target/app.jar server app/src/main/resources/local-config.yml
java.lang.NoClassDefFoundError: ch/qos/logback/classic/jmx/JMXConfigurator
        at io.dropwizard.logging.DefaultLoggingFactory.configure(DefaultLoggingFactory.java:153)
        at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:94)
        at io.dropwizard.cli.Cli.run(Cli.java:78)
        at io.dropwizard.Application.run(Application.java:94)
        at c.a.a.a.a.App.main(ApiAuthApp.java:19)
Caused by: java.lang.ClassNotFoundException: ch.qos.logback.classic.jmx.JMXConfigurator
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        ... 5 more
```

I have a few questions about this.

1) What is the plan to move to slf4j 2.x? Will this be landing in the Dropwizard 2.1.x release tree?
2) Does Dropwizard intend to maintain it's own JMXConfigurator to maintain backward compatibility with a move to the current logback?
3) Any suggestions on what I should be doing in the mean time?

**Comment by mattnelson** [comment]
Using slf4j-2.x is supported in 2.1.2+

see #5825

**Comment by JKomoroski** [comment]
Oof. I totally missed that wasn't current on dropwizard.

Sorry about that. Closing the issue.
