### ISSUE TITLE
Issues migrating to Dropwizard 4.0.0-beta.4

### ISSUE THREAD

**Issue by ahalma** [dropwizard/dropwizard#6764]
I'm trying to migrate my app to the latest beta of versions 4 from version 2.1.5.

 - Replacing all imports from: `javax.*` to `jakarta.*` and `io.dropwizard.*` to `io.dropwizard.core.*` went fine.
 - Disabling old plugins (dropwizard-web and a SwaggerBundle) is fine for now...
 
.. and it compiles. But when running a clean build, I run into:

```
java.lang.NoClassDefFoundError: javax/servlet/DispatcherType
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Class.java:3297)
	at java.base/java.lang.Class.getDeclaredFields(Class.java:2371)
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector._findFields(AnnotatedFieldCollector.java:73)
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collect(AnnotatedFieldCollector.java:48)
	at com.fasterxml.jackson.databind.introspect.AnnotatedFieldCollector.collectFields(AnnotatedFieldCollector.java:43)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass._fields(AnnotatedClass.java:371)
	at com.fasterxml.jackson.databind.introspect.AnnotatedClass.fields(AnnotatedClass.java:343)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector._addFields(POJOPropertiesCollector.java:499)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.collectAll(POJOPropertiesCollector.java:426)
	at com.fasterxml.jackson.databind.introspect.POJOPropertiesCollector.getJsonValueAccessor(POJOPropertiesCollector.java:272)
	at com.fasterxml.jackson.databind.introspect.BasicBeanDescription.findJsonValueAccessor(BasicBeanDescription.java:258)
	at com.fasterxml.jackson.databind.ser.BasicSerializerFactory.findSerializerByAnnotations(BasicSerializerFactory.java:391)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory._createSerializer2(BeanSerializerFactory.java:225)
	at com.fasterxml.jackson.databind.ser.BeanSerializerFactory.createSerializer(BeanSerializerFactory.java:174)
	at com.fasterxml.jackson.databind.SerializerProvider._createUntypedSerializer(SerializerProvider.java:1501)
	at com.fasterxml.jackson.databind.SerializerProvider._createAndCacheUntypedSerializer(SerializerProvider.java:1469)
	at com.fasterxml.jackson.databind.SerializerProvider.findValueSerializer(SerializerProvider.java:591)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4575)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4554)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:163)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:844)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:915)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4575)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4554)
	at io.dropwizard.configuration.ConfigurationMetadata$1.optionalProperty(ConfigurationMetadata.java:163)
	at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.depositSchemaProperty(BeanPropertyWriter.java:844)
	at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.acceptJsonFormatVisitor(BeanSerializerBase.java:915)
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.acceptJsonFormatVisitor(DefaultSerializerProvider.java:566)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4575)
	at com.fasterxml.jackson.databind.ObjectMapper.acceptJsonFormatVisitor(ObjectMapper.java:4554)
	at io.dropwizard.configuration.ConfigurationMetadata.<init>(ConfigurationMetadata.java:76)
	at io.dropwizard.configuration.BaseConfigurationFactory.<init>(BaseConfigurationFactory.java:80)
	at io.dropwizard.configuration.YamlConfigurationFactory.<init>(YamlConfigurationFactory.java:28)
	at io.dropwizard.configuration.DefaultConfigurationFactoryFactory.create(DefaultConfigurationFactoryFactory.java:22)
	at io.dropwizard.core.cli.ConfiguredCommand.parseConfiguration(ConfiguredCommand.java:137)
	at io.dropwizard.core.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.core.cli.Cli.run(Cli.java:78)
	at io.dropwizard.core.Application.run(Application.java:94)
	at net.metrique.victoria.App.main(App.java:68)
Caused by: java.lang.ClassNotFoundException: javax.servlet.DispatcherType
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 42 more

Process finished with exit code 1
```

... so still an ol `javax.servlet` somewhere? But not in my code... Any clues? Or are there migration notes available?

**Comment by joschi** [comment]
@ahalma Thanks for reporting this!

The only places where `DispatcherType` is being used in Dropwizard 4.0.0-beta.4 are https://github.com/dropwizard/dropwizard/blob/v4.0.0-beta.4/dropwizard-core/src/main/java/io/dropwizard/core/server/AbstractServerFactory.java and https://github.com/dropwizard/dropwizard/blob/v4.0.0-beta.4/dropwizard-jetty/src/main/java/io/dropwizard/jetty/ServerPushFilterFactory.java, and both refer to the correct Jakarta EE class.

Could you please post the output of `mvn dependency:tree` in your project or the equivalent in your build system?

**Comment by ahalma** [comment]
Sure! There we go...

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ victoria ---
[INFO] net.metrique:victoria:jar:1.0-SNAPSHOT
[INFO] +- io.dropwizard:dropwizard-core:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard:dropwizard-jackson:jar:4.0.0-beta.4:compile
[INFO] |  |  +- com.google.guava:guava:jar:31.1-jre:compile
[INFO] |  |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.14.2:compile
[INFO] |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.14.2:compile
[INFO] |  |  +- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.14.2:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-blackbird:jar:2.14.2:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:4.0.0-beta.4:compile
[INFO] |  |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  \- org.glassfish:jakarta.el:jar:4.0.2:compile
[INFO] |  |     \- jakarta.el:jakarta.el-api:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:4.0.0-beta.4:compile
[INFO] |  |  \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.14.2:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:4.0.0-beta.4:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:4.2.17:compile
[INFO] |  |  +- org.slf4j:jul-to-slf4j:jar:2.0.6:compile
[INFO] |  |  +- ch.qos.logback:logback-core:jar:1.4.5:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.18.0:compile
[INFO] |  |  +- io.dropwizard.logback:logback-throttling-appender:jar:1.1.9:compile
[INFO] |  |  \- org.slf4j:log4j-over-slf4j:jar:2.0.6:runtime
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:4.0.0-beta.4:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:3.0.9:runtime
[INFO] |  |  +- org.glassfish.jersey.inject:jersey-hk2:jar:3.0.9:runtime
[INFO] |  |  |  \- org.glassfish.hk2:hk2-locator:jar:3.0.3:runtime
[INFO] |  |  +- org.javassist:javassist:jar:3.29.2-GA:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey3:jar:4.2.17:compile
[INFO] |  |  +- org.glassfish.hk2:hk2-api:jar:3.0.3:compile
[INFO] |  |  |  +- org.glassfish.hk2:hk2-utils:jar:3.0.3:compile
[INFO] |  |  |  \- org.glassfish.hk2.external:aopalliance-repackaged:jar:3.0.3:compile
[INFO] |  |  \- org.glassfish.jersey.containers:jersey-container-servlet:jar:3.0.9:runtime
[INFO] |  +- io.dropwizard:dropwizard-servlets:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:4.0.0-beta.4:compile
[INFO] |  |  +- org.eclipse.jetty:jetty-servlets:jar:11.0.13:compile
[INFO] |  |  \- org.eclipse.jetty:jetty-http:jar:11.0.13:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard:dropwizard-health:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:4.2.17:compile
[INFO] |  +- io.dropwizard.metrics:metrics-annotation:jar:4.2.17:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jetty11:jar:4.2.17:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:4.2.17:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jmx:jar:4.2.17:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jakarta-servlets:jar:4.2.17:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:4.2.17:compile
[INFO] |  |  \- com.helger:profiler:jar:1.1.1:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:4.2.17:compile
[INFO] |  +- io.dropwizard:dropwizard-request-logging:jar:4.0.0-beta.4:compile
[INFO] |  |  \- ch.qos.logback:logback-access:jar:1.4.5:compile
[INFO] |  +- ch.qos.logback:logback-classic:jar:1.4.5:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.14.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.14.2:compile
[INFO] |  +- org.checkerframework:checker-qual:jar:3.31.0:compile
[INFO] |  +- jakarta.servlet:jakarta.servlet-api:jar:5.0.0:compile
[INFO] |  +- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] |  +- jakarta.ws.rs:jakarta.ws.rs-api:jar:3.0.0:compile
[INFO] |  +- net.sourceforge.argparse4j:argparse4j:jar:0.9.0:compile
[INFO] |  +- org.eclipse.jetty:jetty-security:jar:11.0.13:compile
[INFO] |  +- org.eclipse.jetty:jetty-server:jar:11.0.13:compile
[INFO] |  +- org.eclipse.jetty:jetty-servlet:jar:11.0.13:compile
[INFO] |  +- org.eclipse.jetty:jetty-util:jar:11.0.13:compile
[INFO] |  +- org.eclipse.jetty.toolchain.setuid:jetty-setuid-java:jar:1.0.4:compile
[INFO] |  +- jakarta.inject:jakarta.inject-api:jar:2.0.1.MR:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:3.0.9:compile
[INFO] |  |  \- org.glassfish.hk2:osgi-resource-locator:jar:1.0.3:compile
[INFO] |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:3.0.9:compile
[INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.4.2.Final:compile
[INFO] |  +- org.hibernate.validator:hibernate-validator:jar:7.0.5.Final:compile
[INFO] |  \- org.slf4j:slf4j-api:jar:2.0.6:compile
[INFO] +- io.dropwizard:dropwizard-jdbi3:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard:dropwizard-db:jar:4.0.0-beta.4:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-jdbc:jar:10.1.5:compile
[INFO] |  |     \- org.apache.tomcat:tomcat-juli:jar:10.1.5:compile
[INFO] |  +- org.jdbi:jdbi3-core:jar:3.37.1:compile
[INFO] |  |  \- io.leangen.geantyref:geantyref:jar:1.3.14:compile
[INFO] |  +- org.jdbi:jdbi3-sqlobject:jar:3.37.1:compile
[INFO] |  +- org.jdbi:jdbi3-guava:jar:3.37.1:compile
[INFO] |  \- io.dropwizard.metrics:metrics-jdbi3:jar:4.2.17:compile
[INFO] +- io.dropwizard:dropwizard-migrations:jar:4.0.0-beta.4:compile
[INFO] |  +- org.liquibase:liquibase-core:jar:4.19.0:compile
[INFO] |  |  +- org.yaml:snakeyaml:jar:1.33:compile
[INFO] |  |  \- com.opencsv:opencsv:jar:5.7.1:compile
[INFO] |  +- com.mattbertolini:liquibase-slf4j:jar:4.1.0:runtime
[INFO] |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:3.0.1:compile
[INFO] |     \- com.sun.activation:jakarta.activation:jar:2.0.1:compile
[INFO] +- io.dropwizard:dropwizard-testing:jar:4.0.0-beta.4:compile
[INFO] |  +- com.fasterxml.jackson.datatype:jackson-datatype-guava:jar:2.14.2:compile
[INFO] |  +- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-json-provider:jar:2.14.2:compile
[INFO] |  |  +- com.fasterxml.jackson.jakarta.rs:jackson-jakarta-rs-base:jar:2.14.2:compile
[INFO] |  |  \- com.fasterxml.jackson.module:jackson-module-jakarta-xmlbind-annotations:jar:2.14.2:compile
[INFO] |  +- org.eclipse.jetty:jetty-io:jar:11.0.13:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:3.0.9:compile
[INFO] |  +- org.glassfish.jersey.connectors:jersey-apache5-connector:jar:3.0.9:compile
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.2.1:compile
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.2:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:3.0.9:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-server:jar:3.0.9:compile
[INFO] |  +- org.glassfish.jersey.test-framework:jersey-test-framework-core:jar:3.0.9:compile
[INFO] |  |  +- org.glassfish.jersey.media:jersey-media-jaxb:jar:3.0.9:compile
[INFO] |  |  \- org.hamcrest:hamcrest:jar:2.2:compile
[INFO] |  +- org.glassfish.jersey.test-framework.providers:jersey-test-framework-provider-inmemory:jar:3.0.9:compile
[INFO] |  \- jakarta.activation:jakarta.activation-api:jar:2.0.1:compile
[INFO] +- io.dropwizard:dropwizard-assets:jar:4.0.0-beta.4:compile
[INFO] +- io.dropwizard:dropwizard-forms:jar:4.0.0-beta.4:compile
[INFO] |  \- org.glassfish.jersey.media:jersey-media-multipart:jar:3.0.9:compile
[INFO] |     \- org.jvnet.mimepull:mimepull:jar:1.9.13:compile
[INFO] +- io.dropwizard:dropwizard-views:jar:4.0.0-beta.4:compile
[INFO] +- io.dropwizard:dropwizard-client:jar:4.0.0-beta.4:compile
[INFO] |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.2.1:compile
[INFO] |  \- io.dropwizard.metrics:metrics-httpclient5:jar:4.2.17:compile
[INFO] +- io.dropwizard:dropwizard-auth:jar:4.0.0-beta.4:compile
[INFO] |  +- io.dropwizard.metrics:metrics-caffeine:jar:4.2.17:compile
[INFO] |  +- com.github.ben-manes.caffeine:caffeine:jar:3.1.4:compile
[INFO] |  \- jakarta.annotation:jakarta.annotation-api:jar:2.0.0:compile
[INFO] +- io.dropwizard.modules:dropwizard-web:jar:1.5.0:compile
[INFO] +- org.bitbucket.b_c:jose4j:jar:0.9.3:compile
[INFO] +- com.smoketurner:dropwizard-swagger:jar:2.0.12-1:compile
[INFO] |  +- io.dropwizard:dropwizard-views-freemarker:jar:2.0.12:compile
[INFO] |  |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] |  |  \- org.freemarker:freemarker:jar:2.3.30:compile
[INFO] |  \- io.swagger:swagger-jersey2-jaxrs:jar:1.6.2:compile
[INFO] |     \- io.swagger:swagger-jaxrs:jar:1.6.2:compile
[INFO] |        +- io.swagger:swagger-core:jar:1.6.2:compile
[INFO] |        |  \- io.swagger:swagger-models:jar:1.6.2:compile
[INFO] |        |     \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO] |        \- org.reflections:reflections:jar:0.9.11:compile
[INFO] +- org.apache.logging.log4j:log4j-core:jar:2.19.0:compile
[INFO] |  \- org.apache.logging.log4j:log4j-api:jar:2.19.0:compile
[INFO] +- org.apache.commons:commons-csv:jar:1.10.0:compile
[INFO] +- commons-io:commons-io:jar:2.11.0:compile
[INFO] +- org.postgresql:postgresql:jar:42.5.3:compile
[INFO] +- org.junit.jupiter:junit-jupiter:jar:5.9.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter-api:jar:5.9.2:test
[INFO] |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  \- org.junit.platform:junit-platform-commons:jar:1.9.2:test
[INFO] |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.9.2:test
[INFO] |     \- org.junit.platform:junit-platform-engine:jar:1.9.2:test
[INFO] +- org.junit.jupiter:junit-jupiter-params:jar:5.9.2:test
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] +- org.geotools:gt-main:jar:28.1:compile
[INFO] |  +- org.geotools:gt-referencing:jar:28.1:compile
[INFO] |  |  +- org.ejml:ejml-ddense:jar:0.41:compile
[INFO] |  |  |  \- org.ejml:ejml-core:jar:0.41:compile
[INFO] |  |  +- commons-pool:commons-pool:jar:1.5.4:compile
[INFO] |  |  +- org.geotools:gt-metadata:jar:28.1:compile
[INFO] |  |  |  +- org.geotools:gt-opengis:jar:28.1:compile
[INFO] |  |  |  |  \- systems.uom:systems-common:jar:2.0.2:compile
[INFO] |  |  |  |     +- tech.units:indriya:jar:2.0.2:compile
[INFO] |  |  |  |     |  +- tech.uom.lib:uom-lib-common:jar:2.0:compile
[INFO] |  |  |  |     |  \- javax.inject:javax.inject:jar:1:compile
[INFO] |  |  |  |     +- si.uom:si-quantity:jar:2.0.1:compile
[INFO] |  |  |  |     \- si.uom:si-units:jar:2.0.1:compile
[INFO] |  |  |  \- org.geotools.ogc:net.opengis.ows:jar:28.1:compile
[INFO] |  |  |     +- org.geotools.ogc:org.w3.xlink:jar:28.1:compile
[INFO] |  |  |     +- org.eclipse.emf:org.eclipse.emf.common:jar:2.15.0:compile
[INFO] |  |  |     +- org.eclipse.emf:org.eclipse.emf.ecore:jar:2.15.0:compile
[INFO] |  |  |     \- org.eclipse.emf:org.eclipse.emf.ecore.xmi:jar:2.15.0:compile
[INFO] |  |  +- it.geosolutions.jgridshift:jgridshift-core:jar:1.3:compile
[INFO] |  |  \- net.sf.geographiclib:GeographicLib-Java:jar:1.49:compile
[INFO] |  +- org.geotools:gt-http:jar:28.1:compile
[INFO] |  +- org.locationtech.jts:jts-core:jar:1.19.0:compile
[INFO] |  +- org.apache.commons:commons-text:jar:1.10.0:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-core:jar:2.13.2:compile
[INFO] |  +- com.google.re2j:re2j:jar:1.6:compile
[INFO] |  \- javax.media:jai_core:jar:1.1.3:compile
[INFO] +- org.geotools:gt-geojson:jar:28.1:compile
[INFO] |  +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] |  \- org.apache.commons:commons-lang3:jar:3.8.1:compile
[INFO] +- org.geotools:gt-shapefile:jar:28.1:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.12.372:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.12.372:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-core:jar:1.12.372:compile
[INFO] |  |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  |  +- org.apache.httpcomponents:httpclient:jar:4.5.13:compile
[INFO] |  |  |  \- org.apache.httpcomponents:httpcore:jar:4.4.13:compile
[INFO] |  |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.12.6:compile
[INFO] |  |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.12.372:compile
[INFO] +- javax.measure:unit-api:jar:2.1.3:compile
[INFO] +- tec.units:unit-ri:jar:1.0.3:compile
[INFO] |  \- tec.uom.lib:uom-lib-common:jar:1.0.2:compile
[INFO] +- org.graalvm.js:js:jar:22.3.1:compile
[INFO] |  +- org.graalvm.regex:regex:jar:22.3.1:compile
[INFO] |  +- org.graalvm.truffle:truffle-api:jar:22.3.1:compile
[INFO] |  +- org.graalvm.sdk:graal-sdk:jar:22.3.1:compile
[INFO] |  \- com.ibm.icu:icu4j:jar:71.1:compile
[INFO] +- org.graalvm.js:js-scriptengine:jar:22.3.1:compile
[INFO] +- org.apache.poi:poi:jar:5.2.3:compile
[INFO] |  +- commons-codec:commons-codec:jar:1.15:compile
[INFO] |  +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] |  +- org.apache.commons:commons-math3:jar:3.6.1:compile
[INFO] |  \- com.zaxxer:SparseBitSet:jar:1.2:compile
[INFO] +- org.apache.poi:poi-ooxml:jar:5.2.3:compile
[INFO] |  +- org.apache.poi:poi-ooxml-lite:jar:5.2.3:compile
[INFO] |  +- org.apache.xmlbeans:xmlbeans:jar:5.1.1:compile
[INFO] |  +- org.apache.commons:commons-compress:jar:1.21:compile
[INFO] |  \- com.github.virtuald:curvesapi:jar:1.07:compile
[INFO] +- org.apache.tika:tika-core:jar:2.7.0:compile
[INFO] +- org.apache.tika:tika-parsers-standard-package:jar:2.7.0:compile
[INFO] |  +- org.apache.tika:tika-parser-apple-module:jar:2.7.0:compile
[INFO] |  |  +- org.apache.tika:tika-parser-zip-commons:jar:2.7.0:compile
[INFO] |  |  \- com.googlecode.plist:dd-plist:jar:1.26:compile
[INFO] |  +- org.apache.tika:tika-parser-audiovideo-module:jar:2.7.0:compile
[INFO] |  |  \- com.drewnoakes:metadata-extractor:jar:2.18.0:compile
[INFO] |  |     \- com.adobe.xmp:xmpcore:jar:6.1.11:compile
[INFO] |  +- org.apache.tika:tika-parser-cad-module:jar:2.7.0:compile
[INFO] |  +- org.apache.tika:tika-parser-code-module:jar:2.7.0:compile
[INFO] |  |  +- org.codelibs:jhighlight:jar:1.1.0:compile
[INFO] |  |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:9.4:compile
[INFO] |  |  +- com.epam:parso:jar:2.0.14:compile
[INFO] |  |  \- org.tallison:jmatio:jar:1.5:compile
[INFO] |  +- org.apache.tika:tika-parser-crypto-module:jar:2.7.0:compile
[INFO] |  |  +- org.bouncycastle:bcmail-jdk18on:jar:1.72:compile
[INFO] |  |  |  +- org.bouncycastle:bcutil-jdk18on:jar:1.72:compile
[INFO] |  |  |  \- org.bouncycastle:bcpkix-jdk18on:jar:1.72:compile
[INFO] |  |  \- org.bouncycastle:bcprov-jdk18on:jar:1.72:compile
[INFO] |  +- org.apache.tika:tika-parser-digest-commons:jar:2.7.0:compile
[INFO] |  +- org.apache.tika:tika-parser-font-module:jar:2.7.0:compile
[INFO] |  |  \- org.apache.pdfbox:fontbox:jar:2.0.27:compile
[INFO] |  +- org.apache.tika:tika-parser-html-module:jar:2.7.0:compile
[INFO] |  +- org.apache.tika:tika-parser-image-module:jar:2.7.0:compile
[INFO] |  |  +- com.github.jai-imageio:jai-imageio-core:jar:1.4.0:compile
[INFO] |  |  \- org.apache.pdfbox:jbig2-imageio:jar:3.0.4:compile
[INFO] |  +- org.apache.tika:tika-parser-mail-module:jar:2.7.0:compile
[INFO] |  |  \- org.apache.tika:tika-parser-mail-commons:jar:2.7.0:compile
[INFO] |  |     +- org.apache.james:apache-mime4j-core:jar:0.8.9:compile
[INFO] |  |     \- org.apache.james:apache-mime4j-dom:jar:0.8.9:compile
[INFO] |  +- org.apache.tika:tika-parser-microsoft-module:jar:2.7.0:compile
[INFO] |  |  +- com.pff:java-libpst:jar:0.9.3:compile
[INFO] |  |  +- org.apache.poi:poi-scratchpad:jar:5.2.3:compile
[INFO] |  |  +- com.healthmarketscience.jackcess:jackcess:jar:4.0.5:compile
[INFO] |  |  \- com.healthmarketscience.jackcess:jackcess-encrypt:jar:4.0.2:compile
[INFO] |  +- org.slf4j:jcl-over-slf4j:jar:2.0.6:compile
[INFO] |  +- org.apache.tika:tika-parser-miscoffice-module:jar:2.7.0:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.6:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.6:compile
[INFO] |  |     \- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  +- org.apache.tika:tika-parser-news-module:jar:2.7.0:compile
[INFO] |  |  \- com.rometools:rome:jar:1.18.0:compile
[INFO] |  |     +- com.rometools:rome-utils:jar:1.18.0:compile
[INFO] |  |     \- org.jdom:jdom2:jar:2.0.6.1:compile
[INFO] |  +- org.apache.tika:tika-parser-ocr-module:jar:2.7.0:compile
[INFO] |  |  \- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  +- org.apache.tika:tika-parser-pdf-module:jar:2.7.0:compile
[INFO] |  |  +- org.apache.pdfbox:pdfbox:jar:2.0.27:compile
[INFO] |  |  +- org.apache.pdfbox:pdfbox-tools:jar:2.0.27:compile
[INFO] |  |  \- org.apache.pdfbox:jempbox:jar:1.8.17:compile
[INFO] |  +- org.apache.tika:tika-parser-pkg-module:jar:2.7.0:compile
[INFO] |  |  +- org.tukaani:xz:jar:1.9:compile
[INFO] |  |  +- org.brotli:dec:jar:0.1.2:compile
[INFO] |  |  \- com.github.junrar:junrar:jar:7.5.4:compile
[INFO] |  +- org.apache.tika:tika-parser-text-module:jar:2.7.0:compile
[INFO] |  |  \- com.github.albfernandez:juniversalchardet:jar:2.4.0:compile
[INFO] |  +- org.apache.tika:tika-parser-webarchive-module:jar:2.7.0:compile
[INFO] |  |  \- org.netpreserve:jwarc:jar:0.21.0:compile
[INFO] |  +- org.apache.tika:tika-parser-xml-module:jar:2.7.0:compile
[INFO] |  |  \- xerces:xercesImpl:jar:2.12.2:compile
[INFO] |  |     \- xml-apis:xml-apis:jar:1.4.01:compile
[INFO] |  +- org.apache.tika:tika-parser-xmp-commons:jar:2.7.0:compile
[INFO] |  |  \- org.apache.pdfbox:xmpbox:jar:2.0.27:compile
[INFO] |  +- org.gagravarr:vorbis-java-tika:jar:0.8:compile
[INFO] |  \- org.gagravarr:vorbis-java-core:jar:0.8:compile
[INFO] +- org.apache.avro:avro:jar:1.11.1:compile
[INFO] \- org.jsoup:jsoup:jar:1.15.3:compile
```

**Comment by zUniQueX** [comment]
There are `provided` dependencies for an older servlet api. E.g. `dropwizard-swagger` uses `swagger-jaxrs2`, which declares a provided dependency on servlet API 4.x.

**Comment by jplock** [comment]
I haven’t had time to update dropwizard-swagger to 4.0 yet. I’d except a PR for that though.

**Comment by ahalma** [comment]
@zUniQueX , I see your point of those dependencies... 

I can't easily exclude `dropwizard-swagger` since my models and resources are drowning in `io.swagger.annotations` (`@ApiModelProperty`, `@ApiOperation`, ...). Otherwise it is easier to see if that solves the initial issues.

@jplock , I'm very happy to see you released a new dropwizard-swagger version recently! I consider it a core module for my projects. I'm not sure I'm the best candidate to help out with PR for an upgrade to 4.0, but let me start by cloning the latest repo ;)

**Comment by joschi** [comment]
> I can't easily exclude `dropwizard-swagger` since my models and resources are drowning in ?`io.swagger.annotations` (`@ApiModelProperty`, `@ApiOperation`, ...). Otherwise it is easier to see if that solves the initial issues.

I'm afraid you won't be able to upgrade to Dropwizard 4.0.x (Jakarta EE), but have to go with Dropwizard 3.0.x (Java EE) because the Swagger libraries do not support the new namespaces yet.

https://github.com/swagger-api/swagger-core/issues/3836

**Comment by zUniQueX** [comment]
Seems like the [latest version](https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-jaxrs2-jakarta/2.2.8) of the `jakarta` artifact ships with Jackson 2.14.x, so the issue might be resolved.

**Comment by ahalma** [comment]
> I haven’t had time to update dropwizard-swagger to 4.0 yet. I’d except a PR for that though.

I looked at it, but don't feel qualified to poke around and simply hope it is the right approach...
