### ISSUE TITLE
dropwizard 0.7.1 syslog throws java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by wendell-bu** [dropwizard/dropwizard#698]
When enable logging appenders syslog in yaml, like
    - type: syslog
      host: localhost
      port: 514
      facility: local0
      threshold: ALL
version 0.7.1 exit with following exception when start the server,

```
Exception in thread "main" java.lang.AbstractMethodError: ch.qos.logback.core.net.SyslogAppenderBase.createOutputStream()Lch/qos/logback/core/net/SyslogOutputStream;
    at ch.qos.logback.core.net.SyslogAppenderBase.start(SyslogAppenderBase.java:54)
    at ch.qos.logback.classic.net.SyslogAppender.start(SyslogAppender.java:48)
    at io.dropwizard.logging.SyslogAppenderFactory.build(SyslogAppenderFactory.java:214)
    at io.dropwizard.logging.LoggingFactory.configure(LoggingFactory.java:110)
    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:72)
    at io.dropwizard.cli.Cli.run(Cli.java:70)
    at io.dropwizard.Application.run(Application.java:72)
    at com.cisco.cws.siem.SiemConfigurationService.main(SiemConfigurationService.java:40)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

But it works just downgrade dropwizard to version 0.7.0

**Comment by V0L0DYMYR** [comment]
I've got similar issue, when I tried to migrate from version 0.9.2 to 1.0.0.

```
Exception in thread "main" java.lang.AbstractMethodError
	at ch.qos.logback.core.pattern.PatternLayoutBase.start(PatternLayoutBase.java:88)
	at ch.qos.logback.access.PatternLayout.start(PatternLayout.java:210)
	at io.dropwizard.logging.AbstractAppenderFactory.buildLayout(AbstractAppenderFactory.java:197)
	at io.dropwizard.logging.ConsoleAppenderFactory.build(ConsoleAppenderFactory.java:102)
	at io.dropwizard.request.logging.LogbackAccessRequestLogFactory.build(LogbackAccessRequestLogFactory.java:78)
	at io.dropwizard.server.AbstractServerFactory.addRequestLog(AbstractServerFactory.java:580)
	at io.dropwizard.server.DefaultServerFactory.build(DefaultServerFactory.java:179)
	at io.dropwizard.cli.ServerCommand.run(ServerCommand.java:49)
	at io.dropwizard.cli.EnvironmentCommand.run(EnvironmentCommand.java:44)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:85)
	at io.dropwizard.cli.Cli.run(Cli.java:75)
	at io.dropwizard.Application.run(Application.java:79)
	at ua.codegym.xunit.application.App.main(App.java:62)
```

**Comment by evnm** [comment]
@V0L0DYMYR, can you provide more information on the situation in which you see that error? As @joschi asked in response to the initial issue, can you check what version of Logback you're pulling in, please? Providing the output of `mvn dependency:tree` could be helpful, for instance.

Have you tried running `mvn clean` before packaging the project?

**Comment by V0L0DYMYR** [comment]
Solved! I find out that I have two different versions of Logback in my dependency tree. When I  exclude one of them, it start working.
