### ISSUE TITLE
NPE in Jersey Client with gzipEnabled set to false

### ISSUE THREAD

**Issue by sldab** [dropwizard/dropwizard#7101]
The Jersey client in Dropwizard 4.0.0 throws a NPE when sending requests without a `Content-Encoding` (i.e. when `gzipEnabled` is set to `false`).

```java
java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.glassfish.jersey.client.ClientRequest.getRequestHeader(String)" is null
 at io.dropwizard.client.DropwizardApacheConnector$JerseyRequestHttpEntity.<init>(DropwizardApacheConnector.java:222)
 at io.dropwizard.client.DropwizardApacheConnector.getHttpEntity(DropwizardApacheConnector.java:175)
 at io.dropwizard.client.DropwizardApacheConnector.buildApacheRequest(DropwizardApacheConnector.java:121)
 at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:87)
 ... 94 common frames omitted
```

This is due to `clientRequest.getRequestHeader(HttpHeaders.CONTENT_ENCODING)` returning `null` in line 222 of `DropwizardApacheConnector`:
```java
clientRequest.getRequestHeader(HttpHeaders.CONTENT_ENCODING).stream().findFirst().orElse(null)
```
**Fix:**
```
Optional
  .ofNullable(clientRequest.getRequestHeader(HttpHeaders.CONTENT_ENCODING))
  .map(contentEncodings -> contentEncodings.get(0))
  .orElse(null)
```

**Comment by zUniQueX** [comment]
Hi @sldab. We have a [test](https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-client/src/test/java/io/dropwizard/client/JerseyClientIntegrationTest.java#L171-L197) without gzip in the `dropwizard-client` module. The test runs fine and when debugging into the line you mentioned, there is an empty list returned instead of a `null` value.

Do you manually override any dependencies, especially the Jersey version? Please supply an output of `mvn dependency:tree`.

**Comment by sldab** [comment]
Hi @zUniQueX, I do not override any dependencies. Please see my output of

`mvn dependency:tree | grep -P '(dropwizard|jersey|apache)' | grep -v ':test$'`

```
[INFO] +- io.dropwizard:dropwizard-core:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-util:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-jackson:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-validation:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-configuration:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-logging:jar:4.0.0:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-logback:jar:4.2.18:compile
[INFO] |  |  +- io.dropwizard.logback:logback-throttling-appender:jar:1.1.9:compile
[INFO] |  +- io.dropwizard:dropwizard-metrics:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-jersey:jar:4.0.0:compile
[INFO] |  |  +- org.glassfish.jersey.ext:jersey-metainf-services:jar:3.1.1:runtime
[INFO] |  |  +- org.glassfish.jersey.inject:jersey-hk2:jar:3.1.1:runtime
[INFO] |  |  +- io.dropwizard.metrics:metrics-jersey3:jar:4.2.18:compile
[INFO] |  |  \- org.glassfish.jersey.containers:jersey-container-servlet:jar:3.1.1:runtime
[INFO] |  +- io.dropwizard:dropwizard-servlets:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-jetty:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-lifecycle:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-health:jar:4.0.0:compile
[INFO] |  +- io.dropwizard.metrics:metrics-core:jar:4.2.18:compile
[INFO] |  +- io.dropwizard.metrics:metrics-annotation:jar:4.2.18:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jetty11:jar:4.2.18:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jvm:jar:4.2.18:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jmx:jar:4.2.18:compile
[INFO] |  +- io.dropwizard.metrics:metrics-jakarta-servlets:jar:4.2.18:compile
[INFO] |  |  +- io.dropwizard.metrics:metrics-json:jar:4.2.18:compile
[INFO] |  +- io.dropwizard.metrics:metrics-healthchecks:jar:4.2.18:compile
[INFO] |  +- io.dropwizard:dropwizard-request-logging:jar:4.0.0:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-common:jar:3.1.1:compile
[INFO] |  +- org.glassfish.jersey.ext:jersey-bean-validation:jar:3.1.1:compile
[INFO] +- io.dropwizard:dropwizard-client:jar:4.0.0:compile
[INFO] |  +- org.glassfish.jersey.core:jersey-client:jar:3.1.1:compile
[INFO] |  +- org.apache.httpcomponents.client5:httpclient5:jar:5.1.4:compile
[INFO] |  |  \- org.apache.httpcomponents.core5:httpcore5-h2:jar:5.1.5:compile
[INFO] |  +- org.apache.httpcomponents.core5:httpcore5:jar:5.1.5:compile
[INFO] |  \- io.dropwizard.metrics:metrics-httpclient5:jar:4.2.18:compile
[INFO] +- io.dropwizard:dropwizard-views-mustache:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-views:jar:4.0.0:compile
[INFO] |  \- org.glassfish.jersey.core:jersey-server:jar:3.1.1:compile
[INFO] +- io.dropwizard:dropwizard-migrations:jar:4.0.0:compile
[INFO] |  +- io.dropwizard:dropwizard-db:jar:4.0.0:compile
[INFO] |  |  \- org.apache.tomcat:tomcat-jdbc:jar:10.1.8:compile
[INFO] |  |     \- org.apache.tomcat:tomcat-juli:jar:10.1.8:compile
[INFO] +- io.dropwizard:dropwizard-jdbi3:jar:4.0.0:compile
[INFO] |  \- io.dropwizard.metrics:metrics-jdbi3:jar:4.2.18:compile
[INFO] +- zone.dragon.dropwizard:dropwizard-hk2:jar:4.0.1:compile
[INFO] +- org.apache.commons:commons-collections4:jar:4.4:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] +- org.apache.commons:commons-text:jar:1.10.0:compile
[INFO] +- io.prometheus:simpleclient_dropwizard:jar:0.16.0:compile
[INFO] +- com.smoketurner.dropwizard:graphql-core:jar:4.0.0-1:compile
[INFO] |  +- io.dropwizard:dropwizard-assets:jar:4.0.0:compile
[INFO] |  +- org.glassfish.jersey.containers:jersey-container-servlet-core:jar:3.1.1:compile
```

**Comment by zUniQueX** [comment]
Hi @sldab. Your log reports that Jersey 3.1.1 is used. However, Dropwizard 4.0.0 ships with 3.0.9. So there is actually something overriding your dependencies there.

Jersey 3.1.x is part of Jakarta EE 10 and currently not supported by Dropwizard yet.

**Comment by sldab** [comment]
@zUniQueX, thanks for your help. A dependency with scope **import** in my parent pom was the culprit.  Apparently maven is not capable of correctly displaying the origin of imported dependencies.
