### ISSUE TITLE
javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?

### ISSUE THREAD

**Issue by khslsahan** [dropwizard/dropwizard#7122]
I get this error when use proxy my config 
```
jerseyClientConfiguration:
  timeout: 150000ms
  connectionTimeout: 150000ms
  minThreads: 1
  maxThreads: 128
  workQueueSize: 8
  gzipEnabled: false
  gzipEnabledForRequests: false
  chunkedEncodingEnabled: false
  proxy:
    host: x.x.x.x
    port: 9018
    scheme: https
    nonProxyHosts: ["172.*","10.*", "192.168.*", "localhost"] 
``` 

I get error as
```
javax.ws.rs.ProcessingException: javax.net.ssl.SSLException: Unrecognized SSL message, plaintext connection?
	at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:110) ~[dropwizard-client-0.9.2.jar:0.9.2]
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:255) ~[jersey-client-2.22.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$2.call(JerseyInvocation.java:700) ~[jersey-client-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.internal.Errors.process(Errors.java:228) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444) [jersey-common-2.22.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:696) ~[jersey-client-2.22.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:448) ~[jersey-client-2.22.1.jar:na]
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:349) ~[jersey-client-2.22.1.jar:na]
	at hms.custom.m1.prepaidportal.notification.connectors.fcm.FireBaseConnector.sendFcmMessage(FireBaseConnector.java:56) [notification-api-5.5.7.jar:na]
	at hms.custom.m1.prepaidportal.notification.connectors.fcm.FireBaseConnector.sendNotification(FireBaseConnector.java:47) [notification-api-5.5.7.jar:na]
	at hms.custom.m1.prepaidportal.notification.services.impl.FcmNotificationServiceImpl.sendFcmNotification(FcmNotificationServiceImpl.java:110) [notification-api-5.5.7.jar:na]
	at hms.custom.m1.prepaidportal.notification.services.impl.FcmNotificationServiceImpl.sendMessageByTemplate(FcmNotificationServiceImpl.java:92) [notification-api-5.5.7.jar:na]
	at hms.custom.m1.prepaidportal.notification.services.impl.NotificationAgentIdentifierServiceImpl.sendMessageByTemplate(NotificationAgentIdentifierServiceImpl.java:166) [notification-api-5.5.7.jar:na]
```

**Comment by joschi** [comment]
What kind of proxy is the server you've configured in `jerseyClientConfiguration.proxy`?
Does it support HTTPS? Does it transparently downgrade proxied HTTPS connections to HTTP?

**Comment by khslsahan** [comment]
thanks yes that support only http but I have used https
