### ISSUE TITLE
Server rejects certain sizes of streamed request bodies

### ISSUE THREAD

**Issue by Mahoney** [dropwizard/dropwizard#7275]
DropWizard 4.0.1, Jetty 11.0.15, Java 17

When posting certain body sizes to a Dropwizard server via the Dropwizard configured Jersey client, the server returns a 500 because of an exception thrown inside Jetty:
```
127.0.0.1 - - [28/Jun/2023:16:49:19 +0000] "POST /test HTTP/1.1" 500 110 "-" "gzip-interceptor-bug (RQZNuukVWd)" 1
ERROR [2023-06-28 16:49:19,766] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 20dae4a5c6058e23
! java.io.IOException: Interceptor org.eclipse.jetty.server.handler.gzip.GzipHttpInputInterceptor@1aa1d204 did not consume any of the 8 remaining byte(s) of content
! at org.eclipse.jetty.server.AsyncContentProducer.intercept(AsyncContentProducer.java:449)
! at org.eclipse.jetty.server.AsyncContentProducer.transformRawContent(AsyncContentProducer.java:378)
! at org.eclipse.jetty.server.AsyncContentProducer.nextTransformedContent(AsyncContentProducer.java:368)
! at org.eclipse.jetty.server.AsyncContentProducer.nextContent(AsyncContentProducer.java:250)
! at org.eclipse.jetty.server.BlockingContentProducer.nextContent(BlockingContentProducer.java:103)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:287)
! at org.eclipse.jetty.server.HttpInput.read(HttpInput.java:272)
! at org.glassfish.jersey.message.internal.EntityInputStream.read(EntityInputStream.java:79)
! at java.base/java.io.InputStream.readNBytes(InputStream.java:409)
! at java.base/java.io.InputStream.readAllBytes(InputStream.java:346)
! at foo.TestResource.absorbBytes(TestResource.java:20)
```

There's a reproduction repo here:
https://github.com/Mahoney-bug-examples/gzip-interceptor-bug

**Comment by Mahoney** [comment]
Resource:

```java
@Path("/test")
public class TestResource {

    @POST
    @Consumes(MediaType.APPLICATION_OCTET_STREAM)
    @Produces(MediaType.APPLICATION_JSON)
    public Response absorbBytes(InputStream bytes) throws IOException {
        return Response.ok(Map.of("bytes_received", bytes.readAllBytes().length)).build();
    }
}
```
https://github.com/Mahoney-bug-examples/gzip-interceptor-bug/blob/main/src/main/java/foo/TestResource.java

Test:
```java
@ExtendWith(DropwizardExtensionsSupport.class)
public class RequestSizeTest {

    private static final DropwizardAppExtension<BugConfiguration> APP = new DropwizardAppExtension<>(
            BugApplication.class
    );

    @ParameterizedTest
    @ValueSource(ints = {
            8191,
            8192,
            8193,
            8194,
            8195,
            // many others, redacted for length...
    })
    void can_post_arbitrary_body_sizes_to_the_server(int bytesToSend) throws Exception {

        var body = new StreamingOutput() {
            @Override
            public void write(OutputStream output) throws IOException, WebApplicationException {
                for (int i = 0; i < bytesToSend; i++) {
                    output.write(1);
                }
            }
        };

        try (Response response = new JerseyClientBuilder(APP.getEnvironment())
                .build(RandomStringUtils.randomAlphabetic(10))
                .target("http://localhost:" + APP.getLocalPort())
                .path("/test")
                .request()
                .post(Entity.entity(body, APPLICATION_OCTET_STREAM))) {

            var data = response.readEntity(String.class);
            assert response.getStatus() == 200 : data;
            assertEquals(Map.of("bytes_received", bytesToSend), new ObjectMapper().readValue(data, Map.class));
        }
    }
}
```
https://github.com/Mahoney-bug-examples/gzip-interceptor-bug/blob/main/src/test/java/foo/RequestSizeTest.java

**Comment by Mahoney** [comment]
(I asked about this in https://github.com/dropwizard/dropwizard/discussions/7274 , but I'm now more confident it's either a Dropwizard or a Jetty bug, so moving it to an issue.)

**Comment by Mahoney** [comment]
I raised https://github.com/eclipse/jetty.project/issues/9990 on the Jetty project because it seems likely to be a Jetty issue - I'll keep this open until we know for sure where the problem is.

**Comment by Mahoney** [comment]
Jetty have accepted it as their bug, I'll leave this open to cover the upgrades to the fixed 10.x and 11.x Jetty versions

**Comment by Mahoney** [comment]
Jetty 11.0.16 (for Dropwizard 4.x) and 10.0.16 (for Dropwizard 3.x) are now published, so it should be possible to fix this in Dropwizard now.

**Comment by zUniQueX** [comment]
Hi @Mahoney. Jetty is already bumped to 11.0.16 in the `release/4.0.x` branch. So this will be included in the next release.
