### ISSUE TITLE
Content-Encoding header is null but not expected

### ISSUE THREAD

**Issue by danjee** [dropwizard/dropwizard#7319]
`DropwizardApacheConnector` has the private class BufferedJerseyRequestHttpEntity that expects a `Content-Encoding` header that is not suppose to be mandatory.

**Comment by zUniQueX** [comment]
Hi @danjee. Dropwizard doesn't need the header to be set.

The constructor of `AbstractHttpEntity` expects a parameter for the content encoding. Since the entity is processed by the Jersey MBWs, Dropwizard doesn't know the content encoding. So we utilize the header, if present, to set the encoding there.

The JavaDoc of `EntityDetails#getContentEncoding()` states:
> Returns content encoding of the entity, if known.

So if the header isn't present, we simply don't set the encoding.

**Comment by Mahoney** [comment]
https://github.com/dropwizard/dropwizard/blob/release/4.0.x/dropwizard-client/src/main/java/io/dropwizard/client/DropwizardApacheConnector.java#L222 is throwing a `NullPointerException` for me because `clientRequest.getRequestHeader(HttpHeaders.CONTENT_ENCODING)` is return null.

Causing code:

```java
package foo;

import io.dropwizard.client.JerseyClientBuilder;
import io.dropwizard.client.JerseyClientConfiguration;
import io.dropwizard.core.setup.Environment;
import jakarta.ws.rs.client.Client;
import jakarta.ws.rs.client.Entity;

public class Main {

    public static void main(String[] args) {
    
        JerseyClientConfiguration clientConfiguration = new JerseyClientConfiguration();
        clientConfiguration.setGzipEnabledForRequests(false);
    
        Client client = (new JerseyClientBuilder(new Environment("env")))
                .using(clientConfiguration)
                .build("whatever");
    
        client
                .target("https://www.example.com")
                .request()
                .post(Entity.text(""));
    }
}

```

Full stack:
```
Exception in thread "main" jakarta.ws.rs.ProcessingException: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.glassfish.jersey.client.ClientRequest.getRequestHeader(String)" is null
	at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:105)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$0(JerseyInvocation.java:662)
	at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:697)
	at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:691)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
	at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:691)
	at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:661)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:439)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:345)
	at foo.Main.main(Main.java:23)
Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.stream()" because the return value of "org.glassfish.jersey.client.ClientRequest.getRequestHeader(String)" is null
	at io.dropwizard.client.DropwizardApacheConnector$JerseyRequestHttpEntity.<init>(DropwizardApacheConnector.java:222)
	at io.dropwizard.client.DropwizardApacheConnector.getHttpEntity(DropwizardApacheConnector.java:175)
	at io.dropwizard.client.DropwizardApacheConnector.buildApacheRequest(DropwizardApacheConnector.java:121)
	at io.dropwizard.client.DropwizardApacheConnector.apply(DropwizardApacheConnector.java:87)
	... 13 more
```

**Comment by Mahoney** [comment]
Raised https://github.com/dropwizard/dropwizard/pull/7532 if you want it
