### ISSUE TITLE
[0.8.0 migration] No injection source found for a parameter

### ISSUE THREAD

**Issue by Toilal** [dropwizard/dropwizard#783]
I try to migrate my app from 0.7.x to 0.8.x (github master). But this method doesn't pass the jersey model validation:

``` java
@Path("/users")
@Produces(MediaType.APPLICATION_JSON)
public class UserResource {
    ...

    @POST
    @Path("/changePassword")
    @Consumes(MediaType.APPLICATION_JSON)
    public void changePassword(@Auth User user, String password) {
        ...
    }

}
```

Error message is about 10 meters wide and unreadable, but short version says : `No injection source found for a parameter of type public void com.pragmasphere.tictac.planning.services.auth.UserResource.changePassword(com.pragmasphere.tictac.planning.services.auth.User,java.lang.String) at index 0.`

Here is the full stacktrace:

```
Caused by: org.glassfish.jersey.server.model.ModelValidationException: Validation of the application resource model has failed during application initialization.
[[FATAL] No injection source found for a parameter of type public void com.pragmasphere.tictac.planning.services.auth.UserResource.changePassword(com.pragmasphere.tictac.planning.services.auth.User,java.lang.String) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.auth.UserResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@2582b0ef]}, definitionMethod=public void com.pragmasphere.tictac.planning.services.auth.UserResource.changePassword(com.pragmasphere.tictac.planning.services.auth.User,java.lang.String), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=class java.lang.String, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public void com.pragmasphere.tictac.planning.services.person.PersonResource.update(com.pragmasphere.tictac.planning.services.auth.User,long,long,com.pragmasphere.tictac.planning.services.person.Person) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.person.PersonResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@70721c12]}, definitionMethod=public void com.pragmasphere.tictac.planning.services.person.PersonResource.update(com.pragmasphere.tictac.planning.services.auth.User,long,long,com.pragmasphere.tictac.planning.services.person.Person), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=long, source=environmentId, defaultValue=null], Parameter [type=long, source=id, defaultValue=null], Parameter [type=class com.pragmasphere.tictac.planning.services.person.Person, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public void com.pragmasphere.tictac.planning.services.person.PersonResource.save(com.pragmasphere.tictac.planning.services.auth.User,long,javax.ws.rs.core.HttpHeaders,long,com.pragmasphere.tictac.planning.services.person.Person) at index 0.; source='ResourceMethod{httpMethod=PUT, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.person.PersonResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@769bd849]}, definitionMethod=public void com.pragmasphere.tictac.planning.services.person.PersonResource.save(com.pragmasphere.tictac.planning.services.auth.User,long,javax.ws.rs.core.HttpHeaders,long,com.pragmasphere.tictac.planning.services.person.Person), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=long, source=environmentId, defaultValue=null], Parameter [type=interface javax.ws.rs.core.HttpHeaders, source=null, defaultValue=null], Parameter [type=long, source=id, defaultValue=null], Parameter [type=class com.pragmasphere.tictac.planning.services.person.Person, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public com.pragmasphere.tictac.planning.services.person.Person com.pragmasphere.tictac.planning.services.person.PersonResource.create(com.pragmasphere.tictac.planning.services.auth.User,long,com.pragmasphere.tictac.planning.services.person.Person) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.person.PersonResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@101ca8da]}, definitionMethod=public com.pragmasphere.tictac.planning.services.person.Person com.pragmasphere.tictac.planning.services.person.PersonResource.create(com.pragmasphere.tictac.planning.services.auth.User,long,com.pragmasphere.tictac.planning.services.person.Person), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=long, source=environmentId, defaultValue=null], Parameter [type=class com.pragmasphere.tictac.planning.services.person.Person, source=null, defaultValue=null]], responseType=class com.pragmasphere.tictac.planning.services.person.Person}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public void com.pragmasphere.utils.dropwizard.CrudAuthResource.save(java.lang.Object,javax.ws.rs.core.HttpHeaders,java.lang.Object,java.lang.Object) at index 0.; source='ResourceMethod{httpMethod=PUT, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.environment.EnvironmentResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@20a967fe]}, definitionMethod=public void com.pragmasphere.utils.dropwizard.CrudAuthResource.save(java.lang.Object,javax.ws.rs.core.HttpHeaders,java.lang.Object,java.lang.Object), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=interface javax.ws.rs.core.HttpHeaders, source=null, defaultValue=null], Parameter [type=class java.lang.Long, source=id, defaultValue=null], Parameter [type=class com.pragmasphere.tictac.planning.services.environment.Environment, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public void com.pragmasphere.utils.dropwizard.CrudAuthResource.update(java.lang.Object,java.lang.Object,java.lang.Object) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.environment.EnvironmentResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@405b6d75]}, definitionMethod=public void com.pragmasphere.utils.dropwizard.CrudAuthResource.update(java.lang.Object,java.lang.Object,java.lang.Object), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=class java.lang.Long, source=id, defaultValue=null], Parameter [type=class com.pragmasphere.tictac.planning.services.environment.Environment, source=null, defaultValue=null]], responseType=void}, nameBindings=[]}', [FATAL] No injection source found for a parameter of type public java.lang.Object com.pragmasphere.utils.dropwizard.CrudAuthResource.create(java.lang.Object,java.lang.Object) at index 0.; source='ResourceMethod{httpMethod=POST, consumedTypes=[application/json], producedTypes=[application/json], suspended=false, suspendTimeout=0, suspendTimeoutUnit=MILLISECONDS, invocable=Invocable{handler=ClassBasedMethodHandler{handlerClass=class com.pragmasphere.tictac.planning.services.environment.EnvironmentResource, handlerConstructors=[org.glassfish.jersey.server.model.HandlerConstructor@682abca7]}, definitionMethod=public java.lang.Object com.pragmasphere.utils.dropwizard.CrudAuthResource.create(java.lang.Object,java.lang.Object), parameters=[Parameter [type=class com.pragmasphere.tictac.planning.services.auth.User, source=null, defaultValue=null], Parameter [type=class com.pragmasphere.tictac.planning.services.environment.Environment, source=null, defaultValue=null]], responseType=class com.pragmasphere.tictac.planning.services.environment.Environment}, nameBindings=[]}']
    at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:467)
    at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:163)
    at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:323)
    at org.glassfish.jersey.internal.Errors$2.call(Errors.java:289)
    at org.glassfish.jersey.internal.Errors$2.call(Errors.java:286)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
    at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:286)
    at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:320)
    at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:285)
    at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:311)
    at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:170)
    at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:358)
    at javax.servlet.GenericServlet.init(GenericServlet.java:244)
    at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
    ... 36 more
```

**Comment by chrishaum** [comment]
I'm actually still seeing this issue after upgrading from 0.7.x to 0.8.x.

I'm using the new AuthFactory.binder(authFactory) registration, but my @Auth annotation is still causing errors similar to the one above.

Does anybody have any ideas for other ways to fix this?
