### ISSUE TITLE
Breaking change in a version between 4.0.1 and 4.0.4

### ISSUE THREAD

**Issue by danjee** [dropwizard/dropwizard#7945]
AuthFilter now wants to inject an InjectionManager. Couldn't find anything related to this on the changelogs. 

Had to manually create a NoopInjectionManager

```java
package com.adswizz.awapi.v2.security;

import java.lang.annotation.Annotation;
import java.lang.reflect.Type;
import java.util.List;
import org.glassfish.jersey.internal.inject.Binder;
import org.glassfish.jersey.internal.inject.Binding;
import org.glassfish.jersey.internal.inject.ForeignDescriptor;
import org.glassfish.jersey.internal.inject.InjectionManager;
import org.glassfish.jersey.internal.inject.ServiceHolder;
import org.springframework.stereotype.Component;

@Component
public class NoopInjectionManager implements InjectionManager {
    @Override
    public void completeRegistration() {

    }

    @Override
    public void shutdown() {

    }

    @Override
    public boolean isShutdown() {
        return false;
    }

    @Override
    public void register(final Binding binding) {

    }

    @Override
    public void register(final Iterable<Binding> descriptors) {

    }

    @Override
    public void register(final Binder binder) {

    }

    @Override
    public void register(final Object provider) throws IllegalArgumentException {

    }

    @Override
    public boolean isRegistrable(final Class<?> clazz) {
        return false;
    }

    @Override
    public <T> T create(final Class<T> createMe) {
        return null;
    }

    @Override
    public <T> T createAndInitialize(final Class<T> createMe) {
        return null;
    }

    @Override
    public <T> List<ServiceHolder<T>> getAllServiceHolders(
            final Class<T> contractOrImpl, final Annotation... qualifiers) {
        return null;
    }

    @Override
    public <T> T getInstance(final Class<T> contractOrImpl, final Annotation... qualifiers) {
        return null;
    }

    @Override
    public <T> T getInstance(final Class<T> contractOrImpl, final String classAnalyzer) {
        return null;
    }

    @Override
    public <T> T getInstance(final Class<T> contractOrImpl) {
        return null;
    }

    @Override
    public <T> T getInstance(final Type contractOrImpl) {
        return null;
    }

    @Override
    public Object getInstance(final ForeignDescriptor foreignDescriptor) {
        return null;
    }

    @Override
    public ForeignDescriptor createForeignDescriptor(final Binding binding) {
        return null;
    }

    @Override
    public <T> List<T> getAllInstances(final Type contractOrImpl) {
        return null;
    }

    @Override
    public void inject(final Object injectMe) {

    }

    @Override
    public void inject(final Object injectMe, final String classAnalyzer) {

    }

    @Override
    public void preDestroy(final Object preDestroyMe) {

    }
}
``` 
to get around this.

Error in logs was:

```
4c9f14Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.glassfish.jersey.internal.inject.InjectionManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@jakarta.inject.Inject()}
4c9f14	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1824)
4c9f14	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1383)
4c9f14	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1337)
4c9f14	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:711)
```

**Comment by zUniQueX** [comment]
Hi @danjee. This was introduced in #7537. The `InjectionManager` is nullable there.

We don't officially support Spring DI and there's no problem with Jersey DI and HK2. I can't imagine why someone wants to use dropwizard-auth in a Spring project instead of Spring security. Is the a regular use-case I'm missing?

**Comment by danjee** [comment]
We setup the spring context programmatically like this ```java
AnnotationConfigApplicationContext context =
                new AnnotationConfigApplicationContext(MyConfig.class);```
Yes, our security is based on the AuthFilter and for our needs is more suited than spring security. At the moment, frankly I cannot keep up with the changes that happens in spring security. Neither does baeldung, the tutorial site.

**Comment by zUniQueX** [comment]
@danjee If you really need to do this, I'd suggest to sync the DI containers. There is a [bridge](https://www.javadoc.io/doc/org.glassfish.hk2/spring-bridge/latest/org.glassfish.hk2.spring.bridge/org/jvnet/hk2/spring/bridge/api/SpringBridge.html) between Spring and HK2. To use this bridge with HK2, Jersey has the [`ImmediateHk2InjectionManager`](https://eclipse-ee4j.github.io/jersey.github.io/apidocs/2.35/jersey/org/glassfish/jersey/inject/hk2/ImmediateHk2InjectionManager.html).
