### ISSUE TITLE
NPE in tests when a factory is used to inject a value to a resource method parameter

### ISSUE THREAD

**Issue by StanSvec** [dropwizard/dropwizard#7989]
> Check existing issues to see if it has been addressed already

404 Not Found

> The version of Dropwizard you are using

v4.0.4 (Java 21)

> A short description of the issue you are experiencing and the expected outcome

An implementation of the `org.glassfish.hk2.api.Factory` can be configured in the `AbstractBinder` to allow injecting custom values into HK2 managed services and resources. One of the possible usages is injecting a value into a resource method parameter with the `@Context` annotation. This setup works fine in production code but produces a `NullPointerException` when a test is run using the `DropwizardExtensionsSupport` mechanism.

> Description of how someone else can reproduce the problem

Create `ResourceExtension` and add an abstract binder provider which binds a factory to a type:
```
 private static final ResourceExtension EXT = ResourceExtension.builder()
            .addProvider(new AbstractBinder() {
                @Override
                protected void configure() {
                    bindFactory(IPAddressFactory.class).to(IPAddress.class).in(RequestScoped.class);
                }
            })
            .addResource(new TestResource())
            .build();
```

> Paste error output or logs in your issue or in a Gist.

```
/long stack trace here followed by:
Caused by: A MultiException has 3 exceptions.  They are:
1. java.lang.NullPointerException: Cannot invoke "org.glassfish.jersey.server.internal.process.RequestProcessingContext.request()" because the return value of "org.glassfish.jersey.server.internal.process.RequestProcessingContextReference.get()" is null
2. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of com.taggstar.restapi.util.IPAddressFactory errors were found
3. java.lang.IllegalStateException: Unable to perform operation: resolve on com.taggstar.restapi.util.IPAddressFactory

	at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:65)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:250)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:388)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.jvnet.hk2.internal.PerLookupContext.findOrCreate(PerLookupContext.java:46)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:67)
	at org.jvnet.hk2.internal.FactoryCreator.dispose(FactoryCreator.java:151)
	at org.jvnet.hk2.internal.SystemDescriptor.dispose(SystemDescriptor.java:521)
	at org.glassfish.jersey.inject.hk2.RequestContext.lambda$findOrCreate$0(RequestContext.java:60)
	at org.glassfish.jersey.internal.inject.ForeignDescriptorImpl.dispose(ForeignDescriptorImpl.java:63)
	at org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.remove(Hk2RequestScope.java:126)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at org.glassfish.jersey.inject.hk2.Hk2RequestScope$Instance.release(Hk2RequestScope.java:143)
	at org.glassfish.jersey.process.internal.RequestScope.release(RequestScope.java:246)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:267)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:235)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:684)
	at org.glassfish.jersey.test.inmemory.InMemoryConnector.apply(InMemoryConnector.java:251)
	at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:300)
	... 15 more
Caused by: java.lang.NullPointerException: Cannot invoke "org.glassfish.jersey.server.internal.process.RequestProcessingContext.request()" because the return value of "org.glassfish.jersey.server.internal.process.RequestProcessingContextReference.get()" is null
	at org.glassfish.jersey.server.internal.process.RequestProcessingConfigurator$ContainerRequestFactory.get(RequestProcessingConfigurator.java:67)
	at org.glassfish.jersey.server.internal.process.RequestProcessingConfigurator$ContainerRequestFactory.get(RequestProcessingConfigurator.java:56)
	at org.glassfish.jersey.inject.hk2.SupplierFactoryBridge.provide(SupplierFactoryBridge.java:76)
	at org.jvnet.hk2.internal.FactoryCreator.create(FactoryCreator.java:129)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:466)
	at org.glassfish.jersey.inject.hk2.RequestContext.findOrCreate(RequestContext.java:59)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2109)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:93)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:690)
	at org.jvnet.hk2.internal.ThreeThirtyResolver.resolve(ThreeThirtyResolver.java:55)
	at org.jvnet.hk2.internal.ClazzCreator.resolve(ClazzCreator.java:198)
	at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:215)
	... 34 more
```

> Write a unit test to show the issue!

Please run the test located here:
https://github.com/StanSvec/dropwizard-test-issue/blob/main/src/test/java/resource/ResourceTest.java

The repository contains a minimum code to replicate the issue.

Many thanks!

**Comment by joschi** [comment]
@StanSvec Please try using a full-fledged container for Jersey in your tests such as Grizzly2 or Jetty.

https://www.dropwizard.io/en/release-4.0.x/manual/testing.html#test-containers

**Comment by StanSvec** [comment]
Thanks, @joschi, for showing me where the problem was. My bad. I should have read the documentation more carefully. It works fine with the Grizzly2 container when it's not the newest version. I had success with this one:
```
        <dependency>
            <groupId>org.glassfish.jersey.test-framework.providers</groupId>
            <artifactId>jersey-test-framework-provider-grizzly2</artifactId>
            <version>3.0.12</version>
            <scope>test</scope>
        </dependency>
```
