### ISSUE TITLE
Exporting ehCache metrics to Elasticsearch causes NaN error 

### ISSUE THREAD

**Issue by kmandeville** [dropwizard/dropwizard#897]
I set up ehCache metrics collection with the Dropwizard metrics in my Spring Boot app. I set up a vanilla elasticsearch server and set up a Scheduled job to use ElasticsearchReporter. Looks like the timestamp data from the ehcache metrics is causing elasticsearch to stumble: 

[2015-02-24 18:07:28,426][DEBUG][action.bulk              ] [Bora] [metrics-2015-02][4] failed to execute bulk item (index) index {[metrics-2015-02][gauge][szcN3Lg4QcCm7aZP3UyOhA], source[{"name":"net.sf.ehcache.Cache.com.xxx.xxx.xxx.CustomerPromotion.mean-search-time","@timestamp":"2015-02-24T18:07:26.000+0000","value":"NaN"}]}
org.elasticsearch.index.mapper.MapperParsingException: failed to parse [value]
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:418)
	at org.elasticsearch.index.mapper.object.ObjectMapper.serializeValue(ObjectMapper.java:616)
	at org.elasticsearch.index.mapper.object.ObjectMapper.parse(ObjectMapper.java:469)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:515)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:462)
	at org.elasticsearch.index.shard.service.InternalIndexShard.prepareCreate(InternalIndexShard.java:363)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardIndexOperation(TransportShardBulkAction.java:406)
	at org.elasticsearch.action.bulk.TransportShardBulkAction.shardOperationOnPrimary(TransportShardBulkAction.java:157)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction.performOnPrimary(TransportShardReplicationOperationAction.java:556)
	at org.elasticsearch.action.support.replication.TransportShardReplicationOperationAction$AsyncShardOperationAction$1.run(TransportShardReplicationOperationAction.java:426)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "NaN"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Long.parseLong(Long.java:441)
	at java.lang.Long.parseLong(Long.java:483)
	at org.elasticsearch.common.xcontent.support.AbstractXContentParser.longValue(AbstractXContentParser.java:145)
	at org.elasticsearch.index.mapper.core.LongFieldMapper.innerParseCreateField(LongFieldMapper.java:297)
	at org.elasticsearch.index.mapper.core.NumberFieldMapper.parseCreateField(NumberFieldMapper.java:215)
	at org.elasticsearch.index.mapper.core.AbstractFieldMapper.parse(AbstractFieldMapper.java:408)

**Comment by arteam** [comment]
@kmandeville  Are you sure your problem is related to the Dropwizard project?
From the log you provided, I don't see anything that links it with the io.dropwizard package, under which the project is distributed.

If you believe that the problem is with Dropwizard Metrics - it's a separate project under Dropwizard organization. You can open an issue there.

**Comment by joschi** [comment]
Additionally the Elasticsearch metrics reporter is maintained by Elasticsearch: https://github.com/elasticsearch/elasticsearch-metrics-reporter-java
